simple = [
    "Infračervená kamera je aktivní.",
    "Teplota cíle je vysoká.",
    "Analyzujeme tepelný podpis.",
    "Termální obraz je jasný.",
    "Noční vidění je zapnuto.",
    "Detekován zdroj tepla.",
    "Zaměřujeme horké body.",
    "Tepelná mapa generována.",
    "Optimalizace obrazu probíhá.",
    "Viditelnost je dobrá.",
    "IR senzor je kalibrován.",
    "Horké místo potvrzeno.",
    "Přepínáme na infračervený režim.",
    "Analýza spektra dokončena.",
    "Zvýšená teplota v oblasti.",
    "FLIR systém je připraven.",
    "Infračervená detekce je přesná.",
    "Teplotní rozdíly zaznamenány.",
    "Zaznamenán pohyb v infračerveném spektru.",
    "Senzory jsou plně funkční.",
    "Zaměřujeme se na tepelné změny.",
    "IR filtr aplikován.",
    "Viditelnost v mlze zlepšena.",
    "Termovizní skenování zahájeno.",
    "Infračervené spektrum je stabilní.",
    "Zaměřujeme se na tepelný cíl.",
    "Detekujeme únik tepla.",
    "Snímek termokamery uložen.",
    "Zvyšujeme kontrast tepelného obrazu.",
    "Tepelný obraz analyzován.",
    "Noční vidění je stabilní.",
    "Termální citlivost je optimalizována.",
    "Horká oblast identifikována.",
    "Analyzujeme tepelné odrazy.",
    "FLIR kamera je zapnutá.",
    "Detekce anomálií probíhá.",
    "Kalibrace teplotních senzorů dokončena.",
    "Monitorujeme infračervené spektrum.",
    "Tepelný zdroj je potvrzen.",
    "Přepínáme mezi termálními režimy.",
    "Systém automatického zaměřování aktivován.",
    "Zaznamenáváme tepelné emise.",
    "Teplotní mapování je dokončeno.",
    "Detekujeme změny teploty v čase.",
    "Přepínáme na noční režim.",
    "Infračervené čidlo aktivní.",
    "Zachycen pohyb na tepelném snímku.",
    "Zlepšujeme kontrast termovize.",
    "FLIR skener inicializován.",
    "Tepelná detekce běží hladce.",
    "Analýza infračervených dat probíhá.",
    "Senzory detekují vysokou teplotu.",
    "Přepínání mezi teplotními režimy.",
    "Termální obraz je ostrý.",
    "Noční vidění je vylepšené.",
    "Tepelná kamera zachytila objekt.",
    "Sledování teplotních variací.",
    "Teplotní analyzátor aktivován.",
    "FLIR detekce pracuje optimálně.",
    "Zaznamenáváme neznámé tepelné objekty.",
    "Systém infračervené analýzy spuštěn.",
    "Termální kamera detekuje anomálii.",
    "Tepelná emise analyzována.",
    "FLIR kamera zaměřuje pohyb.",
    "Přepínáme na maximální citlivost.",
    "Zaznamenali jsme tepelný vzorec.",
    "Automatická detekce horkých bodů.",
    "Senzory kalibrovány pro lepší přesnost.",
    "Noční režim je optimalizován.",
    "Termovizní senzor plně funkční.",
    "Detekujeme skryté zdroje tepla.",
    "Horké místo bylo potvrzeno senzory.",
    "Infračervený skener zachytil cíl.",
    "Termální snímky analyzovány.",
    "Monitorujeme tepelný tok.",
    "FLIR kamera nastavena na široký úhel.",
    "Termální kontrast upraven.",
    "Tepelný signál stabilní.",
    "FLIR snímek exportován.",
    "Horké objekty zvýrazněny.",
    "Noční vidění zesíleno.",
    "IR spektrum analyzováno.",
    "Zaznamenáváme infračervené záření.",
    "Infračervený filtr aktivován.",
    "Teplotní analýza probíhá.",
    "Infračervený obraz je optimalizován.",
    "FLIR systém připraven k použití.",
    "Přepínání mezi teplotními vrstvami.",
    "Skenujeme infračervený rozsah.",
    "Teplotní senzory jsou v pohotovosti.",
    "FLIR detekuje vysokou intenzitu tepla.",
    "Monitorujeme infračervené signály.",
    "Detekujeme tepelné nehomogenity.",
    "Systém FLIR v provozu.",
    "Termovizní detekce aktivována.",
    "Kalibrace infračervených senzorů.",
    "Analyzujeme tepelné mapy.",
    "Tepelná anomálie potvrzena.",
    "FLIR záznam je připraven.",
    "Zvýšený tepelný kontrast.",
    "Přepínáme mezi infračervenými režimy."
]

advance = [
    "Tvoje oči jsou jako magnet, přitahují mě bez odporu.",
    "Jsi důvod, proč věřím v lásku na první pohled.",
    "Můžu se ztratit v tvém úsměvu na celý den.",
    "Kdybys byla sen, nikdy bych se nechtěl probudit.",
    "Jsi tak krásná, že bych tě rád maloval, ale bojím se, že by to umění neuneslo.",
    "Tvoje přítomnost je jako melodie, kterou si nechci přestat zpívat.",
    "Pokud bych měl jedinou hvězdu pro každý tvůj úsměv, měl bych vlastní galaxii.",
    "Jsi jako WiFi, protože cítím silné spojení.",
    "Kdybych byl malíř, použil bych všechny barvy světa jen na tebe.",
    "Jsi jako kniha, kterou bych nikdy nechtěl přestat číst.",
    "Můj den se rozzáří, jakmile tě uvidím.",
    "Máš v očích něco, co mě nutí věřit v zázraky.",
    "Můžeš mi půjčit mapu? Protože jsem se ztratil v tvém pohledu.",
    "Nejkrásnější květina by vedle tebe jen bledla.",
    "Máš klíč od mého srdce, aniž bys o to žádala.",
    "Kdybys byla slunce, nikdy bych nepotřeboval jiný zdroj světla.",
    "Když se na tebe podívám, zapomínám na všechny starosti.",
    "Tvoje krása je tak oslnivá, že nepotřebuji světlo.",
    "Jsi jako tajemství, které chci objevovat každý den.",
    "Tvoje slova jsou jako melodie, která mi hraje v srdci.",
    "V přítomnosti tvého úsměvu všechno ostatní bledne.",
    "Kdybys byla píseň, hrál bych ji pořád dokola.",
    "Jsi jako báseň, kterou chci číst stále dokola.",
    "Každá minuta strávená s tebou je jako poklad.",
    "Tvoje přítomnost je jako kouzlo, které mě okouzluje.",
    "Nejlepší věci v životě přicházejí nečekaně – stejně jako ty.",
    "Tvoje energie je tak nakažlivá, že se vedle tebe vždy cítím šťastně.",
    "Jsi jako zářící hvězda, kterou nikdy nechci přestat sledovat.",
    "Můžu s tebou sdílet svůj svět? Protože bez tebe není úplný.",
    "Když jsi poblíž, i déšť se zdá být slunečním svitem.",
    "Jsi tak okouzlující, že bys mohla zastavit čas.",
    "Tvoje láska je jediná hádanka, kterou chci celý život řešit.",
    "Jsi odpověď na všechny otázky, které jsem kdy měl o lásce.",
    "Tvůj hlas je jako hudba, kterou si chci pouštět stále dokola.",
    "Tvůj dotek je jako magie, která mě rozechvívá.",
    "Každý den strávený s tebou je jako pohádka.",
    "Tvoje smích je jako lék, který vždycky potřebuji.",
    "Můžeš mi říct tajemství? Jak můžeš být tak úžasná?",
    "Jsi ten nejkrásnější sen, který se mi kdy zdál.",
    "Jsi ten nejlepší důvod, proč věřit na osud.",
    "Nejlepší momenty v životě jsou ty, kdy jsem s tebou.",
    "Tvoje krása není jen ve tváři, ale i v srdci.",
    "Tvůj úsměv je jako sluneční paprsek, který mi vždy zlepší den.",
    "Pokud je láska hra, pak chci hrát jen s tebou.",
    "Jsi jako teplá káva v zimní ráno – naprosto dokonalá.",
    "Nikdy jsem nevěřil v osud, dokud jsem nepotkal tebe.",
    "Myslím, že mám alergii... protože kdykoli tě vidím, zapomínám dýchat.",
    "Jsi tak kouzelná, že když jsi poblíž, všechno ostatní se zdá nedůležité.",
    "Tvoje jméno by mělo být v encyklopedii pod slovem 'dokonalost'.",
    "Pokud bych měl možnost splnit si jedno přání, přál bych si být navždy s tebou.",
    "Tvoje srdce je místo, kde chci zůstat navždy.",
    "Kdybych mohl zastavit čas, zastavil bych ho vždy, když jsme spolu.",
    "Jsi jako krásná písnička, kterou si nikdy neomrzím.",
    "Nikdy jsem nevěřil na lásku na první pohled, dokud jsem nepotkal tebe.",
    "Jsi odpověď na všechny mé otázky o lásce.",
    "Kdybys byla obraz, nikdy bych se na tebe nepřestal dívat.",
    "Jsi ten nejkrásnější důvod, proč se usmívat.",
    "Tvoje přítomnost je jako léto v zimě – nečekaná, ale nádherná.",
    "Máš klíč k mému srdci, a ani jsi si ho nemusela brát.",
    "Když tě vidím, svět kolem mě zmizí.",
    "Jsi jako sluneční paprsek v zamračeném dni.",
    "Můžeš mi říct, jak to děláš, že jsi tak okouzlující?",
    "Tvoje oči jsou jako oceán, do kterého se chci ponořit.",
    "Tvoje láska je jako pohádka, ve které chci žít.",
    "Jsi důvod, proč se každý den těším na nový den.",
    "Můžeš mě naučit, jak nebýt okouzlený tvou krásou?",
    "Každý okamžik s tebou je jako sen.",
    "Jsi nejkrásnější kapitola mého života.",
    "Jsi jako zářící hvězda, kterou nikdy nechci ztratit z dohledu.",
    "Tvůj úsměv je kouzlo, které mě vždy přiměje cítit se lépe.",
    "Máš tak úžasnou energii, že vedle tebe všechno ožívá.",
    "Tvoje přítomnost mě dělá nejšťastnějším člověkem na světě.",
    "Pokud je život cesta, pak ty jsi moje nejoblíbenější zastávka.",
    "Tvůj smích je melodie, kterou chci slyšet každý den.",
    "Můžu si tě nechat na celý život?"
]

cs_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
