simple = [
    "Er du en troldmand? For hver gang jeg kigger på dig, forsvinder alle andre.",
    "Jeg må være en snefnug, fordi jeg er faldet for dig.",
    "Er din far en tyv? Fordi han stjal alle stjernerne og lagde dem i dine øjne.",
    "Er du en GPS? Fordi du altid viser mig vejen til dit hjerte.",
    "Dit smil lyser op i mit liv mere end solen.",
    "Er du en engel? Fordi himlen mangler en.",
    "Jeg må være et bogstav, fordi jeg er vild med dig.",
    "Er du en magnet? Fordi jeg bliver trukket mod dig.",
    "Du er ligesom min yndlingssang – jeg kan ikke få dig ud af mit hoved.",
    "Kan jeg følge dig hjem? For mine forældre sagde, at jeg skal følge mine drømme.",
    "Er du WiFi? Fordi jeg føler en stærk forbindelse.",
    "Hvis skønhed var en forbrydelse, ville du være livstidsfange.",
    "Er du solskin? Fordi du lyser min dag op.",
    "Dit smil smelter mit hjerte som chokolade i solen.",
    "Hvis jeg kunne omarrangere alfabetet, ville jeg sætte U og I sammen.",
    "Kan jeg låne et kort? Fordi jeg bliver ved med at fare vild i dine øjne.",
    "Hvis du var en frugt, ville du være en ‘fin-appel’ (pineapple).",
    "Er du kaffe? Fordi du holder mig vågen hele natten.",
    "Dit smil er mere værdifuldt end guld.",
    "Du er grunden til, at jeg tror på kærlighed ved første blik.",
    "Er du en drøm? Fordi jeg vil aldrig vågne op fra dig.",
    "Hvis du var en bog, ville du være min yndlingsside.",
    "Er du en kunstner? Fordi du har tegnet mit hjerte.",
    "Du må være en stjerne, for du lyser op i min mørkeste nat.",
    "Kan du hjælpe mig? Jeg har tabt mit telefonnummer, kan jeg få dit?",
    "Du er det eneste, der giver mening i en meningsløs verden.",
    "Mit hjerte banker hurtigere, hver gang du er tæt på.",
    "Du er den perfekte balance mellem skønhed og charme.",
    "Du har et smil, der kan redde en dårlig dag.",
    "Er du en bog? Fordi jeg vil aldrig stoppe med at læse dig.",
    "Jeg har søgt efter lykke, og jeg fandt dig.",
    "Du er som en solnedgang – smuk og umulig at ignorere.",
    "Jeg er ikke fotograf, men jeg kan forestille os sammen.",
    "Er du en tryllekunstner? Fordi hver gang du smiler, forsvinder alt andet.",
    "Kan jeg tage dig ud til middag, eller er vi allerede ude?",
    "Er du en komet? Fordi du har sat ild til mit hjerte.",
    "Du er sødere end chokolade.",
    "Du må være en engel, fordi du har vinger i mit hjerte.",
    "Er du en skjult skat? Fordi jeg har ledt efter dig hele mit liv.",
    "Jeg vidste ikke, at stjerner kunne falde ned fra himlen, før jeg mødte dig.",
    "Hvis kys var en regndråbe, ville jeg sende dig en storm.",
    "Du er den mest interessante side i min livshistorie.",
    "Jeg er ikke matematiker, men du og jeg giver perfekt mening.",
    "Er du en pil? Fordi du har ramt mit hjerte direkte.",
    "Hvis jeg var en kat, ville jeg bruge alle mine ni liv på dig.",
    "Kan du lide gåder? Fordi svaret på alle mine er dig.",
    "Du må være en stjerne, for du lyser mit liv op.",
    "Jeg er ikke videnskabsmand, men du må være ren kemi.",
    "Er du et eventyr? Fordi du er magisk.",
    "Hvis du var en film, ville du være min yndlingsscene.",
    "Jeg ville gå tusind mil for at se dit smil.",
    "Du er som en sød drøm, jeg ikke vil vågne op fra.",
    "Hvis du var en sang, ville jeg spille dig på repeat.",
    "Jeg behøver ikke kaffe, du vækker mig op nok.",
    "Du er som en sommerbrise – opfriskende og uimodståelig.",
    "Hvis kærlighed var en sport, ville vi være verdensmestre.",
    "Er du et spejl? Fordi jeg ser mit liv i dine øjne.",
    "Du har den smukkeste sjæl, jeg nogensinde har mødt.",
    "Hvis du var en blomst, ville du være den sjældneste og smukkeste.",
    "Er du en stjernehimmel? Fordi jeg kunne stirre på dig hele natten.",
    "Du har stjålet mit hjerte, og jeg vil aldrig have det tilbage.",
    "Er du et fyrværkeri? Fordi du får mit hjerte til at eksplodere.",
    "Du er den perfekte kombination af sød og sjov.",
    "Jeg tror, vi ville lave et fantastisk eventyr sammen.",
    "Er du en regnbue? Fordi du bringer farve til mit liv.",
    "Hvis skønhed var tid, ville du være evigheden.",
    "Er du en magisk eliksir? Fordi jeg er fortryllet af dig."
]

