simple = [
    "Er du en troldmand? For hver gang jeg kigger på dig, forsvinder alle andre.",
    "Jeg må være en snefnug, fordi jeg er faldet for dig.",
    "Er din far en tyv? Fordi han stjal alle stjernerne og lagde dem i dine øjne.",
    "Er du en GPS? Fordi du altid viser mig vejen til dit hjerte.",
    "Dit smil lyser op i mit liv mere end solen.",
    "Er du en engel? Fordi himlen mangler en.",
    "Jeg må være et bogstav, fordi jeg er vild med dig.",
    "Er du en magnet? Fordi jeg bliver trukket mod dig.",
    "Du er ligesom min yndlingssang – jeg kan ikke få dig ud af mit hoved.",
    "Kan jeg følge dig hjem? For mine forældre sagde, at jeg skal følge mine drømme.",
    "Er du WiFi? Fordi jeg føler en stærk forbindelse.",
    "Hvis skønhed var en forbrydelse, ville du være livstidsfange.",
    "Er du solskin? Fordi du lyser min dag op.",
    "Dit smil smelter mit hjerte som chokolade i solen.",
    "Hvis jeg kunne omarrangere alfabetet, ville jeg sætte U og I sammen.",
    "Kan jeg låne et kort? Fordi jeg bliver ved med at fare vild i dine øjne.",
    "Hvis du var en frugt, ville du være en ‘fin-appel’ (pineapple).",
    "Er du kaffe? Fordi du holder mig vågen hele natten.",
    "Dit smil er mere værdifuldt end guld.",
    "Du er grunden til, at jeg tror på kærlighed ved første blik.",
    "Er du en drøm? Fordi jeg vil aldrig vågne op fra dig.",
    "Hvis du var en bog, ville du være min yndlingsside.",
    "Er du en kunstner? Fordi du har tegnet mit hjerte.",
    "Du må være en stjerne, for du lyser op i min mørkeste nat.",
    "Kan du hjælpe mig? Jeg har tabt mit telefonnummer, kan jeg få dit?",
    "Du er det eneste, der giver mening i en meningsløs verden.",
    "Mit hjerte banker hurtigere, hver gang du er tæt på.",
    "Du er den perfekte balance mellem skønhed og charme.",
    "Du har et smil, der kan redde en dårlig dag.",
    "Er du en bog? Fordi jeg vil aldrig stoppe med at læse dig.",
    "Jeg har søgt efter lykke, og jeg fandt dig.",
    "Du er som en solnedgang – smuk og umulig at ignorere.",
    "Jeg er ikke fotograf, men jeg kan forestille os sammen.",
    "Er du en tryllekunstner? Fordi hver gang du smiler, forsvinder alt andet.",
    "Kan jeg tage dig ud til middag, eller er vi allerede ude?",
    "Er du en komet? Fordi du har sat ild til mit hjerte.",
    "Du er sødere end chokolade.",
    "Du må være en engel, fordi du har vinger i mit hjerte.",
    "Er du en skjult skat? Fordi jeg har ledt efter dig hele mit liv.",
    "Jeg vidste ikke, at stjerner kunne falde ned fra himlen, før jeg mødte dig.",
    "Hvis kys var en regndråbe, ville jeg sende dig en storm.",
    "Du er den mest interessante side i min livshistorie.",
    "Jeg er ikke matematiker, men du og jeg giver perfekt mening.",
    "Er du en pil? Fordi du har ramt mit hjerte direkte.",
    "Hvis jeg var en kat, ville jeg bruge alle mine ni liv på dig.",
    "Kan du lide gåder? Fordi svaret på alle mine er dig.",
    "Du må være en stjerne, for du lyser mit liv op.",
    "Jeg er ikke videnskabsmand, men du må være ren kemi.",
    "Er du et eventyr? Fordi du er magisk.",
    "Hvis du var en film, ville du være min yndlingsscene.",
    "Jeg ville gå tusind mil for at se dit smil.",
    "Du er som en sød drøm, jeg ikke vil vågne op fra.",
    "Hvis du var en sang, ville jeg spille dig på repeat.",
    "Jeg behøver ikke kaffe, du vækker mig op nok.",
    "Du er som en sommerbrise – opfriskende og uimodståelig.",
    "Hvis kærlighed var en sport, ville vi være verdensmestre.",
    "Er du et spejl? Fordi jeg ser mit liv i dine øjne.",
    "Du har den smukkeste sjæl, jeg nogensinde har mødt.",
    "Hvis du var en blomst, ville du være den sjældneste og smukkeste.",
    "Er du en stjernehimmel? Fordi jeg kunne stirre på dig hele natten.",
    "Du har stjålet mit hjerte, og jeg vil aldrig have det tilbage.",
    "Er du et fyrværkeri? Fordi du får mit hjerte til at eksplodere.",
    "Du er den perfekte kombination af sød og sjov.",
    "Jeg tror, vi ville lave et fantastisk eventyr sammen.",
    "Er du en regnbue? Fordi du bringer farve til mit liv.",
    "Hvis skønhed var tid, ville du være evigheden.",
    "Er du en magisk eliksir? Fordi jeg er fortryllet af dig."
]

advance = [
    "Dit smil er som en hemmelighed, jeg gerne vil bruge hele mit liv på at afkode.",
    "Hvis vi var to bøger, ville vi være den perfekte kærlighedsroman.",
    "Din stemme er som en melodi, jeg kunne lytte til på repeat.",
    "Hver gang du ser på mig, føles det som et digt skrevet direkte til mit hjerte.",
    "Du er som en gåde, jeg aldrig vil løse, fordi jeg elsker mysteriet i dig.",
    "Hvis kærlighed var en kunstform, ville du være mit mesterværk.",
    "Dine øjne holder universets hemmeligheder, og jeg vil gerne bruge et liv på at opdage dem.",
    "Jeg har rejst verden rundt i mine drømme, men intet sted er smukkere end ved din side.",
    "Hvis du var en tidsmaskine, ville jeg rejse tilbage til øjeblikket, vi mødtes, igen og igen.",
    "At elske dig føles som at læse den bedste bog – jeg håber, historien aldrig slutter.",
    "Du er som en smuk sonet, skrevet i hjertet af en poet.",
    "Dit grin er som ekkoet af lykke, der danser i mit sind.",
    "Hvis vores kærlighed var en symfoni, ville den være uendelig.",
    "Når jeg holder din hånd, føler jeg, at jeg holder universet selv.",
    "Hvert sekund med dig føles som en scene fra en tidløs kærlighedsfilm.",
    "Dine kys er som poesi skrevet på mine læber.",
    "Du er den smukkeste tanke, mit sind nogensinde har skabt.",
    "Hvis stjernerne kunne tale, ville de synge sange om dig.",
    "Din kærlighed er som en flamme, der lyser op i mit mørkeste nat.",
    "Du er som en sjælden juvel – uvurderlig og uimodståelig.",
    "At være tæt på dig føles som at være i en drøm, jeg aldrig vil vågne fra.",
    "Du er penselstrøget, der gør mit livs lærred komplet.",
    "Hvis vi var to noter i et musikstykke, ville vi skabe den smukkeste harmoni.",
    "Hver samtale med dig føles som en rejse gennem stjernene.",
    "Dit blik får mit hjerte til at slå i en rytme, jeg aldrig før har kendt.",
    "Du er som en mystisk bog, jeg vil læse om og om igen.",
    "Jeg behøver ingen drømme, når jeg har dig i mit liv.",
    "Hvis jeg var en skulptør, ville jeg skabe mit mesterværk i dit billede.",
    "Du er det eneste eventyr, jeg nogensinde vil leve i.",
    "Din skønhed er som et maleri, der aldrig falmer.",
    "Hvis du var en blomst, ville du være den sjældneste i verden.",
    "Hver gang du smiler, skriver du en ny historie i mit hjerte.",
    "Jeg tror ikke på tilfældigheder – du og jeg var skæbnebestemt.",
    "Din kærlighed er en magisk potion, der fortryller min sjæl.",
    "Hvis hjertet havde et sprog, ville det tale dit navn.",
    "Dit nærvær gør selv de kedeligste dage til eventyr.",
    "Hvis jeg kunne male kærlighed, ville det ligne dig.",
    "Du er den eneste melodi, mit hjerte nogensinde vil spille.",
    "Jeg ser evigheden, hver gang jeg ser ind i dine øjne.",
    "Din kærlighed er en labyrint, jeg aldrig vil finde vej ud af.",
    "Hvis mit liv var en nattehimmel, ville du være min lyseste stjerne.",
    "Dine ord er som en sang, der synges direkte til mit hjerte.",
    "Du er som en vin, der kun bliver bedre med tiden.",
    "Hvis din kærlighed var en bog, ville jeg aldrig kunne lægge den fra mig.",
    "Dit navn er det smukkeste ord, jeg nogensinde har hørt.",
    "Hvis jeg var en kunstner, ville mit eneste motiv være dig.",
    "Din kærlighed er som en sjælden perle – skinnende og uerstattelig.",
    "Hver gang du taler, føles det som en smuk sonet i mit hjerte.",
    "Hvis jeg kunne give dig en gave, ville det være evigheden sammen.",
    "Du er som et digt skrevet af selve universet.",
    "At elske dig føles som at danse gennem stjernelyset.",
    "Du er drømmen, jeg aldrig vil vågne op fra.",
    "Din kærlighed er min yndlingshistorie, og jeg vil aldrig nå sidste kapitel.",
    "Hvis vores kærlighed var en blomst, ville den blomstre for evigt.",
    "Jeg ville skrive dig et kærlighedsbrev, men ord er ikke nok til at beskrive dig.",
    "Du er som en stille brise på en varm sommerdag – forfriskende og uundværlig.",
    "Hvis jeg var en astronom, ville jeg kalde en stjerne opkaldt efter dig.",
    "Din kærlighed er et eventyr, jeg aldrig vil forlade.",
    "Du er den smukkeste sonet, skrevet af tidens egen hånd.",
    "Hvis vores kærlighed var musik, ville den spille for evigt.",
    "Du er mere værdifuld end diamanter, fordi du skinner indefra.",
    "Når du er her, er hele verden fyldt med farver.",
    "Jeg ville rejse gennem tid og rum for at være hos dig.",
    "Du er som en skjult skat, jeg aldrig vil miste.",
    "Hvis kærlighed var en kunst, ville du være det ultimative mesterværk.",
    "Du er som et ekko af evigheden i mit hjerte.",
    "Dit smil er nøglen til mit hjertes mest hemmelige kammer.",
    "Hvis du var en sang, ville du være en symfoni af skønhed.",
    "Din kærlighed er en drøm, jeg aldrig vil vågne fra."
]

da_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
