simple = [
    "Bist du ein Zauberer? Denn jedes Mal, wenn ich dich ansehe, verschwinden alle anderen!",
    "Hast du eine Karte? Ich verliere mich ständig in deinen Augen.",
    "Glaubst du an Liebe auf den ersten Blick oder soll ich nochmal vorbeigehen?",
    "Ich dachte, Engel gibt es nur im Himmel, bis ich dich traf.",
    "Wenn Schönheit ein Verbrechen wäre, wärst du lebenslang im Gefängnis!",
    "Deine Augen sind wie Sterne – so hell und wunderschön!",
    "Darf ich dich auf einen Kaffee einladen? Oder bevorzugst du lieber eine heiße Schokolade?",
    "Hast du eine Sonne in der Tasche? Weil du mein Herz erwärmst!",
    "Darf ich dein persönlicher Kompass sein? Weil ich mich nur nach dir richte!",
    "Ich muss meine Nummer vergessen haben – kann ich deine haben?",
    "Deine Stimme klingt wie Musik in meinen Ohren.",
    "Hast du Magnete in deinen Händen? Ich fühle mich von dir angezogen!",
    "Hast du heute schon gelächelt? Falls nicht, darf ich der Grund sein?",
    "Ich glaube, ich brauche eine Sonnenbrille, dein Lächeln ist zu hell!",
    "Bist du ein WLAN-Signal? Weil ich eine starke Verbindung zu dir spüre!",
    "Wenn Küssen eine Sprache wäre, würde ich dir einen Roman schreiben!",
    "Hast du etwas Zucker? Weil du so süß bist!",
    "Wenn du eine Frucht wärst, wärst du eine süße Erdbeere!",
    "Bist du ein Maler? Weil du mein Leben in den schönsten Farben malst!",
    "Ich hätte fast die Welt bereist, aber dein Lächeln ist das schönste Reiseziel!",
    "Kannst du mir den Weg zu deinem Herzen zeigen? Ich glaube, ich habe mich verlaufen!",
    "Ich bin kein Fotograf, aber ich kann uns zusammen sehen!",
    "Ich habe mein Herz verloren. Hast du es vielleicht?",
    "Bist du ein Zaubertrank? Weil ich mich in dich verliebt habe!",
    "Bist du ein Spiegel? Denn ich sehe meine Zukunft in dir!",
    "Ich wünschte, ich wäre eine Träne in deinem Auge, um auf deiner Wange zu verweilen!",
    "Bist du ein Sonnenaufgang? Weil du meinen Tag erhellst!",
    "Wenn du eine Blume wärst, wärst du die schönste von allen!",
    "Ich habe meinen Namen vergessen – kann ich deinen stattdessen haben?",
    "Darf ich dich zum Lachen bringen? Denn dein Lächeln ist unbezahlbar!",
    "Bist du eine Kamera? Weil du jeden Moment perfekt machst!",
    "Bist du ein Puzzle? Weil du das fehlende Stück in meinem Leben bist!",
    "Bist du eine Sternschnuppe? Weil du alle meine Wünsche wahr machst!",
    "Wenn du ein Gedicht wärst, wärst du das schönste Versmaß!",
    "Bist du ein Ozean? Weil ich in dir versinken könnte!",
    "Dein Lächeln ist wie ein Sonnenstrahl an einem Regentag!",
    "Ich habe mich verlaufen – kannst du mir den Weg zu deinem Herzen zeigen?",
    "Bist du ein Kuss von der Sonne? Weil du mich so warm fühlen lässt!",
    "Wenn ich eine Blume für jedes Mal hätte, dass ich an dich denke, hätte ich einen Garten!",
    "Du bist wie mein Lieblingslied – ich kann nicht aufhören, an dich zu denken!",
    "Bist du ein Engel? Weil du den Himmel auf die Erde gebracht hast!",
    "Ich glaube, ich habe Schmetterlinge im Bauch – oder bist das du?",
    "Dein Lächeln ist ansteckend – jetzt kann ich nicht aufhören zu lächeln!",
    "Wenn Liebe eine Sprache wäre, würdest du mein Lieblingswort sein!",
    "Bist du eine Melodie? Weil ich nicht aufhören kann, dich zu summen!",
    "Bist du ein Edelstein? Weil du einfach unbezahlbar bist!",
    "Du bist der Grund, warum ich an Magie glaube!",
    "Bist du der Mond? Weil du meine Nächte erhellst!",
    "Wenn du eine Note wärst, wärst du die schönste in meiner Symphonie!",
    "Ich kann nicht glauben, dass ich jemanden wie dich getroffen habe!",
    "Bist du ein Leuchtturm? Weil du mich sicher nach Hause führst!",
    "Darf ich dich jeden Tag sehen? Sonst fehlt mir die Sonne!",
    "Ich glaube, mein Herz hat gerade deinen Namen geflüstert!",
    "Du bist das schönste Kapitel in meinem Buch des Lebens!",
    "Ich habe mich nicht verirrt, aber ich habe trotzdem dein Herz gefunden!",
    "Bist du eine Blume? Weil du so wunderschön duftest!",
    "Wenn du eine Farbe wärst, wärst du das schönste Spektrum meines Lebens!",
    "Ich habe ein Problem – ich kann nicht aufhören, an dich zu denken!",
    "Bist du ein Superheld? Weil du mein Herz im Sturm erobert hast!",
    "Du bist wie eine Kerze – du bringst Licht in mein Leben!",
    "Wenn Schönheit eine Zeit wäre, wärst du die Ewigkeit!",
    "Ich bin kein Mathematiker, aber du und ich ergeben 100%!",
    "Bist du ein Märchen? Weil du einfach zauberhaft bist!",
    "Ich brauche kein GPS – mein Herz führt mich direkt zu dir!"
]

advance = [
    "Wenn du ein Traum wärst, würde ich nie wieder aufwachen wollen.",
    "Dein Lächeln ist wie ein Gedicht, das mein Herz mit jeder Zeile berührt.",
    "Ich würde lieber einen Moment mit dir verbringen als eine Ewigkeit ohne dich.",
    "Bist du ein Zauberer? Denn du hast mich mit einem Blick verzaubert.",
    "Wenn du ein Buch wärst, würde ich dich nie aus der Hand legen.",
    "Bist du eine Sternschnuppe? Denn jeder Moment mit dir ist ein Wunsch, der in Erfüllung geht.",
    "Wenn deine Augen ein Universum wären, würde ich mich darin verlieren.",
    "Ich habe mein Herz verloren. Darf ich deines als Ersatz nehmen?",
    "Deine Berührung ist wie eine sanfte Brise an einem heißen Sommertag – erfrischend und unvergesslich.",
    "Mit dir ist jeder Moment wie ein perfektes Musikstück – harmonisch und voller Magie.",
    "Du bist wie ein edler Wein – je mehr Zeit ich mit dir verbringe, desto süßer wird das Leben.",
    "Wenn meine Gedanken ein Gemälde wären, wärst du das schönste Kunstwerk.",
    "Jede Sekunde ohne dich fühlt sich an wie eine Ewigkeit.",
    "Du bist nicht nur ein Teil meines Lebens – du bist die schönste Melodie meines Herzens.",
    "Ich würde tausend Gedichte schreiben, wenn es bedeuten würde, dass du sie liest.",
    "Bist du eine seltene Blume? Denn deine Schönheit ist einzigartig und unvergesslich.",
    "Du bist der Sonnenaufgang, der jede Dunkelheit in meinem Leben vertreibt.",
    "Wenn Liebe eine Sprache ist, dann bist du mein Lieblingswort.",
    "Darf ich der Grund sein, warum du heute Nacht von etwas Schönem träumst?",
    "Dein Blick ist wie ein geheimes Versprechen, das ich immer wieder entschlüsseln möchte.",
    "Wenn meine Gedanken ein Lied wären, würde jeder Ton nur von dir erzählen.",
    "Ich habe viele Träume, aber du bist der schönste, den ich je hatte.",
    "Du bist die Geschichte, die ich immer wieder lesen möchte.",
    "Wenn du ein Rätsel wärst, würde ich mein Leben lang nach der Lösung suchen.",
    "Ich habe viele Orte gesehen, aber dein Herz ist mein Lieblingsort.",
    "Dein Lachen ist der Klang, den meine Seele am liebsten hört.",
    "Wenn mein Herz sprechen könnte, würde es nur deinen Namen flüstern.",
    "Du bist nicht nur eine Erinnerung – du bist das schönste Kapitel meiner Geschichte.",
    "Jeder Tag mit dir fühlt sich an wie eine Liebesgeschichte, die nie endet.",
    "Wenn Liebe Kunst ist, dann bist du mein Meisterwerk.",
    "Mit dir ist selbst die Stille voller Melodie.",
    "Ich würde durch Feuer gehen, nur um dich lächeln zu sehen.",
    "Du bist wie der Ozean – tief, wunderschön und voller Geheimnisse.",
    "Ich wünschte, ich könnte die Zeit anhalten, wenn ich mit dir zusammen bin.",
    "Bist du ein Gedicht? Denn du bist voller schöner Worte und tiefer Bedeutung.",
    "Wenn ich in deinen Augen sehe, vergesse ich die ganze Welt um mich herum.",
    "Du bist wie ein kostbares Juwel – selten, wunderschön und unbezahlbar.",
    "Wenn unsere Seelen Musik wären, dann wären wir die schönste Symphonie.",
    "Bist du ein Kompass? Denn du zeigst mir immer den richtigen Weg – zu dir.",
    "Ich habe nach Glück gesucht, aber ich habe dich gefunden.",
    "Du bist nicht nur mein Sonnenstrahl – du bist mein ganzes Universum.",
    "Bist du ein Schmetterling? Denn jedes Mal, wenn du in meiner Nähe bist, schlägt mein Herz schneller.",
    "Wenn Schönheit eine Melodie wäre, dann wärst du das schönste Lied.",
    "Jeder Moment mit dir ist ein neues Abenteuer, das ich nie beenden möchte.",
    "Du bist wie ein Stern, der selbst in der dunkelsten Nacht leuchtet.",
    "Ich könnte tausend Bücher schreiben, aber keines könnte ausdrücken, was ich für dich empfinde.",
    "Ich bin kein Dichter, aber du inspirierst mich zu den schönsten Versen.",
    "Wenn deine Liebe ein Rätsel ist, dann möchte ich es für immer lösen.",
    "Ich würde mein Herz in deine Hände legen, weil ich weiß, dass es dort sicher ist.",
    "Mit dir fühlt sich selbst der Alltag wie ein Märchen an.",
    "Du bist die schönste Zufallsbegegnung meines Lebens.",
    "Wenn ich die Sterne zähle, denke ich an die unzähligen Gründe, warum ich dich liebe.",
    "Du bist wie ein warmer Sommerregen – sanft, erfrischend und voller Leben.",
    "Deine Augen sind wie das Meer – tief, unergründlich und voller Geheimnisse.",
    "Ich habe mein Zuhause gefunden – es ist in deinen Armen.",
    "Jede Sekunde mit dir ist wie ein wertvoller Schatz.",
    "Wenn Liebe eine Melodie wäre, dann wärst du das schönste Lied meines Lebens.",
    "Deine Berührung ist wie eine sanfte Brise, die mein Herz streichelt.",
    "Ich habe in deinen Augen das Paradies gefunden.",
    "Wenn Glück ein Ort wäre, dann wäre es überall dort, wo du bist.",
    "Bist du ein Leuchtturm? Denn du zeigst mir immer den richtigen Weg.",
    "Ich würde durch jede Dunkelheit gehen, um dein Licht zu sehen.",
    "Du bist wie ein Sternenhimmel – endlos faszinierend und wunderschön.",
    "Mit dir fühlt sich jede Sekunde wie eine Ewigkeit voller Liebe an.",
    "Wenn du ein Lied wärst, würde ich es auf Dauerschleife hören.",
    "Bist du eine Sonne? Denn du erwärmst mein Herz, egal wo ich bin.",
    "Ich würde alles geben, um dich für immer an meiner Seite zu haben.",
    "Dein Lächeln ist das schönste Geschenk, das ich je bekommen habe.",
    "Wenn Liebe eine Sprache ist, dann bist du meine Muttersprache.",
    "Ich sehe die Zukunft – und sie ist voller Liebe, weil du darin bist.",
    "Mit dir ist jeder Moment unvergesslich und einzigartig.",
    "Du bist nicht nur meine große Liebe – du bist mein Schicksal." 
]

de_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
