simple = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you French? Because Eiffel for you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a bank loan? Because you have my interest!",
    "Can you lend me a kiss? I promise I’ll give it back.",
    "Are you WiFi? Because I'm really feeling a connection.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Is your dad a boxer? Because you’re a knockout!",
    "Are you a time traveler? Because I see you in my future.",
    "Are you an electrician? Because you’re lighting up my life!",
    "Are you made of copper and tellurium? Because you’re Cu-Te!",
    "Do you like Star Wars? Because Yoda one for me!",
    "You must be a parking ticket because you’ve got ‘FINE’ written all over you.",
    "Are you a keyboard? Because you're just my type.",
    "Are you an angel? Because heaven is missing one.",
    "Are you a dictionary? Because you add meaning to my life.",
    "You must be a snowflake, because I've fallen for you.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "Do you believe in fate? Because I think we were meant to meet.",
    "Are you a sunrise? Because you brighten up my day.",
    "Are you a cloud? Because you make my heart float.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Are you a piece of art? Because I’d love to frame you.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you like coffee? Because I like you a latte.",
    "Are you a magician? Because whenever I see you, everyone else disappears.",
    "Is your name Chapstick? Because you’re da balm!",
    "Are you my phone charger? Because without you, I’d die.",
    "Do you like Harry Potter? Because I a-Dumbledore you!",
    "Are you a campfire? Because you make my heart melt.",
    "Are you a baker? Because you make my heart rise.",
    "Are you Cinderella? Because when I see you, time stops.",
    "Are you my favorite song? Because I can’t get you out of my head.",
    "Are you a shooting star? Because my wish just came true.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a beaver? Because daaaaam!",
    "Are you a jewel? Because you’re priceless.",
    "Are you a teddy bear? Because I want to cuddle with you forever.",
    "Are you a candle? Because you light up my world.",
    "Are you my dream? Because I never want to wake up.",
    "Are you the moon? Because even in the dark, you shine.",
    "Are you my compass? Because I keep getting drawn to you.",
    "Are you a riddle? Because you keep me intrigued.",
    "Are you a flower? Because you make my heart bloom.",
    "Are you a phone? Because I can’t stop checking you out.",
    "Are you an alarm clock? Because you just woke up my heart.",
    "Are you a rainbow? Because you bring color to my life.",
    "Are you a book? Because I can’t stop reading about you.",
    "Are you a sunset? Because I can’t take my eyes off you.",
    "Are you a diamond? Because you shine so bright.",
    "Are you a magnet? Because I’m so attracted to you.",
    "Are you a puzzle? Because you complete me.",
    "Are you an ice cream? Because you make everything sweeter.",
    "Are you a dream catcher? Because you make my dreams come true.",
    "Are you a mirror? Because I see my happiness in you.",
    "Are you the ocean? Because I’m lost at sea.",
    "Are you the sun? Because you brighten my day.",
    "Are you a genie? Because you just granted my wish.",
    "Are you a melody? Because you play on repeat in my heart.",
    "Are you a garden? Because you make my heart bloom.",
    "Are you a racecar? Because my heart races when I see you.",
    "Are you a twinkling star? Because you light up my night.",
    "Are you a lucky charm? Because I feel lucky around you.",
    "Are you a feather? Because you lift me up.",
    "Are you a treasure? Because I’ve been searching for you.",
    "Are you a firework? Because you make my heart explode.",
    "Are you a summer breeze? Because you make me feel alive.",
    "Are you a time machine? Because I want to spend forever with you.",
    "Are you a constellation? Because you complete my sky.",
    "Are you an oasis? Because you bring peace to my soul.",
    "Are you a cupcake? Because you’re so sweet.",
    "Are you a chocolate? Because you melt my heart.",
    "Are you a kite? Because you make my heart soar.",
    "Are you a festival? Because you bring joy into my life.",
    "Are you a melody? Because I can’t stop humming your tune.",
    "Are you a hug? Because I never want to let you go.",
    "Are you a lantern? Because you guide me home.",
    "Are you my heart? Because you beat just for me.",
    "Are you a lullaby? Because you soothe my soul.",
    "Are you a symphony? Because you harmonize my life.",
    "Are you a lighthouse? Because you guide me safely home.",
    "Are you a poem? Because every line about you is beautiful.",
    "Are you my favorite book? Because I never want to put you down."
]

advance = [
    "Your presence defies logic; how can one person radiate such celestial magnetism?",
    "If time were infinite, I'd still choose to spend every moment lost in your gaze.",
    "Your voice is a siren's call, entrancing me beyond the bounds of reason.",
    "If beauty were a currency, you'd be the wealthiest soul to ever exist.",
    "You must have been sculpted by the gods themselves, for mortals were never meant to be this divine.",
    "Every heartbeat of mine composes a symphony, each note dedicated solely to you.",
    "Are you woven from the cosmos itself? Because your existence outshines the stars.",
    "Gravity is a mere suggestion when I'm around you; you lift me beyond earthly constraints.",
    "You intoxicate my senses more potently than the finest wine ever crafted.",
    "Your touch is alchemy, transmuting the ordinary into something spellbinding.",
    "If my thoughts were constellations, your presence would be their brightest star.",
    "You are the missing equation in my life's unsolvable puzzle.",
    "Time slows when you're near, as if the universe itself lingers to admire you.",
    "You have a gravitational pull stronger than any force known to science, and I'm utterly drawn in.",
    "If words were enough, I’d write you a sonnet so profound the heavens themselves would weep.",
    "Your laughter is a melody that renders all other symphonies obsolete.",
    "Your elegance eclipses the grandest of sunsets, leaving all else in shadow.",
    "If I could bottle the essence of your charm, the world would be eternally drunk on love.",
    "Your gaze is a cosmic event, an eclipse that leaves me breathless.",
    "You are a poem that the universe spent eons perfecting.",
    "If love had a voice, it would echo your name across eternity.",
    "Your presence bends the laws of nature—how else can you be both fire and ice?",
    "To call you mesmerizing would be a gross understatement of your celestial allure.",
    "Your soul shines with such brilliance, even the night sky envies your radiance.",
    "If your beauty were a novel, every page would be a masterpiece.",
    "The air is sweeter when you're near, as if nature itself sighs in adoration.",
    "You redefine perfection with every move you make.",
    "Your embrace must be woven from moonlight and silk, for nothing else feels so ethereal.",
    "Are you a cosmic anomaly? Because my heart loses all sense of normal function around you.",
    "Your presence turns the mundane into a fairytale, where every moment is a stanza of poetry.",
    "If emotions were constellations, my love for you would paint the night sky.",
    "Your laughter is an enchantment that turns sorrow into stardust.",
    "Each word you speak is a verse, each glance a chapter, and each touch a novel I long to read.",
    "You are a living sonnet, each syllable crafted by destiny itself.",
    "With every heartbeat, my soul composes a love letter addressed solely to you.",
    "You are the crescendo in the symphony of my existence.",
    "How does it feel to be the sun that my entire world orbits around?",
    "Your presence is a brushstroke on the canvas of my soul, leaving hues of love and adoration.",
    "To compare you to the stars is an injustice—you outshine them effortlessly.",
    "You are the philosopher’s stone of my heart, turning every moment into pure gold.",
    "Your elegance is a language that needs no translation.",
    "Every whisper from your lips is an enchantment that binds me further in awe.",
    "You must be a celestial melody, for every note of you resonates in my very being.",
    "If my soul were a diary, every page would be filled with tales of you.",
    "Your existence is a verse that even Shakespeare could not have conceived.",
    "You are the unwritten poem the universe has long yearned to scribe.",
    "Your eyes are twin galaxies where my heart finds its home.",
    "To say you are dazzling is to misunderstand the magnitude of your light.",
    "Your voice lingers in the air like the sweetest refrain of a timeless melody.",
    "Are you a meteor shower? Because your beauty leaves me spellbound.",
    "Your grace is the rhythm that turns my chaos into a waltz.",
    "If attraction were an art, you would be the grandest masterpiece ever conceived.",
    "Your presence feels like moonlight dancing upon my skin.",
    "You are the enigma I never want to solve.",
    "With you, every moment is an uncharted adventure waiting to be lived.",
    "You wield charm with such finesse that even the stars seem to bow in admiration.",
    "Your name is the sweetest stanza in the poetry of my heart.",
    "You are the love letter the universe never had the courage to send.",
    "Your beauty isn’t just seen; it’s felt in the depths of my soul.",
    "If fate had fingerprints, they would be etched into the contours of your existence.",
    "Your essence lingers like the most exquisite perfume upon the air of my reality.",
    "You are the unseen force that turns my world effortlessly on its axis.",
    "Are you the pulse of the universe? Because every beat of my heart echoes your name.",
    "Your love is an intricate melody that my soul has been waiting to dance to.",
    "You must be a constellation of everything I’ve ever dreamed of.",
    "With every glance, you compose a love story without a single word.",
    "You are the rarest gem hidden within the cosmos of existence.",
    "Your presence is poetry that needs no ink to be written.",
    "You are the spell that keeps my heart eternally enchanted.",
    "Every heartbeat of mine sings a silent ode to you.",
    "You are the moonlight that turns my darkest nights into a dream.",
    "If love were a kingdom, your heart would be its throne.",
    "You are the serendipity that the universe conspired to bring into my life.",
    "Every second with you is a fragment of eternity worth cherishing.",
    "You are the cosmic wonder my soul has long sought after."
]

en_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
