
simple = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you French? Because Eiffel for you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a bank loan? Because you have my interest!",
    "Can you lend me a kiss? I promise I’ll give it back.",
    "Are you WiFi? Because I'm really feeling a connection.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Is your dad a boxer? Because you’re a knockout!",
    "Are you a time traveler? Because I see you in my future.",
    "Are you an electrician? Because you’re lighting up my life!",
    "Are you made of copper and tellurium? Because you’re Cu-Te!",
    "Do you like Star Wars? Because Yoda one for me!",
    "You must be a parking ticket because you’ve got ‘FINE’ written all over you.",
    "Are you a keyboard? Because you're just my type.",
    "Are you an angel? Because heaven is missing one.",
    "Are you a dictionary? Because you add meaning to my life.",
    "You must be a snowflake, because I've fallen for you.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "Do you believe in fate? Because I think we were meant to meet.",
    "Are you a sunrise? Because you brighten up my day.",
    "Are you a cloud? Because you make my heart float.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Are you a piece of art? Because I’d love to frame you.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Can you take a picture with me? I want to prove to my friends that angels are real.",
    "Do you like coffee? Because I like you a latte.",
    "Are you a magician? Because whenever I see you, everyone else disappears.",
    "Is your name Chapstick? Because you’re da balm!",
    "Are you my phone charger? Because without you, I’d die.",
    "Do you like Harry Potter? Because I a-Dumbledore you!",
    "Are you a campfire? Because you make my heart melt.",
    "Are you a baker? Because you make my heart rise.",
    "Are you Cinderella? Because when I see you, time stops.",
    "Are you my favorite song? Because I can’t get you out of my head.",
    "Are you a shooting star? Because my wish just came true.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a beaver? Because daaaaam!",
    "Are you a jewel? Because you’re priceless.",
    "Are you a teddy bear? Because I want to cuddle with you forever.",
    "Are you a candle? Because you light up my world.",
    "Are you my dream? Because I never want to wake up.",
    "Are you the moon? Because even in the dark, you shine.",
    "Are you my compass? Because I keep getting drawn to you.",
    "Are you a riddle? Because you keep me intrigued.",
    "Are you a flower? Because you make my heart bloom.",
    "Are you a phone? Because I can’t stop checking you out.",
    "Are you an alarm clock? Because you just woke up my heart.",
    "Are you a rainbow? Because you bring color to my life.",
    "Are you a book? Because I can’t stop reading about you.",
    "Are you a sunset? Because I can’t take my eyes off you.",
    "Are you a diamond? Because you shine so bright.",
    "Are you a magnet? Because I’m so attracted to you.",
    "Are you a puzzle? Because you complete me.",
    "Are you an ice cream? Because you make everything sweeter.",
    "Are you a dream catcher? Because you make my dreams come true.",
    "Are you a mirror? Because I see my happiness in you.",
    "Are you the ocean? Because I’m lost at sea.",
    "Are you the sun? Because you brighten my day.",
    "Are you a genie? Because you just granted my wish.",
    "Are you a melody? Because you play on repeat in my heart.",
    "Are you a garden? Because you make my heart bloom.",
    "Are you a racecar? Because my heart races when I see you.",
    "Are you a twinkling star? Because you light up my night.",
    "Are you a lucky charm? Because I feel lucky around you.",
    "Are you a feather? Because you lift me up.",
    "Are you a treasure? Because I’ve been searching for you.",
    "Are you a firework? Because you make my heart explode.",
    "Are you a summer breeze? Because you make me feel alive.",
    "Are you a time machine? Because I want to spend forever with you.",
    "Are you a constellation? Because you complete my sky.",
    "Are you an oasis? Because you bring peace to my soul.",
    "Are you a cupcake? Because you’re so sweet.",
    "Are you a chocolate? Because you melt my heart.",
    "Are you a kite? Because you make my heart soar.",
    "Are you a festival? Because you bring joy into my life.",
    "Are you a melody? Because I can’t stop humming your tune.",
    "Are you a hug? Because I never want to let you go.",
    "Are you a lantern? Because you guide me home.",
    "Are you my heart? Because you beat just for me.",
    "Are you a lullaby? Because you soothe my soul.",
    "Are you a symphony? Because you harmonize my life.",
    "Are you a lighthouse? Because you guide me safely home.",
    "Are you a poem? Because every line about you is beautiful.",
    "Are you my favorite book? Because I never want to put you down."
]
