simple = [
    "Eres un ladrón, porque te has robado mi corazón.",
    "Si besarte fuera pecado, caminaría feliz por el infierno.",
    "¿Crees en el amor a primera vista o debo pasar otra vez?",
    "Si la belleza fuera tiempo, tú serías la eternidad.",
    "No soy fotógrafo, pero puedo capturar tu sonrisa en mi corazón.",
    "Debes estar cansada porque has estado corriendo en mi mente todo el día.",
    "Si ser guapo fuera un delito, tendrías cadena perpetua.",
    "Quisiera ser el aire que respiras para estar siempre a tu lado.",
    "¿Eres un mago? Porque cada vez que te miro, todo lo demás desaparece.",
    "Si fueras un sueño, nunca querría despertar.",
    "Eres el café de mis mañanas, sin ti no puedo empezar el día.",
    "Tus ojos son como el mar: me pierdo en ellos.",
    "¿Tienes un mapa? Porque me he perdido en tu mirada.",
    "Si las estrellas brillan es porque saben que estás aquí.",
    "Tu sonrisa ilumina mi día más que el sol.",
    "Si la belleza fuera agua, tú serías el océano.",
    "Si tuviera que pedir un deseo, desearía estar contigo para siempre.",
    "Me gustas más que el chocolate.",
    "¿Eres Google? Porque tienes todo lo que busco.",
    "Eres la melodía que mi corazón no deja de tararear.",
    "Si fueses un delito, te aseguraría cadena perpetua en mi corazón.",
    "Contigo, cada momento es mágico.",
    "¿Puedo seguirte a casa? Es que mis padres siempre me dijeron que siguiera mis sueños.",
    "Eres el poema más bello que la vida ha escrito.",
    "No soy astronauta, pero contigo me siento en la luna.",
    "Tus labios deben saber a cielo.",
    "Mi color favorito es verte.",
    "Si me dieran una moneda cada vez que pienso en ti, sería millonario.",
    "Cuando te vi, supe que lo mejor de mi vida estaba por empezar.",
    "Eres la casualidad más bonita que llegó a mi vida.",
    "Cada latido de mi corazón dice tu nombre.",
    "Si las miradas mataran, ya estaría en el cielo.",
    "No soy poeta, pero inspiras los mejores versos en mí.",
    "Tienes algo que me hace olvidar todo lo demás.",
    "Deberían arrestarte por ser tan hermosa.",
    "Si me das una oportunidad, te prometo hacerte la persona más feliz.",
    "No me gusta el café, pero contigo me tomaría uno cada mañana.",
    "Si fueras una estrella, iluminarías todo mi universo.",
    "Quisiera ser el sol para iluminar tu día desde que despiertas.",
    "Tu sonrisa es la curva más hermosa que he visto.",
    "Cuando sonríes, el mundo se detiene.",
    "Eres la razón por la que creo en el amor.",
    "Nunca creí en el amor a primera vista, hasta que te vi.",
    "Si amarte fuera trabajo, nunca querría vacaciones.",
    "No sé qué tienes, pero me tienes loco.",
    "Eres el mejor error que jamás cometería.",
    "Me gustas más que dormir hasta tarde.",
    "Si la dulzura tuviera un nombre, se llamaría como tú.",
    "Eres mi persona favorita en este planeta.",
    "Si el amor tuviera rostro, seguro que sería el tuyo.",
    "No sé qué me pasa, pero cada vez que te veo, sonrío sin querer.",
    "Si te miro más tiempo, tendré que cobrar entrada.",
    "Tus abrazos deberían ser patrimonio de la humanidad.",
    "Eres mi mejor coincidencia.",
    "Si fueras un perfume, te llamaría felicidad.",
    "Quisiera escribir tu nombre en el cielo para que el mundo sepa cuánto te quiero.",
    "Contigo, cada instante se vuelve eterno.",
    "Si fueras un planeta, serías el más hermoso del universo.",
    "Cada día contigo es un regalo.",
    "Si mi vida fuera un rompecabezas, tú serías la pieza que me faltaba.",
    "Eres el suspiro que nunca quiero dejar de sentir.",
    "Solo con verte, mi día mejora.",
    "Si fueras un hechizo, seguro que serías amor eterno.",
    "Tu risa es la música más dulce para mis oídos.",
    "Me encantaría ser el motivo de tu felicidad.",
    "Eres el secreto que nunca quiero compartir.",
    "Si la felicidad tuviera nombre, se llamaría como tú.",
    "Tus besos deberían ser ilegales, porque son demasiado adictivos.",
    "¿Eres un ángel? Porque cada vez que te veo, siento que estoy en el cielo.",
    "No me des chocolate, dame un beso tuyo y me harás más feliz.",
    "Si mi corazón hablara, diría tu nombre en cada latido.",
    "Eres el mejor capítulo de mi vida.",
    "Si fueras un cuento, serías mi favorito.",
    "Quiero ser la razón detrás de tu sonrisa.",
    "Eres el mejor sueño que he tenido.",
    "Cuando me miras, el mundo desaparece.",
    "Me haces creer en la magia del amor.",
    "Si amarte fuera un deporte, ganaría todas las medallas.",
    "Eres el anhelo de mi corazón.",
    "No sé si fue el destino, pero me encanta que nos haya juntado.",
    "Si fueras una canción, te escucharía en repeat todo el día.",
    "Me encanta cómo iluminas mi mundo con solo existir.",
    "Si pudiera, atraparía cada estrella del cielo para hacerte un collar.",
    "Eres el arcoíris después de mi tormenta.",
    "Quiero perderme en tu abrazo y nunca encontrar el camino de vuelta.",
    "Eres la razón por la que sonrío sin motivo.",
    "Cada vez que te veo, mi corazón baila de felicidad.",
    "Eres lo mejor que me ha pasado en la vida.",
    "Si me das la oportunidad, te demostraré que vales todo para mí.",
    "No me canso de mirarte, eres un arte vivo.",
    "Eres mi historia favorita que nunca quiero dejar de leer.",
    "Si fueras un color, serías el más hermoso de todos.",
    "Cuando estoy contigo, el tiempo se detiene.",
    "Eres el mejor capítulo de mi vida y quiero seguir escribiéndolo contigo." 
]

advance = [
    "Si fueras un libro, serías mi capítulo favorito que leo una y otra vez.",
    "Cada vez que te veo, mi corazón compone una sinfonía solo para ti.",
    "Eres como una obra de arte, cuanto más te observo, más me enamoro.",
    "Si mi amor por ti fuera una ecuación, sería una sin solución porque es infinito.",
    "Cada palabra que dices es como poesía para mis oídos.",
    "Si el destino nos unió, es porque sabía que sin ti mi historia estaría incompleta.",
    "Eres la brújula que guía cada paso de mi vida hacia la felicidad.",
    "Si mi corazón fuera una ciudad, cada calle llevaría tu nombre.",
    "Me has hechizado con tu esencia y no quiero el antídoto.",
    "Eres mi definición de perfección en un mundo de imperfecciones.",
    "Cada latido de mi corazón suena como un eco de tu nombre.",
    "Si fueras un secreto, serías el único que nunca querría revelar.",
    "No eres un sueño, pero cada momento contigo es pura fantasía.",
    "Si pudieras ver mi alma, encontrarías tu reflejo en ella.",
    "No necesito brújula, porque mi norte siempre apunta hacia ti.",
    "Tu voz es la melodía que mi alma necesita para sentirse en paz.",
    "Eres la tinta con la que mi destino está escrito.",
    "Si mis pensamientos fueran estrellas, tú serías la constelación más brillante.",
    "No quiero un final feliz, quiero una eternidad contigo.",
    "Cada palabra tuya es un hechizo que me mantiene cautivado.",
    "Si mi amor por ti fuera una pintura, cada pincelada estaría hecha de emoción pura.",
    "Eres la sinfonía que da armonía a mi mundo.",
    "No necesito diamantes ni oro, porque tu presencia ya lo vale todo.",
    "Si fueras una ola, dejaría que me arrastraras una y otra vez.",
    "Eres la estrella fugaz que iluminó mi noche eterna.",
    "Si fueras un suspiro, sería el que nunca querría dejar escapar.",
    "Cuando me hablas, el tiempo pierde su significado.",
    "Si el amor tuviera rostro, sería el tuyo reflejado en mis ojos.",
    "Tu risa es el eco más dulce que mis oídos han escuchado.",
    "Si el arte pudiera respirar, tomaría tu forma.",
    "Eres el rompecabezas perfecto que encaja en cada rincón de mi ser.",
    "Tus abrazos son el refugio donde mi alma encuentra paz.",
    "Si la luna tiene un lado oculto, tú eres la luz que lo descubre.",
    "Cada segundo sin ti es un siglo de espera.",
    "Eres el paraíso que jamás quisiera abandonar.",
    "Si la eternidad tuviera un comienzo, sería el día en que te conocí.",
    "No hay idioma suficiente para describir lo que siento por ti.",
    "Si mi corazón fuera un poema, cada verso llevaría tu esencia.",
    "Cada latido que tengo es una carta de amor dedicada a ti.",
    "Eres la metáfora más hermosa que la vida me ha regalado.",
    "Si el universo tiene un centro, debe estar en la profundidad de tu mirada.",
    "Eres el equilibrio perfecto entre locura y amor.",
    "Si fueras un viento, serías la brisa que acaricia mi alma.",
    "No hay reloj que pueda medir el tiempo que quiero pasar contigo.",
    "Eres la melodía que mi corazón no deja de repetir.",
    "Si la felicidad tuviera un aroma, olería a ti.",
    "Cada segundo sin ti es como una sinfonía sin notas.",
    "Eres la luz que transforma mi oscuridad en poesía.",
    "Si la eternidad pudiera sentirse, sería cada instante a tu lado.",
    "Eres la constelación que adorna mis noches de insomnio.",
    "Si fueras una historia, serías mi favorita para siempre.",
    "Eres el enigma que nunca quiero resolver.",
    "Si el amor tuviera nombre, se llamaría como tú.",
    "Eres la única verdad en la que siempre quiero creer.",
    "Si mis sueños pudieran hablar, gritarían tu nombre.",
    "Eres el verso que falta en mi poema inacabado.",
    "Si el destino escribiera en el cielo, nuestras almas serían las estrellas más brillantes.",
    "Eres la respuesta a cada pregunta que mi corazón ha hecho.",
    "Si fueras un fuego, serías el que nunca quiero apagar.",
    "Eres la nota que falta en mi canción de amor.",
    "Si la perfección existe, seguro que lleva tu nombre.",
    "Eres el puente entre mis sueños y la realidad.",
    "Si mis pensamientos fueran pétalos, formarían un jardín con tu esencia.",
    "Eres la magia que transforma mis días comunes en extraordinarios.",
    "Si la belleza tuviera forma, tomaría la tuya.",
    "Eres el verso más hermoso del poema de mi vida.",
    "Si pudiera capturar la felicidad, la guardaría en un frasco con tu nombre.",
    "Eres el refugio donde mi alma encuentra calma.",
    "Si fueras un destino, sería el único lugar al que quisiera llegar.",
    "Eres la brújula que siempre me señala hacia el amor.",
    "Si el amor fuera un río, en ti encontraría su cauce.",
    "Eres la luna que ilumina mis noches más oscuras.",
    "Si cada latido pudiera hablar, el mío solo diría tu nombre.",
    "Eres la melodía que mi alma ha estado buscando.",
    "Si el amor tuviera un color, se reflejaría en tus ojos.",
    "Eres la inspiración de cada uno de mis pensamientos.",
    "Si la felicidad tuviera dueño, sería quien tiene tu corazón.",
    "Eres el susurro del viento que acaricia mis sueños.",
    "Si la eternidad existe, es porque tú formas parte de ella.",
    "Eres la chispa que enciende cada uno de mis días.",
    "Si la pasión pudiera definirse, lo haría con tu nombre.",
    "Eres la razón por la que el tiempo no tiene sentido cuando estoy contigo.",
    "Si la vida me diera un solo deseo, pediría que nunca te alejaras.",
    "Eres la canción que nunca quiero dejar de escuchar.",
    "Si el destino tiene planes, espero que siempre te incluyan a ti y a mí." 
]

es_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
