simple = [
    "Sa oled nagu päikesetõus – sa muudad kõik ilusamaks.",
    "Su naeratus on nagu maagia, see paneb mu südame kiiremini põksuma.",
    "Kas sa oled kunstiteos? Sest sa oled tõeline meistriteos!",
    "Kui ilu oleks kuritegu, oleksid sa eluaegne vang!",
    "Sinu silmad on nagu tähed – ma võiksin neisse igavesti vaadata.",
    "Ma kaotasin oma telefoni numbri… Kas ma saaksin sinu oma?",
    "Kas sa oled magnet? Sest ma tunnen, kuidas sa mind tõmbad.",
    "Kui sa oleksid unistus, siis ma ei tahaks kunagi ärgata.",
    "Sinu naer on nagu muusika mu kõrvadele.",
    "Sa oled nagu mõistatus, mida ma tahan igavesti lahendada.",
    "Ma ei usu armastusse esimesest silmapilgust, aga sina panid mind ümber mõtlema.",
    "Kas sul on kaart? Sest ma eksisin ära su silmadesse.",
    "Sa oled nagu kalliskivi – haruldane ja hindamatu.",
    "Kui ma saaksin soovi soovida, sooviksin ma veeta terve elu sinuga.",
    "Sa oled ilusam kui kõik maailma päikeseloojangud kokku.",
    "Ma võiksin sind vaadata terve igaviku ja see ei oleks raisatud aeg.",
    "Sa oled nagu raamat, mida ma tahan ikka ja jälle lugeda.",
    "Sinu hääl on nagu meloodia, mis ei lähe kunagi meelest.",
    "Kui ilu oleks ajalugu, oleksid sina terve ajastu.",
    "Kas ma võin sind õhtusöögile viia? Ma tahan sulle näidata, kui eriline sa oled!",
    "Sa oled nagu kohv – ma ei saa ilma sinuta päeva alustada.",
    "Kui ma peaksin kirjeldama sind ühe sõnaga, oleks see „täiuslik”.",
    "Kui ma oleksin meri, tahaksin ma olla su laine.",
    "Kas sa oled fotograaf? Sest sa jäädvustasid mu südame.",
    "Sa oled nagu luuletus – lummav ja unikaalne.",
    "Ma teadsin, et armastus on ilus, aga ma ei teadnud, et see võib olla nii ilus kui sina.",
    "Sa oled nagu täht langevas öös – haruldane ja soovitud.",
    "Kui ma võiksin olla ükskõik kus maailmas, siis ma tahaksin olla sinu kõrval.",
    "Sinu juuresolek paneb mu südame tantsima.",
    "Sa oled nagu kevad – tood mu ellu värskust ja ilu.",
    "Kui ma oleksin kunstnik, joonistaksin ma ainult sind.",
    "Kas sa oled teadlane? Sest sa tekitasid minus keemiat.",
    "Sa oled nagu kõige ilusam unenägu, millest ma ei taha ärgata.",
    "Kui sa oleksid lilleõis, oleksid sa kõige kaunim.",
    "Sinu naeratus on nagu päike, see valgustab mu päeva.",
    "Kas sa oled WiFi? Sest ma tunnen sinuga tugevat ühendust.",
    "Sa oled nagu kalliskivi, mida ma tahan igavesti hoida.",
    "Kui su süda oleks hotell, tahaksin ma sinna sisse registreeruda igaveseks.",
    "Sa oled nagu unistus, mis on saanud tõeks.",
    "Kui ilu oleks valuuta, oleksid sa miljardär.",
    "Ma arvasin, et ma olen õnnelik, aga siis kohtasin ma sind ja sain teada, mis on tõeline õnn.",
    "Sa oled nagu tulevärk – sa valgustad mu maailma.",
    "Kui armastus oleks kunst, oleksid sina mu meistriteos.",
    "Kas sa oled paradiisist? Sest sa oled liiga täiuslik, et olla siit maailmast.",
    "Kui mu süda saaks laulda, laulaks see ainult sinust.",
    "Sa oled nagu kõige ilusam meloodia, mida ma tahan kuulata igavesti.",
    "Ma ei vaja kompassi, sest su süda näitab mulle alati õiget suunda.",
    "Kui su silmad oleksid ookean, upuksin ma neisse rõõmuga.",
    "Sa oled nagu küünlavalgus pimedas toas – sa tood soojust ja valgust.",
    "Kas sa oled maag? Sest sa oled mind ära nõidunud.",
    "Kui ma võiksin soovida midagi, sooviksin ma veeta igaviku sinuga.",
    "Sinu puudutus on nagu pehme suvebriis.",
    "Sa oled nagu täht taevas – ma ei saa sinult silmi ära.",
    "Kui su süda oleks lukk, siis ma tahan olla võti.",
    "Sa oled nagu muinasjutt – ilus ja uskumatult võluv.",
    "Sa oled nagu suvine päikesepaiste – soojendad mu südant.",
    "Kas sa oled viiul? Sest sa mängid mu südamele kauneimat meloodiat.",
    "Sa oled nagu kunst – iga nurga alt kaunis.",
    "Kui sa naeratad, tundub maailm parem paik.",
    "Sinu häält kuuldes tunnen end kohe paremini.",
    "Sa oled nagu õrn tuuleiil, mis toob mu ellu värskust.",
    "Kui armastus oleks meri, oleksin ma sinusse uppunud.",
    "Sa oled nagu salajane aed, mida ma tahan avastada.",
    "Sinu silmad on nagu kaks kalliskivi, mis säravad kõige eredamalt.",
    "Sa oled nagu kõige magusam unenägu.",
    "Kui ma oleksin kirjanik, kirjutaksin ma ainult sinust.",
    "Sa oled nagu kõige kaunim luule.",
    "Kui armastus oleks mäng, tahaksin ma mängida seda ainult sinuga.",
    "Sa oled nagu kallihinnaline vein – muutud ainult paremaks.",
    "Sinu kõrval tundub kõik muu ebaoluline.",
    "Sa oled nagu kuu – valgustad isegi kõige pimedamat ööd.",
    "Kui mu süda oleks raamat, oleksid sa selle kauneim peatükk."
]

advance = [
    "Su silmad on nagu galaktikad – ma võiksin neisse eksida ja iialgi tagasi mitte tulla.",
    "Kui su naer oleks laul, kuulaksin ma seda kordusena igavesti.",
    "Sa oled kui kuldne niit minu saatuseraamatus.",
    "Kas sa oled alkeemik? Sest sa muudad kõik, mida puudutad, kullaks.",
    "Sinu puudutus on nagu elektrilaeng, mis paneb mind elama.",
    "Kui armastus oleks kunst, oleksid sa kõige täiuslikum meistriteos.",
    "Sa oled nagu matemaatiline võrrand – keeruline, aga väärt lahendamist.",
    "Kui su süda oleks muusika, mängiks see kõige ilusamat sümfooniat.",
    "Sa oled universumi kõige kaunim saladus.",
    "Kui armastus oleks teadus, siis oleksid sa selle kõige olulisem avastus.",
    "Kas sa oled unistus? Sest iga kord, kui sind näen, tunnen, et ma ei taha ärgata.",
    "Sinu süda lööb nagu kõige täpsem kell, kuid ainult siis, kui ma olen sinu lähedal.",
    "Sa oled nagu Shakespeare'i sonett – klassikaline, ajatu ja täiuslik.",
    "Kui ma saaksin aja peatada, jääksin ma igavesti sellesse hetke sinuga.",
    "Sa oled nagu kõige kaunim armastuslaul, mida maailm on kunagi kuulnud.",
    "Sinu silmad on nagu peegel, milles ma näen oma kõige õnnelikumat versiooni.",
    "Kui armastus oleks taevas, siis sina oleksid mu tähtede kaart.",
    "Sa oled nagu kõige haruldasem kalliskivi – ainulaadne ja hindamatu.",
    "Kui mu süda võiks kirjutada luuletusi, oleks iga sõna pühendatud sinule.",
    "Kas sa oled loodusjõud? Sest sa oled mind täielikult vallutanud.",
    "Kui sa oleksid sõna, siis oleksid sa kõige ilusam sõna minu sõnavaras.",
    "Sinu hääl on nagu jazz – ajatu ja täis hingepuudutusi.",
    "Kui su naeratus oleks keel, tahaksin ma seda õppida rääkimiseks.",
    "Sa oled nagu kõige kaunim sümfoonia, mille noodid on kirjutatud armastusest.",
    "Kui sa oleksid reisisihtkoht, siis tahaksin ma sinna kolida igaveseks.",
    "Sinu silmad on nagu kõige sügavamad ookeanid – täis saladusi ja võlu.",
    "Kui sa oleksid mõistatus, siis oleksin ma õnnelik, et pean sind igavesti lahendama.",
    "Sa oled nagu öine taevas – täis imet ja sära.",
    "Kui ma oleksin teadlane, pühendaksin ma kogu oma elu, et uurida su ilu.",
    "Sa oled nagu universumi kõige säravam täht.",
    "Kui su naeratus oleks energiaallikas, võiks see toita terve maailma.",
    "Kas sa oled ajamasin? Sest iga kord, kui ma olen sinuga, tundub aeg peatunud.",
    "Sa oled nagu kõige kaunim sonett, mille Shakespeare unustas kirjutada.",
    "Kui ma saaksin su nime sosistada igal hommikul, oleks see minu jaoks täiuslik äratuskell.",
    "Sinu naer on nagu mahe tuul, mis kannab mind armastuse merre.",
    "Sa oled nagu salapärane raamat, mida ma tahan lugeda ikka ja jälle.",
    "Kui su puudutus oleks luuletus, oleks see kirjutatud tähtede valguses.",
    "Sa oled nagu kõige täiuslikum armastuslugu, mis kunagi loodud.",
    "Kui ma saaksin soovida midagi, sooviksin ma sinuga igavest õhtut tantsida.",
    "Sinu hing särab eredamalt kui ükski päike.",
    "Kas sa oled loovus? Sest sa inspireerid mind olema parem inimene.",
    "Kui ilu oleks teadus, siis sina oleksid selle kõige täpsem valem.",
    "Sa oled nagu kõige kaunim unenägu, mida ma ei taha iial unustada.",
    "Kui ma võiksin maalida, jäädvustaksin su naeratuse kõige säravamates värvides.",
    "Sinu pilk on nagu magnet, mis tõmbab mind lähemale iga kord, kui sind vaatan.",
    "Sa oled nagu kõige kallihinnalisem kunstiteos Louvre’is – hinnaline ja ainulaadne.",
    "Kui armastus oleks linn, siis sina oleksid selle südames." 
]

et_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
