simple = [
    "Oletko taikuri? Koska aina kun katson sinua, kaikki muu katoaa.",
    "Tiedätkö, mikä näyttäisi hyvältä päälläsi? Minä.",
    "Oletko kartta? Koska eksyin silmiisi.",
    "Sattuiko, kun putosit taivaasta?",
    "Jos olisit hedelmä, olisit ehdottomasti hieno-meloni!",
    "Sinulla täytyy olla kamera sydämessäsi, koska aina kun katson sinua, hymyilen.",
    "Oletko laina? Koska olet kiinnostukseni kohde!",
    "Voinko lainata suudelman? Lupaan palauttaa sen.",
    "Sinulla on jotain kauniimpaa kuin tähdet taivaalla – hymysi.",
    "Oletko Bluetooth? Koska tunnen todellista yhteyttä kanssasi.",
    "Onko nimesi Google? Koska sinulla on kaikki, mitä etsin.",
    "Oletko kahvi? Koska en voi aloittaa päivääni ilman sinua.",
    "Sinun täytyy olla taideteos, koska en voi lakata ihailemasta sinua.",
    "Oletko wifi? Koska tunnen vahvan yhteyden sinuun.",
    "Voinko seurata sinua kotiin? Koska vanhempani aina sanovat, että seuraa unelmiasi.",
    "Oletko aurinko? Koska tuot valoa päivääni.",
    "Sinun hymysi on kuin aamukahvi – se tekee päivästäni paremman.",
    "Oletko enkeli? Koska näytät siltä, että kuulut taivaaseen.",
    "Oletko tähti? Koska tuot valoa elämääni.",
    "Oletko kello? Koska pysäytit juuri aikani.",
    "Onko sinulla karttaa? Koska eksyin katseeseesi.",
    "Voinko saada suudelman? Lupaan palauttaa sen takaisin.",
    "Oletko magiaa? Koska lumouduit minut. ",
    "Sinun hymysi sulattaa sydämeni kuin aurinko jäävuoren.",
    "Oletko runo? Koska saat sydämeni soimaan. ",
    "Olet kuin hyvä kirja – en halua lopettaa sinua. ",
    "Sinulla on jotain erityistä… ja se on kaikki sinussa!",
    "Voinko viettää loppuelämäni kanssasi? Koska jo nämä sekunnit kanssasi tuntuvat parhailta. ",
    "Sinun täytyy olla keiju, koska toit taikaa elämääni.",
    "Onko sinulla kompassi? Koska eksyn hymyysi.",
    "Oletko taidemaalari? Koska maalaat maailman kauniiksi. ",
    "Sinun täytyy olla unelma, koska en halua herätä tästä hetkestä. ",
    "Sinun naurusi on kaunein musiikki, mitä olen kuullut.",
    "Oletko salama? Koska sytytit kipinän sydämeeni.",
    "Sinun läsnäolosi saa sydämeni lyömään nopeammin.",
    "Voinko ottaa valokuvan kanssasi? Haluan todistaa enkeleiden olemassaolon.",
    "Olet kuin täydellinen auringonlasku – en voi lakata tuijottamasta. ",
    "Sinun silmäsi kertovat enemmän kuin tuhat sanaa. ",
    "Oletko suudelma sateessa? Koska haluan kokea sen kanssasi. ",
    "Oletko keiju? Koska levität taikaa kaikkialle. ",
    "Sinä olet kuin tähti – kirkas ja ainutlaatuinen.",
    "Oletko tanssi? Koska kanssasi kaikki tuntuu kevyeltä ja kauniilta. ",
    "Hymysi on kuin ilotulitus – kaunis ja lumoava. ",
    "Sinä olet syy, miksi uskon kohtaloon. ",
    "Sinun täytyy olla suosikkikappaleeni, koska haluan kuunnella sinua yhä uudelleen. ",
    "Oletko kirja? Koska haluan lukea sinut kannesta kanteen. ",
    "Sinun äänesi on musiikkia korvilleni. ",
    "Olet kuin ensimmäinen kevätpäivä – lämmin ja täynnä iloa. ",
    "Oletko karkki? Koska olet makeampi kuin suklaa. ",
    "Sinun seurassasi aika pysähtyy. ",
    "Oletko sydämentykytys? Koska tunnet minut paremmin kuin kukaan muu. ",
    "Voinko pitää kädestäsi kiinni? En halua päästää irti. ",
    "Olet kaunein asia, mitä olen koskaan nähnyt. ",
    "Sinun hymysi on tärkein syy, miksi päiväni ovat valoisia. ",
    "Olet kuin tähtiöinen taivas – rauhallinen ja lumoava. ",
    "Oletko kevät? Koska tuot elämän kaikkeen ympärilläsi. ",
    "Sinun naurusi on kuin sateenkaari myrskyn jälkeen. ",
    "Oletko unelma? Koska en halua koskaan herätä. ",
    "Olet täydellinen juuri sellaisena kuin olet. ",
    "Sinä olet syy, miksi uskon rakkauteen. ",
    "Oletko aurinko? Koska ilman sinua maailma olisi kylmä. ",
    "Sinä olet kuin kaunein maalaus – täynnä värejä ja elämää. "
]

advance = [
    "Jos olisin runoilija, kirjoittaisin sonetin silmiesi kauneudesta.",
    "Sinä olet kuin aurinko aamutaivaalla – et voi olla huomaamatta sinua.",
    "Kun katson sinua, sydämeni lyö tahtia, jota en ennen tuntenut.",
    "Oletko loitsu? Koska en pysty irrottamaan ajatuksiani sinusta.",
    "Jos rakkaus olisi taidetta, sinä olisit mestariteos.",
    "Silmäsi ovat kuin syvä meri, ja joka kerta kun katson niihin, hukuttaudun uudelleen.",
    "Olet kuin kaunein sinfonia – jokainen hetki kanssasi on harmoniaa.",
    "En tarvitse tähtiä taivaalla, kun sinä valaiset elämäni.",
    "Sinun naurusi on kuin kaunis melodia, joka soi sydämessäni.",
    "Oletko salaisuus? Koska haluan käyttää loppuelämäni sinut selvittäen.",
    "Kun katsot minuun, unohdan hengittää hetkeksi.",
    "Jos suudelmat olisivat sanoja, kirjoittaisin sinulle romaanin.",
    "Olet kuin viini – vain paranet ajan myötä.",
    "Olet kuin ensimmäinen kevään kukka – herätät sydämeni eloon.",
    "Sinä olet se kappale, jota en koskaan halua lopettaa kuuntelemasta.",
    "Olet kuin tähtitaivas – loputtoman kaunis ja täynnä mysteereitä.",
    "Kaikki sanat maailmassa eivät riittäisi kuvaamaan tunteitani sinua kohtaan.",
    "Oletko tähtisumu? Koska en voi nähdä muuta kuin sinut.",
    "Kun olet lähellä, koko maailma tuntuu kirkkaammalta.",
    "Jokainen hetki kanssasi tuntuu ajan pysähtymiseltä.",
    "Oletko kohtalo? Koska en voi uskoa, että tapaamisemme oli sattumaa.",
    "Jokainen päivä kanssasi on kuin kaunis runo.",
    "Sinun hymysi saa minut tuntemaan, että kaikki on mahdollista.",
    "Oletko mysteeri? Koska haluan käyttää elämäni sinut selvittäen.",
    "Oletko tähti? Koska tuot valoa pimeimpäänkin hetkeen.",
    "Jos elämäni olisi kirja, sinä olisit sen kaunein luku.",
    "Sinun lähelläsi olemisesta on tullut minun lempipaikkani maailmassa.",
    "Oletko tuuli? Koska saat sydämeni väreilemään pelkällä olemassaolollasi.",
    "Sinun kanssasi vietetty aika ei koskaan tunnu riittävältä.",
    "Jos voisin jäädyttää hetken, se olisi jokainen hetki kanssasi.",
    "Oletko revontulet? Koska olet kaunein näky, jonka olen koskaan nähnyt.",
    "Sinun äänesi on kuin lempeä melodia, joka rauhoittaa sydämeni.",
    "Olet kuin harvinainen jalokivi – ainutlaatuinen ja korvaamaton.",
    "En tarvitse karttaa, koska tiedän, että sydämeni vie minut aina luoksesi.",
    "Sinun katseesi on kuin magneetti, joka vetää minut puoleensa.",
    "Oletko aurinkoinen aamu? Koska joka kerta kun näen sinut, päiväni alkaa täydellisesti.",
    "Sinun hymysi tekee maailmasta paremman paikan.",
    "Kun hymyilet, sydämeni alkaa tanssia.",
    "Jos voisin toivoa yhtä asiaa, toivoisin lisää aikaa kanssasi.",
    "Sinun kosketuksesi jättää jäljen sydämeeni.",
    "Oletko iltarusko? Koska kanssasi kaikki tuntuu taianomaiselta.",
    "Kun olet lähellä, koko maailmani on täydellinen.",
    "Jos elämä olisi maalaus, sinä olisit sen kirkkain väri.",
    "Sinun äänesi saa sydämeni laulamaan.",
    "Oletko taianomainen satu? Koska kanssasi elämä tuntuu unelmalta.",
    "Oletko peili? Koska kun katson sinuun, näen parhaan version itsestäni.",
    "Sinun hymysi on kaunein taideteos, jonka olen koskaan nähnyt.",
    "Oletko muisto? Koska en voi lopettaa ajattelemasta sinua.",
    "Sinun rakkautesi on kuin lämpöinen viltti kylmänä päivänä.",
    "Oletko haave? Koska et voi olla todellinen.",
    "Olet täydellinen yhdistelmä kauneutta ja älykkyyttä.",
    "Sinun silmissäsi on universumi täynnä ihmeitä.",
    "Olet kuin kaunis melodia, joka soi mielessäni taukoamatta.",
    "Sinun naurusi on kuin makein sävel musiikissa.",
    "Oletko auringonlasku? Koska en halua, että tämä hetki päättyy.",
    "Olet elämäni kaunein yllätys.",
    "Oletko seikkailu? Koska haluan viettää loppuelämäni kanssasi tutkien maailmaa.",
    "Olet kuin kirkas tähti yössä, valaiseva ja ihmeellinen.",
    "Sinun kanssasi jokainen päivä on kuin satukirjan luku.",
    "Oletko kohtalo? Koska tuntuu siltä, että kuulut elämääni.",
    "Sinun kosketuksesi on kuin sähkövirta, joka herättää minut eloon.",
    "Olet kuin taianomainen loitsu, joka tekee elämästäni satumaisen.",
    "Sinun hymysi on kuin lupa paremmasta huomisesta.",
    "Olet kuin syksyn ensimmäinen lehti – ainutlaatuinen ja täynnä kauneutta.",
    "Oletko salaperäinen runo? Koska jokainen sanasi lumoaa minut.",
    "Sinä olet tarina, jonka haluan lukea yhä uudelleen.",
    "Kun pidän kädestäsi kiinni, tunnen olevani kotona.",
    "Oletko uni? Koska en halua koskaan herätä tästä tunteesta.",
    "Sinun hymysi on avain, joka avaa sydämeni oven.",
    "Olet elämäni kaunein kappale.",
    "Sinun rakkautesi on kuin liekki, joka lämmittää sydämeni.",
    "Oletko tähdenlento? Koska joka kerta kun näen sinut, toivon jotain kaunista."
]

fi_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
