simple = [
    "Es-tu un magicien ? Parce que chaque fois que je te regarde, tout disparaît autour de moi.",
    "Si la beauté était un crime, tu serais déjà en prison.",
    "Ton père est un voleur ? Parce qu'il a volé toutes les étoiles pour les mettre dans tes yeux.",
    "Tu dois être fatiguée, car tu as couru dans mon esprit toute la journée.",
    "Ton sourire est la seule lumière dont j’ai besoin dans ma vie.",
    "Si j'étais un chat, je passerais mes neuf vies avec toi.",
    "Es-tu une caméra ? Parce que chaque fois que je te regarde, je souris.",
    "Tu as un nom ou puis-je t’appeler mienne ?",
    "Si tu étais un légume, tu serais une ‘courge mignonne’.",
    "Je ne suis pas photographe, mais je peux nous imaginer ensemble.",
    "Si j'avais un euro à chaque fois que je pense à toi, je serais millionnaire.",
    "Je ne suis pas mathématicien, mais je pense que nous sommes faits l’un pour l’autre.",
    "Es-tu une étoile filante ? Parce que j’ai fait un vœu en te voyant.",
    "Si tu étais une chanson, tu serais mon tube préféré.",
    "Je voudrais être une larme pour naître dans tes yeux et mourir sur tes lèvres.",
    "Quand je regarde les étoiles, je me rends compte qu'elles ne brillent pas autant que toi.",
    "Je devrais porter des lunettes de soleil, car ton sourire brille trop fort.",
    "J’ai oublié mon numéro… Je peux avoir le tien ?",
    "Si être belle était un travail, tu serais PDG.",
    "Je ne suis pas un génie, mais je peux exaucer ton souhait d’être aimé.",
    "Si j'avais un bisou à chaque fois que je pense à toi, mes lèvres ne quitteraient jamais les tiennes.",
    "Es-tu une fée ? Parce que chaque fois que je te vois, tout devient magique.",
    "Je ne suis pas ivre, je suis juste enivré par ta beauté.",
    "Tu as volé mon cœur, puis-je avoir le tien en échange ?",
    "Je crois que j'ai perdu mon chemin… Peux-tu me guider jusqu'à ton cœur ?",
    "Si ton amour était un crime, je plaiderais coupable.",
    "On dit que l’amour fait mal, mais avec toi, je suis prêt à prendre le risque.",
    "Peux-tu sourire encore une fois ? Mon cœur a raté un battement.",
    "J’aimerais être une goutte d’eau pour glisser sur ta peau.",
    "Ton regard est comme un aimant, je ne peux pas m’en détacher.",
    "Si l’amour était une œuvre d’art, tu en serais le chef-d’œuvre.",
    "Si tu étais un parfum, tu serais mon essence préférée.",
    "Je ne crois pas au coup de foudre, mais tu viens de me prouver le contraire.",
    "J’aimerais être ton ombre pour te suivre partout.",
    "Tu illumines ma vie comme le soleil illumine la terre.",
    "Ton rire est la plus belle mélodie que j’ai jamais entendue.",
    "Peux-tu m'apprendre à voler ? Parce que chaque fois que je te vois, je me sens dans les nuages.",
    "Si l’amour était un voyage, j’aimerais le faire avec toi.",
    "Mon cœur a dessiné ton visage dans ses battements.",
    "J’aimerais être la mer pour caresser ton rivage.",
    "Si l’amour était un jeu, tu aurais déjà gagné mon cœur.",
    "J’ai demandé au destin de m’envoyer un ange, et il m’a envoyé toi.",
    "J’aimerais être une étoile pour veiller sur toi chaque nuit.",
    "J’aimerais être un livre que tu ne cesserais jamais de lire.",
    "Si les bisous étaient des flocons de neige, je t’offrirais une tempête.",
    "Tu es la seule énigme que je ne veux jamais résoudre.",
    "Es-tu une sirène ? Parce que tu m’as ensorcelé.",
    "Si l’amour avait un visage, ce serait le tien.",
    "Mon cœur s’emballe chaque fois que je te vois.",
    "Je ne veux pas te déranger, mais pourrais-tu me rendre mon cœur que tu as volé ?",
    "Quand je suis avec toi, le temps s’arrête.",
    "Ton amour est la seule chose qui manque à ma vie.",
    "Es-tu une étoile ? Parce que tu illumines ma nuit.",
    "Chaque moment avec toi est une poésie que je veux écrire.",
    "Si les roses sont rouges et les violettes bleues, alors mon cœur est à toi.",
    "Es-tu un rêve ? Parce que je ne veux jamais me réveiller.",
    "Ton amour est la plus belle aventure que je puisse vivre.",
    "Avec toi, chaque jour est un rayon de soleil.",
    "Es-tu un voleur ? Parce que tu as volé mon souffle.",
    "Si je pouvais réécrire l’alphabet, je mettrais U et I ensemble.",
    "J’aimerais être l’air que tu respires pour être toujours avec toi.",
    "Tu es la plus belle chose qui me soit jamais arrivée.",
    "Mon amour pour toi est comme l’univers : infini.",
    "J’ai vu une étoile filante, mais je n’ai pas fait de vœu, car je t’ai déjà toi.",
]

advance = [
    "Si l’univers était un poème, tu en serais la plus belle strophe.",
    "Chaque seconde sans toi est une éternité que je ne veux plus vivre.",
    "Ton regard est un labyrinthe dans lequel je veux me perdre pour toujours.",
    "Si l’amour était un chef-d'œuvre, alors tu serais ma plus grande inspiration.",
    "Même le soleil pâlit en comparaison de ton éclat.",
    "Ton sourire est une étoile qui illumine la galaxie de mon cœur.",
    "Je pourrais passer une vie entière à déchiffrer les mystères de ton âme.",
    "Si chaque battement de mon cœur pouvait murmurer ton nom, le monde entier t’entendrait.",
    "Tu es la réponse que mon âme cherchait sans le savoir.",
    "Si l’amour était une science, tu serais la découverte du siècle.",
    "Dans l’équation de ma vie, tu es la seule constante.",
    "Je veux être l’air que tu respires, pour être indispensable à ton existence.",
    "Ton amour est une mer dans laquelle je me noierais volontiers.",
    "Chaque fois que je te regarde, mon âme danse une valse infinie.",
    "Si mon cœur était une toile, tu serais l’artiste qui peint ses plus belles couleurs.",
    "Tu es la seule note qui manque à la mélodie de mon existence.",
    "Si aimer était un crime, je serais condamné à perpétuité avec toi.",
    "Ta voix est une mélodie qui berce mes nuits et enchante mes jours.",
    "Je pourrais lire dans tes yeux une bibliothèque entière d’émotions.",
    "Si l’amour était un livre, chaque page raconterait une histoire sur toi.",
    "Ton rire est la douce symphonie qui rythme mon bonheur.",
    "Je t’aime comme une rose aime la rosée du matin.",
    "Tu es le rêve dont je ne veux jamais me réveiller.",
    "Chaque moment avec toi est une perle précieuse sur le collier de ma vie.",
    "Ton amour est un feu qui brûle sans jamais s’éteindre.",
    "Si j’étais un poète, chaque mot que j’écrirais serait pour toi.",
    "Tu es la lumière qui chasse toutes mes ombres.",
    "Si la vie était une peinture, tu en serais le coup de pinceau le plus éclatant.",
    "Chaque battement de mon cœur est une déclaration silencieuse de mon amour pour toi.",
    "Si le bonheur avait un visage, ce serait le tien.",
    "Je t’aime au-delà des étoiles et des galaxies, jusqu’à l’infini.",
    "Chaque mot que je prononce est une prière adressée à ton amour.",
    "Je veux être le souffle qui caresse doucement ta peau.",
    "Ton amour est une énigme dont je veux passer ma vie à découvrir les secrets.",
    "Si les constellations formaient un mot, ce serait ton prénom.",
    "Ton regard est un poème silencieux que seul mon cœur peut comprendre.",
    "Si l’amour était une équation, tu serais la solution parfaite.",
    "Mon âme reconnaît en toi son éternité.",
    "Chaque frisson sur ma peau est un écho de ton absence.",
    "Si mon amour était un parfum, il embaumerait l’univers entier.",
    "Ton amour est un sort dont je ne veux jamais être libéré.",
    "Je t’aime comme un écrivain aime les mots qui donnent un sens à son existence.",
    "Chaque soupir que je pousse est une ode à ton amour.",
    "Si aimer était une danse, tu serais le rythme de mon cœur.",
    "Tu es le murmure du vent qui caresse mon âme en douceur.",
    "Si mon amour était une mer, il recouvrirait tous les continents.",
    "Tu es l’écho de chaque battement de mon cœur.",
    "Je t’aime comme un peintre aime sa plus belle œuvre.",
    "Chaque étoile dans le ciel est une pensée pour toi.",
    "Si mon amour était une chanson, elle ne connaîtrait jamais de fin.",
    "Ton amour est une lueur qui guide mon âme dans l’obscurité.",
    "Je pourrais me perdre dans les abysses de ton regard sans jamais chercher à en sortir.",
    "Si aimer était une quête, tu serais mon trésor ultime.",
    "Chaque battement de mon cœur crie ton nom en silence.",
    "Tu es la douce tempête qui fait chavirer mon âme.",
    "Si mon amour était une rivière, il coulerait éternellement vers toi.",
    "Ton amour est le plus beau poème que la vie m’ait offert.",
    "Si la passion avait une forme, elle prendrait la tienne.",
    "Je veux être l’écho de chaque mot d’amour que tu murmures.",
    "Ton amour est une éclipse qui occulte tout le reste.",
    "Chaque souffle que je prends est une déclaration d’amour pour toi.",
    "Si les mots pouvaient capturer la beauté, ils échoueraient devant toi.",
    "Ton amour est une étoile qui brille dans la nuit de mon existence.",
    "Chaque instant sans toi est une éternité de trop.",
    "Si l’amour était une symphonie, tu en serais la plus belle note.",
    "Tu es l’étincelle qui enflamme mon cœur.",
    "Ton amour est la poésie silencieuse qui habite mon âme.",
    "Chaque mot que tu prononces est un enchantement qui me captive.",
    "Si mon cœur était un livre, il n’aurait qu’un seul chapitre : Toi.",
    "Tu es la seule constellation qui guide mes nuits.",
    "Si mon amour pour toi était un feu, il brûlerait jusqu’à la fin des temps.",
    "Tu es la douce brise qui souffle sur mon âme.",
    "Si mon amour était une promesse, elle durerait une éternité.",
    "Je veux être l’encre qui écrit les plus belles pages de ton destin.",
    "Ton amour est un voyage dont je ne veux jamais revenir.",
    "Si le temps pouvait s’arrêter, je voudrais qu’il le fasse chaque fois que je suis avec toi.",
    "Chaque battement de mon cœur résonne en harmonie avec le tien.",
    "Si mon âme avait un foyer, ce serait dans ton cœur.",
    "Ton amour est la douce mélodie qui fait danser mon existence.",
    "Chaque étoile dans le ciel brille en hommage à ton amour.",
    "Si aimer était une peinture, tu serais la plus belle toile jamais créée.",
    "Tu es l’inspiration de chaque poème d’amour que mon cœur compose.",
    "Ton amour est la lumière qui éclaire mon chemin.",
]

fr_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
