simple = [
    "Jesi li čarobnjak? Jer svaki put kad te pogledam, nestane mi tlo pod nogama.",
    "Da si knjiga, bio bih tvoj najvjerniji čitatelj.",
    "Tvoje oči su poput oceana – izgubio sam se u njima.",
    "Jesu li tvoji roditelji pekari? Jer si ti najslađe pecivo koje sam ikad vidio!",
    "Ako bi ljepota bila zločin, ti bi bila doživotno zatvorena!",
    "Je li tvoj osmijeh legalan? Jer je nevjerojatno privlačan!",
    "Zar boli kad padneš s neba? Jer sigurno si anđeo!",
    "Da sam mađioničar, prva stvar koju bih učinio je da te natjeram da se zaljubiš u mene.",
    "Mogu li posuditi kartu? Jer sam se izgubio u tvojim očima.",
    "Nisam fotograf, ali mogu te zamisliti i u svojoj budućnosti!",
    "Da li tvoj otac radi u Starbucksu? Jer si ti pravo čudo!",
    "Znaš li karate? Jer me tvoj osmijeh oborio s nogu!",
    "Jesi li svjetionik? Jer mi pokazuješ put u tamnoj noći.",
    "Je li tvoj osmijeh zarazan? Jer me čini sretnim svaki put kad ga vidim!",
    "Jesi li anđeo? Jer svaki put kad si blizu, osjećam se kao u raju.",
    "Imam kartu za kino, ali bolje bi bilo da gledamo jedno drugo.",
    "Znaš li da si razlog zašto mi srce preskoči svaki put kad te vidim?",
    "Ako si san, ne želim se nikada probuditi.",
    "Je li bolno biti tako savršena?",
    "Mislim da moram prijaviti krađu… jer si ukrala moje srce!",
    "Jesi li vila? Jer svaki put kad te vidim, dogodi se nešto čarobno.",
    "Jesi li Google? Jer u tebi nalazim sve što tražim!",
    "Tvoje ime mora biti sunce, jer obasjavaš moj svijet.",
    "Kad bih imao zvijezdu za svaki put kad pomislim na tebe, imao bih vlastitu galaksiju!",
    "Nisam pjesnik, ali bih mogao napisati tisuće pjesama o tvojoj ljepoti.",
    "Jesi li čarobna? Jer svaki put kad si blizu, osjećam leptiriće u trbuhu!",
    "Mogu li te pratiti kući? Jer su me tvoje oči već odvele u raj.",
    "Ako bih mogao preurediti abecedu, stavio bih slovo ‘T’ i ‘I’ zajedno!",
    "Tvoje ime bi trebalo biti ‘San’, jer svaki put kad zatvorim oči, vidim te.",
    "Ako bi ljepota bila zvijezda, ti bi bila cijela galaksija!",
    "Imaš kartu? Jer sam se izgubio u tvom pogledu!",
    "Jesi li sirena? Jer si nevjerojatno očaravajuća!",
    "Ako si ljeto, onda ja nikad ne želim zimu!",
    "Mogu li te uslikati? Jer želim pokazati Djedu Mrazu što želim za Božić!",
    "Kad bi moj svijet imao kraljicu, bila bi to ti!",
    "Ne trebam svjetlo kad si ti ovdje, jer ti sijaš jače od sunca!",
    "Jesi li umjetničko djelo? Jer ne mogu prestati gledati!",
    "Znaš li da je moje srce poput violine? Samo ti znaš kako ga svirati!",
    "Ako bi ljepota bila valuta, ti bi bila najbogatija osoba na svijetu!",
    "Jesi li čokolada? Jer si nevjerojatno slatka!",
    "Mogu li dobiti tvoj autogram? Jer mislim da si prava zvijezda!",
    "Kad bih mogao birati između daha i tebe, rekao bih ti koliko te volim prije nego što prestanem disati!",
    "Je li tvoj osmijeh magija? Jer svaki put kad ga vidim, osjećam se začarano!",
    "Možeš li me zagrliti? Jer želim provjeriti jesu li anđeoska krila stvarna!",
    "Da si pjesma, bio bih tvoj najvjerniji slušatelj!",
    "Jesi li kompas? Jer uvijek me vodiš u pravom smjeru!",
    "Jesi li vila? Jer svaki trenutak s tobom je bajka!",
    "Ako bi mogla biti bilo što na svijetu, bio bih najsretniji čovjek ako bi bila moja!"
]

advance = [
    "Kad bi tvoje srce bilo knjiga, svaki list bi bio ispunjen ljubavlju.",
    "Jesi li enigma? Jer svaki put kad te pogledam, otkrivam novu tajnu.",
    "Volio bih biti ogledalo, da mogu gledati tvoju ljepotu svaki dan.",
    "Jesi li meteor? Jer svaki put kad prođeš pored mene, srce mi zatreperi.",
    "Da sam slikar, naslikao bih tvoje oči jer u njima vidim cijeli svijet.",
    "Mogu li biti kompas? Jer želim te voditi ravno u moje srce.",
    "Jesi li pjesma? Jer svaki tvoj osmijeh je melodija koju ne mogu zaboraviti.",
    "Da sam sat, svaki trenutak bih provodio brojeći sekunde do našeg ponovnog susreta.",
    "Nisi zvijezda na nebu, ali osvjetljavaš moj svijet poput najjačeg svjetionika.",
    "Kad bi postojala valuta ljepote, ti bi bila najbogatija osoba na svijetu.",
    "Jesi li vino? Jer s vremenom postaješ sve bolja i očaravajuća.",
    "Jesi li ljeto? Jer svaki trenutak s tobom osjeća se kao sunčan dan na plaži.",
    "Volio bih biti kiša, samo da te mogu dotaknuti i osjećati na svojoj koži.",
    "Ako si oluja, onda si ona koja nosi toplinu i strast, a ne hladnoću.",
    "Jesi li ruža? Jer tvoja ljepota i miris osvajaju moje srce.",
    "Tvoje ime bi trebalo biti magija, jer svaki put kad ga izgovorim, osjećam se očaran.",
    "Ako bi ljubav bila umjetnost, ti bi bila remek-djelo.",
    "Jesi li pjesnik? Jer svaki tvoj pogled piše stihove u mom srcu.",
    "Da sam astronom, ti bi bila moja omiljena zvijezda na nebu.",
    "Ako je ljubav vatra, onda si ti plamen koji ne želim ugasiti.",
    "Jesi li san? Jer svaki trenutak proveden s tobom je kao najljepša bajka.",
    "Tvoje oči su poput univerzuma, beskonačne i pune misterija koje želim istražiti.",
    "Jesi li cvijet? Jer svaki put kad te vidim, procvjetam od sreće.",
    "Ako su poljupci jezik ljubavi, možemo li pričati cijelu noć?",
    "Jesi li magnet? Jer svaki put kad sam blizu tebe, osjećam neodoljivu privlačnost.",
    "Tvoj glas je poput pjesme koju želim slušati cijeli život.",
    "Jesi li knjiga? Jer svaki put kad te pogledam, želim te iznova i iznova čitati.",
    "Tvoje srce je poput labirinta u kojem želim ostati zauvijek.",
    "Ako bih bio pjesnik, svaka pjesma koju bih napisao bila bi posvećena tebi.",
    "Jesi li plamen? Jer svaki put kad si blizu, osjećam vatru u svom srcu.",
    "Mogu li biti olovka? Jer želim pisati priču o nama.",
    "Jesi li dijamant? Jer tvoje srce je rijetko i dragocjeno.",
    "Kada bi poljupci bili valuta, bio bih milijarder samo od tebe.",
    "Jesi li komad neba? Jer uz tebe se osjećam kao da letim.",
    "Ako su tvoje usne otrov, spreman sam riskirati.",
    "Kad bih mogao, stavio bih tvoju sliku u zvijezde da svi vide tvoju ljepotu.",
    "Da sam slikarski kist, naslikao bih samo tvoju ljepotu.",
    "Ako je život knjiga, onda su stranice s tobom one koje želim zauvijek pamtiti.",
    "Jesi li rijeka? Jer svaki put kad te vidim, osjećam kako me nosiš sa sobom.",
    "Jesi li vjetar? Jer svaki tvoj dodir je poput laganog povjetarca na mom licu.",
    "Da postoji staza do tvog srca, već bih je odavno pronašao.",
    "Jesi li melodija? Jer tvoje riječi zvuče kao najljepša pjesma.",
    "Ako su oči ogledalo duše, onda tvoja duša sja poput sunca.",
    "Jesi li vještica? Jer si me začarala svojim osmijehom.",
    "Ako su tvoje usne vino, želim biti pijan od tvoje ljubavi.",
    "Jesi li galaksija? Jer si puni svemir ljepote i misterije.",
    "Tvoje srce kuca u ritmu koji želim plesati do kraja života.",
    "Ako je ljubav igra, onda želim da igramo zajedno zauvijek.",
    "Jesi li sudbina? Jer osjećam da smo stvoreni jedno za drugo.",
    "Kad bih mogao zamrznuti vrijeme, zauvijek bih ostao u ovom trenutku s tobom.",
    "Tvoj osmijeh je poput zrake sunca koja osvjetljava i najtamnije dane.",
    "Ako je ljubav magija, onda si ti čarolija koja mi je potrebna.",
    "Jesi li vila? Jer svaki trenutak s tobom osjeća se nadnaravno lijepim.",
    "Ako je ljubav ocean, onda sam ja spreman zaroniti najdublje zbog tebe.",
    "Jesi li moj kompas? Jer svaki put me vodiš prema ljubavi.",
    "Ako su zvijezde odraz ljepote, onda si ti cijelo nebo.",
    "Tvoje srce kuca u ritmu koji želim slušati do kraja života.",
    "Jesi li svjetionik? Jer mi pokazuješ put u mraku.",
    "Jesi li moje središte gravitacije? Jer se sve u mom svijetu okreće oko tebe."
]

hr_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
