simple = [
    "Gyönyörű mosolyod beragyogja a napomat.",
    "Olyan vagy nekem, mint a kávé reggelente – nélkülözhetetlen.",
    "Ha szépségverseny lenne, biztosan te nyernél.",
    "Megdobogtatod a szívemet minden egyes mosolyoddal.",
    "Nem tudok nem rád gondolni.",
    "A szemeidben elvesznék örökre.",
    "A nevetésed a legszebb dallam a füleimnek.",
    "Veled minden pillanat különleges.",
    "Te vagy a legédesebb dolog az életemben.",
    "El sem hiszem, hogy ilyen csodálatos emberrel beszélgethetek.",
    "A világ összes csillaga sem ragyog olyan fényesen, mint a szemed.",
    "Bárcsak én lehetnék az oka a mosolyodnak minden nap!",
    "Ha egy kívánságom lehetne, örökké melletted lennék.",
    "Ha a szépség bűn lenne, te életfogytiglant kapnál!",
    "Olyan vagy, mint egy álom, amit nem akarok feladni.",
    "A szívem gyorsabban ver, amikor rád gondolok.",
    "Te vagy a szivárvány az esős napjaimon.",
    "Kérlek, mosolyogj még egyszer, hadd legyen szebb a napom!",
    "Veled minden nap egy új kaland.",
    "Te vagy az én kedvenc meglepetésem az életben.",
    "Ha a csókok hópelyhek lennének, egy egész vihart küldenék neked!",
    "A világ legszebb tája a mosolyod.",
    "Nem vagyok költő, de amikor rád nézek, minden rímelni kezd.",
    "Megtanítanál szeretni téged?",
    "Kicsit elvesztem, segítenél megtalálni az utamat a szívedhez?",
    "Ha a boldogság egy személy lenne, az biztosan te lennél.",
    "A neved a kedvenc szavam.",
    "Kérek egy térképet, mert elvesztem a szemedben.",
    "Te vagy az én kedvenc gondolatom.",
    "A szerelem szó értelmet nyert, amikor megismertelek.",
    "El tudnám tölteni az egész életemet azzal, hogy csodáljalak.",
    "Olyan meleg a tekinteted, hogy elolvad a szívem.",
    "Ha minden gondolatom egy csillag lenne, az egész univerzum fénylene.",
]

advance = [
    "A jelenléted olyan, mint egy mágnes – mindig magadhoz vonzol.",
    "A szavaid olyanok, mint egy dallam, amit sosem unok meg hallgatni.",
    "Ha az életem egy könyv lenne, a kedvenc fejezeteim mind rólad szólnának.",
    "Olyan vagy nekem, mint egy csillag az éjszakai égbolton – mindig rád találok.",
    "Az érintésed olyan, mintha egy pillanatra megállna az idő.",
    "A mosolyod egy titkos nyelv, amit csak a szívem ért meg.",
    "Minden másodperc, amit nélküled töltök, olyan, mint egy eltékozolt pillanat.",
    "Ha a szerelem művészet lenne, te lennél az én mesterművem.",
    "A szemeid mélyebb történeteket mesélnek, mint bármelyik könyv, amit valaha olvastam.",
    "Ha a tekinteted egy festmény lenne, a világ minden múzeuma sorban állna érte.",
    "Nem tudok betelni veled – olyan vagy, mint egy addiktív dallam, amit újra és újra hallani akarok.",
    "A hangod megnyugtat, mint egy lágy dallam egy hosszú nap után.",
    "A bőröd illata egy emlékeztető, hogy az élet tele van varázslatos pillanatokkal.",
    "Ha választanom kellene egy helyet, ahol örökre maradnék, az a karjaid között lenne.",
    "A csókod olyan, mintha a világ összes édes ízét egyetlen érintésben érezném.",
    "Veled lenni olyan, mintha egy végtelen tavaszban élnék.",
    "Ha a szerelem egy utazás, akkor te vagy az úticélom.",
    "Néha csak csendben nézlek, mert a szavak nem elég erősek kifejezni, mit érzek irántad.",
    "A szívem mindig egy ütemmel gyorsabban ver, amikor a közeledben vagyok.",
    "A nevetésed olyan, mint egy dallam, amitől a világ szebb hely lesz.",
    "Amikor veled vagyok, az idő elveszíti az értelmét, és csak a pillanat marad.",
    "Te vagy az oka annak, hogy a szerelem számomra nem csak egy szó, hanem egy érzés.",
    "Minden nap egy új lehetőség arra, hogy beléd szeressek.",
    "Ha a szeretet egy bűvös erő, akkor te vagy a varázslatom forrása.",
    "Amikor a közeledben vagyok, minden más megszűnik létezni.",
    "A világ egyre szebb hely, mióta beléptél az életembe.",
    "Nem tudom, miért, de melletted minden egyszerűbbnek és boldogabbnak tűnik.",
    "Ha minden egyes csók egy szó lenne, akkor egy egész regényt írnék neked.",
    "A szereteted olyan, mint a tavaszi eső – élettel tölti meg a szívemet.",
    "Nélküled az életem csak egy fekete-fehér kép lenne.",
    "A mosolyod a napom fénypontja.",
    "Nem kell semmi más az élettől, csak hogy a közeledben lehessek.",
    "A tekintetedben több titkot fedezek fel, mint a világ összes könyvében.",
    "Te vagy a legjobb döntés, amit valaha hoztam.",
    "A veled töltött idő sosem elég, mindig többet akarok.",
    "Te vagy az a csoda, amit sosem hittem, hogy megtalálok.",
    "Ha egy dal lennél, egész nap ismétlésen hallgatnálak.",
    "A világ összes virága sem ér fel a szépségeddel.",
    "Olyan vagy nekem, mint a tengerparti szellő – frissítő és elbűvölő.",
    "Veled minden pillanat egy újabb emlék, amit a szívembe zárok.",
    "Minden egyes szavad a szívemet érinti.",
    "A csókod a legédesebb bűn, amit valaha elkövettem.",
    "Nem hiszek a sorsban, de ha létezik, biztosan hozzám vezetett téged.",
    "Ha az idő megállna, azt kívánnám, hogy veled töltsem az örökkévalóságot.",
    "Te vagy az egyetlen, aki bármikor képes mosolyt csalni az arcomra.",
    "A szívem mindig hazaér, amikor a közeledben vagyok.",
    "Bármit is csinálok, mindig visszatérek hozzád, mert te vagy az én világom középpontja.",
    "A szereteted olyan, mint egy puha takaró egy hideg téli estén.",
    "Az életem legszebb pillanatai mind hozzád kötődnek.",
    "A csókod a legjobb válasz minden kérdésemre.",
    "Ha minden csillag egy ok lenne, hogy szeretlek, az egész égboltot beborítaná a fényük.",
    "Te vagy a legcsodálatosabb meglepetés, amit az élet valaha adott nekem."
]

