simple = [
    "Kamu punya peta? Aku tersesat di matamu.",
    "Kamu seperti kopi, membuatku ketagihan.",
    "Kamu tahu apa yang lebih indah dari senja? Senyumanmu.",
    "Aku nggak butuh GPS, karena hatiku selalu menuju ke kamu.",
    "Kalau kamu bintang, aku ingin jadi langit yang selalu menaungimu.",
    "Kamu itu seperti wifi, karena aku selalu ingin terhubung denganmu.",
    "Kamu suka hujan? Karena aku ingin jadi payung yang selalu melindungimu.",
    "Aku seperti kamera, setiap saat selalu ingin menangkap senyumanmu.",
    "Kamu tahu? Setiap kali kamu tersenyum, hatiku meleleh seperti es krim.",
    "Jika mencintaimu adalah kesalahan, maka aku tak ingin menjadi benar.",
    "Aku seperti pelangi, muncul setelah kamu membuat hariku cerah.",
    "Aku bukan fotografer, tapi aku bisa membingkai hatimu selamanya.",
    "Kamu suka matematika? Karena setiap kali aku melihatmu, hatiku tambah bahagia.",
    "Aku tidak pandai merangkai kata, tapi hatiku selalu berbicara tentangmu.",
    "Kalau kamu jadi lagu, pasti kamu adalah nada paling indah.",
    "Aku nggak perlu kompas, karena hatiku selalu menunjuk ke arahmu.",
    "Kamu seperti bulan, selalu menyinari malam-malamku.",
    "Aku seperti lilin, selalu mencair setiap kali melihatmu.",
    "Setiap kali aku melihatmu, jantungku berdetak lebih cepat dari biasanya.",
    "Aku ingin jadi alasan di balik senyummu setiap hari.",
    "Kamu seperti teka-teki, aku selalu ingin mencari tahu lebih banyak tentangmu.",
    "Kalau kamu jadi bunga, pasti kamu adalah mawar yang paling indah.",
    "Aku ingin jadi matahari yang selalu menyinari harimu.",
    "Sejak mengenalmu, aku merasa hidupku lebih berwarna.",
    "Kamu tahu? Hatiku selalu bergetar setiap kali mendengar suaramu.",
    "Aku bukan pilot, tapi aku ingin terbang bersamamu menuju masa depan.",
    "Aku ingin jadi buku favoritmu, agar kamu selalu ingin membacaku.",
    "Kamu seperti lagu yang selalu terputar di pikiranku.",
    "Kamu tahu kenapa aku selalu tersenyum? Karena aku memikirkanmu.",
    "Aku ingin jadi cermin, agar aku bisa melihatmu setiap hari.",
    "Kamu seperti cuaca yang selalu membuatku merasa nyaman.",
    "Jika cinta adalah permainan, aku ingin bermain hanya denganmu.",
    "Kamu seperti es krim di hari panas, selalu menyegarkan hatiku.",
    "Kalau aku jadi bintang, aku ingin selalu menemani malammu.",
    "Kamu seperti mimpi indah yang tidak ingin aku bangun darinya.",
    "Aku ingin jadi catatan favoritmu, agar kamu selalu membacaku.",
    "Setiap detik bersamamu adalah hadiah paling berharga.",
    "Kamu seperti udara, aku tidak bisa hidup tanpamu.",
    "Kalau aku punya satu permintaan, aku ingin bersamamu selamanya.",
    "Kamu seperti novel yang tidak pernah ingin aku tamatkan.",
    "Aku ingin jadi bantal favoritmu, agar aku selalu ada di sisimu.",
    "Kalau kamu jadi musim, kamu pasti musim semi yang selalu membawa keindahan.",
    "Aku ingin jadi warna di dalam lukisan hidupmu.",
    "Kamu seperti api unggun di malam dingin, selalu menghangatkanku.",
    "Aku ingin jadi puisi yang selalu kamu baca di malam sepi.",
    "Kalau cinta adalah perjalanan, aku ingin menjelajah dunia bersamamu.",
    "Kamu seperti magnet, selalu menarik hatiku ke arahmu.",
    "Aku ingin jadi sayapmu, agar aku bisa selalu mendukungmu terbang tinggi.",
    "Setiap kali aku melihatmu, aku merasa dunia ini lebih indah.",
    "Kamu seperti gula dalam kopi hidupku, membuat semuanya lebih manis.",
    "Aku ingin jadi jam tanganmu, agar aku selalu ada di dekatmu.",
    "Kamu seperti lilin di tengah kegelapan, menerangi hidupku.",
    "Kalau kamu jadi puzzle, kamu adalah bagian yang selalu aku cari.",
    "Aku ingin jadi lagu yang selalu menemani harimu.",
    "Kamu seperti sinar matahari di pagi hari, menyegarkan dan menghangatkanku.",
    "Aku ingin jadi nafasmu, agar aku selalu ada bersamamu.",
    "Kamu tahu? Senyummu adalah sumber kebahagiaanku.",
    "Aku ingin jadi selimut yang selalu melindungimu dari dinginnya dunia.",
    "Kalau aku bisa memilih di mana aku berada, aku ingin selalu ada di hatimu.",
    "Kamu seperti taman yang penuh dengan bunga-bunga cinta.",
    "Aku ingin jadi pena yang selalu menuliskan kisah kita berdua.",
    "Kamu seperti angin sepoi-sepoi yang selalu menenangkan hatiku.",
    "Aku ingin jadi hujan yang selalu membasahi rindumu padaku.",
    "Kamu seperti fajar yang selalu memberi harapan baru.",
    "Kalau aku jadi ombak, aku ingin selalu menyentuh pantai hatimu.",
    "Aku ingin jadi bulan yang selalu menemani malammu.",
    "Kamu seperti permata yang tak ternilai harganya.",
    "Aku ingin jadi detik di jam tanganmu, agar aku bisa selalu bersamamu.",
    "Kalau aku jadi angin, aku ingin selalu membelai lembut wajahmu.",
    "Kamu seperti senyum yang selalu membuat hariku lebih baik.",
    "Aku ingin jadi cerita yang selalu kamu ceritakan kepada dunia.",
    "Kamu seperti cahaya dalam kegelapan hatiku.",
    "Aku ingin jadi lagu yang selalu mengiringi langkahmu.",
    "Kamu seperti malam berbintang, penuh dengan keindahan.",
    "Aku ingin jadi embun pagi yang selalu menyegarkan harimu.",
    "Kalau aku jadi kanvas, aku ingin selalu dipenuhi warna cintamu.",
    "Aku ingin jadi kata 'kita' dalam cerita hidupmu.",
    "Kamu seperti bunga di taman, selalu menarik perhatianku.",
    "Aku ingin jadi pelangi setelah hujan di hidupmu.",
    "Kamu seperti lilin yang menerangi hatiku di saat gelap.",
    "Aku ingin jadi melodi dalam setiap lagumu.",
    "Kalau aku jadi tinta, aku ingin menuliskan cerita indah tentang kita.",
    "Kamu seperti kedipan bintang yang selalu membuatku terpana.",
    "Aku ingin jadi bayangan yang selalu mengikuti langkahmu.",
    "Kamu seperti detik yang selalu berarti dalam hidupku.",
    "Aku ingin jadi alasan di balik kebahagiaanmu.",
    "Kamu seperti cahaya yang menerangi hari-hariku.",
]

advance = [
    "Kamu seperti puisi tanpa kata, hanya bisa kurasakan tanpa perlu diucapkan.",
    "Aku ingin jadi malam yang selalu mendekapmu dalam keheningan penuh makna.",
    "Kau adalah simfoni yang dimainkan hatiku setiap detik tanpa henti.",
    "Aku ingin menjadi udara yang kau hirup, agar selalu ada dalam hidupmu.",
    "Ketika dunia terasa sunyi, hadirmu adalah melodi yang menghidupkanku kembali.",
    "Cintaku padamu seperti gravitasi, tak terlihat tapi selalu menarikmu ke arahku.",
    "Aku bukan penyair, tapi namamu adalah puisi yang selalu ingin kutuliskan.",
    "Setiap langkahku selalu mengarah kepadamu, seakan hatiku memiliki peta ke cintamu.",
    "Jika aku adalah hujan, maka aku ingin jatuh sebagai rintik-rintik rindu di hatimu.",
    "Kamu seperti senja yang keindahannya tak akan pernah pudar dalam ingatanku.",
    "Aku ingin menjadi detik di jam tanganmu, agar aku selalu bersamamu setiap waktu.",
    "Kamu seperti matahari, karena sinarmu selalu menghangatkan hatiku.",
    "Seandainya aku jadi pelukis, aku akan mengabadikan keindahanmu di setiap kanvasku.",
    "Aku ingin jadi embun pagi yang menyegarkan harimu dengan sentuhan lembut.",
    "Kamu seperti buku favoritku, semakin kubaca semakin aku jatuh cinta.",
    "Jika aku memiliki satu permintaan, aku ingin memiliki senyummu setiap hari.",
    "Kamu adalah alasan kenapa malamku penuh dengan mimpi indah.",
    "Aku ingin jadi bantal kesayanganmu, agar aku bisa menemanimu di setiap tidurmu.",
    "Kamu seperti melodi indah yang terus terngiang dalam pikiranku.",
    "Aku ingin jadi bayanganmu, agar aku bisa selalu mengikutimu kemanapun kamu pergi.",
    "Hatiku seperti labirin, dan kamu adalah satu-satunya jalan keluar.",
    "Kamu seperti magnet, karena aku selalu tertarik kepadamu.",
    "Aku ingin menjadi hujan di hatimu, menyejukkan dan menyegarkan setiap harimu.",
    "Kamu adalah rahasia terindah yang ingin selalu kusimpan di dalam hatiku.",
    "Jika kamu adalah bintang, aku ingin menjadi langit yang selalu menaungimu.",
    "Aku ingin menjadi alasan di balik setiap senyummu.",
    "Seandainya aku bisa menghitung berapa banyak aku memikirkanmu, mungkin semesta tak cukup luas.",
    "Aku ingin jadi doa yang selalu kau ucapkan setiap malam.",
    "Jika hidup adalah perjalanan, aku ingin menjelajah dunia bersamamu.",
    "Kamu seperti udara, aku tak bisa hidup tanpamu.",
    "Aku ingin jadi sajak yang selalu kau baca di setiap malam sunyimu.",
    "Kalau kamu jadi mimpi, aku tak ingin pernah terbangun.",
    "Aku ingin jadi parfum favoritmu, agar aku selalu ada di dekatmu.",
    "Setiap detik yang kulewati tanpamu terasa hampa.",
    "Kamu seperti gula dalam teh, selalu membuat hariku lebih manis.",
    "Aku ingin jadi pelangi setelah hujan di hidupmu.",
    "Cintaku padamu seperti ombak yang tak pernah lelah menyentuh pantai.",
    "Aku ingin menjadi lagu yang selalu kau dengar saat merindukanku.",
    "Kamu adalah cahaya yang menerangi setiap gelap dalam hidupku.",
    "Aku ingin menjadi tinta yang menuliskan kisah indah kita berdua.",
    "Setiap kali kamu tersenyum, dunia terasa lebih indah bagiku.",
    "Aku ingin menjadi malam yang selalu menemani kesunyianmu.",
    "Seandainya aku bisa membaca pikiranmu, pasti aku akan menemukan namaku di sana.",
    "Kamu seperti angin, tak terlihat tapi selalu bisa kurasakan kehadiranmu.",
    "Jika cinta adalah seni, maka hatimu adalah mahakarya terindah.",
    "Aku ingin menjadi kata yang selalu kamu ucapkan dengan penuh cinta.",
    "Kamu seperti misteri yang ingin selalu kupecahkan.",
    "Aku ingin jadi halaman terakhir dalam bukumu, agar aku selalu jadi akhir yang indah bagimu.",
    "Cintaku padamu seperti bintang, meski jauh tapi selalu bersinar.",
    "Aku ingin menjadi tawa yang selalu menghiasi harimu.",
    "Jika waktu bisa dihentikan, aku ingin berhenti di saat bersamamu.",
    "Aku ingin jadi lagu yang selalu membuatmu tenang.",
    "Kamu seperti puzle, aku selalu ingin melengkapimu.",
    "Aku ingin menjadi warna dalam lukisan hidupmu.",
    "Setiap kali aku melihatmu, dunia terasa lebih hidup.",
    "Aku ingin menjadi hujan yang selalu membasahi rindumu.",
    "Kamu adalah alasanku percaya pada keajaiban cinta.",
    "Jika aku bisa memilih di mana aku berada, aku ingin selalu ada di hatimu.",
]

id_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
