simple = [
    "Ar tavo vardas Google? Nes turi viską, ko ieškau.",
    "Ar tiki meile iš pirmo žvilgsnio, ar turėčiau vėl praeiti pro tave?",
    "Tu esi toks karštas, kad net mano ledai išsilydytų.",
    "Jei būtum vaisius, būtum tobula braškė.",
    "Ar galėčiau pamatyti tavo nuotrauką? Noriu Kalėdų seneliui parodėti, ko noriu dovanų.",
    "Ar galiu tave pabučiuoti, ar turėsiu meluoti savo dienoraštyje?",
    "Ar turi žemėlapį? Nes pasiklydau tavo akyse.",
    "Tu mane hipnotizuoji savo šypsena.",
    "Net jeigu būčiau aklas, vis tiek atpažinčiau tave iš tavo kvapo.",
    "Jei turėčiau rašyti apie tave knygą, tai būtų meilės romanas.",
    "Ar tu magnetas? Nes mane traukia prie tavęs.",
    "Tavo akys - mano svajonių jūra.",
    "Kai žiūru į tave, pamirštu viską aplink.",
    "Tavo šypsena - mano geriausias vaistas.",
    "Jei turėčiau galimybę rinktis, rinkčiausi tave vėl ir vėl.",
    "Tu kaip saulė - nušviesi mano dieną.",
    "Kai esi šalia, laikas sustoja.",
    "Tavo balsas - mieliausia muzika mano ausims.",
    "Tu kaip pasaka, kurią noriu skaityti kasdien.",
    "Vien tavo buvimas šalia daro mane laimingą.",
    "Jei gyvenimas yra kelionė, noriu eiti tuo keliu su tavimi.",
    "Ar tiki stebuklais? Nes aš tikrai sutikau vieną.",
    "Tavo akys spindi labiau nei žvaigždės danguje.",
    "Jei galėčiau, kiekvieną rytą pradėčiau nuo tavo šypsenos.",
    "Ar tu magija? Nes kiekvieną kartą, kai tave matau, viskas tampa tobula.",
    "Kai tu esi šalia, visi kiti tampa nematomi.",
    "Jei gyvenimas yra daina, tu esi gražiausia nata joje.",
    "Tu kaip svajonė, kurios nenoriu pabusti.",
    "Kai matau tave, man atrodo, kad viskas yra įmanoma.",
    "Tavo meilė - mano didžiausias turtas.",
    "Tavo balsas skamba kaip mylimiausia melodija.",
    "Jei meilė yra menas, tu esi mano gražiausias kūrinys.",
    "Tu esi atsakymas į visas mano maldas.",
    "Tavo prisilietimas yra kaip elektros impulsas mano širdyje.",
    "Jei galėčiau skaičiuoti, kiek kartų galvoju apie tave, jau būčiau pasiklydęs skaičiuose.",
    "Tu esi priežastis, kodėl kiekviena diena yra ypatinga.",
    "Jei būtum daina, aš norėčiau klausytis tavęs per amžius.",
    "Kai laikau tavo ranką, jaučiu, kad galiu nugalėti visą pasaulį.",
    "Tu esi kaip pirmoji saulės šviesa po ilgos nakties.",
    "Tavo meilė yra kaip ugnis, kuri šildo mano širdį.",
    "Kiekvienas tavo žodis - tai muzika mano sielai.",
    "Kai esi šalia, visas pasaulis tampa spalvingesnis.",
    "Tavo apkabinimas yra mano saugiausia vieta pasaulyje.",
    "Kiekviena akimirka su tavimi yra neįkainojama."
]

advance = [
    "Tavo akys tokios gilesnės už jūrą, kad prarandu save jose.",
    "Noriu praleisti kiekvieną akimirką su tavimi, nes su tavimi laiką pamirštu.",
    "Tu esi kaip šviesa tamsoje, mano širdis negali atsispirti tau.",
    "Kai bučiuoju tave, pamirštu viską, net kas yra aplink.",
    "Tavo kvapas yra toks, kad jis man primena namus, kurių niekada nesu turėjęs.",
    "Kai žiūriu į tave, pasaulis tarsi sustoja, ir tik tu ir aš egzistuojame.",
    "Jei būtų pasaulyje tik viena šypsena, tavo šypsena būtų ta, kurią norėčiau matyti kasdien.",
    "Mano širdis pradeda plakti greičiau kiekvieną kartą, kai tu esi netoliese.",
    "Ar žinai, kad tavo juokas yra kaip geriausia melodija, kuria noriu klausytis visą gyvenimą?",
    "Tavo buvimas mano gyvenime yra tarsi gėris, kurio negaliu atsisakyti.",
    "Jei galėčiau tavęs paklausti vieno dalyko, norėčiau sužinoti, kaip tu sugebi būti tokia nuostabi.",
    "Jei būtum kūrinys, tu būtum meno šedevras, kurį norėčiau apžiūrinėti be pabaigos.",
    "Tu manęs įkvepi kiekvieną dieną, net kai atsikeliu, žinodamas, kad tave turiu šalia.",
    "Kai esi šalia, jaučiuosi tarsi pasiekęs aukščiausią savo gyvenimo viršūnę.",
    "Tu esi man tas pats, kas saulė rytą, užpildai visą pasaulį šiluma ir šviesa.",
    "Noriu, kad kiekviena diena būtų tavo prisilietimo kupina, nes su tavimi gyvenimas tampa nuostabus.",
    "Tu esi kaip pasaka, kurią norėčiau skaityti kiekvieną dieną, kad tik nesibaigtų.",
    "Tu tapai mano svajonių gyvenimo dalimi, be kurios negaliu įsivaizduoti ateities.",
    "Net jei pasaulis sugriūtų, būčiau laimingas tik dėl to, kad turiu tave.",
    "Tavo šypsena yra šviesa mano tamsiuose momentuose.",
    "Tavo rankos - mano saugiausia vieta šiame pasaulyje.",
    "Tu esi mano paslaptis, kurią noriu pasilikti sau amžinai.",
    "Kai pamatau tave, pamirštu viską, nes tu esi viskas, ko man reikia.",
    "Tavo buvimas su manimi visada padaro mano pasaulį tobulu.",
    "Tu esi kaip žvaigždė naktiniame danguje, švytinti net tamsiausiomis akimirkomis.",
    "Aš noriu būti tavo poilsiu ir tavo drąsa, tavo stiprybe ir tavo švelnumu.",
    "Tavo buvimas šalia yra tarsi svajonė, kurios nesinori atsibusti.",
    "Visos pasaulio grožybės nieko nesveria prieš tave, nes tu esi mano viskas.",
    "Tu esi tas žmogus, su kuriuo norėčiau praleisti visą savo gyvenimą.",
    "Tavo širdis turi magiją, kuri mane traukia be jokių pastangų.",
    "Aš noriu dalintis su tavimi kiekviena gyvenimo akimirka, nes su tavimi viskas yra gražu.",
    "Kai esi šalia, aš jaučiuosi lyg būčiau įžengęs į kitą pasaulį, kur viskas yra tobula.",
    "Tu ne tik graži, tu esi mano šviesa ir mano šešėlis, mano diena ir naktis.",
    "Mano širdis girdi tavo širdies ritmą, ir jis yra viskas, ko man reikia.",
    "Aš noriu būti tavo svajonė ir tavo realybė, nes su tavimi mano pasaulis įgauna prasmes.",
    "Tu esi tas žmogus, kurio niekada nenorėčiau prarasti, nes tu užpildai mano gyvenimą džiaugsmu.",
    "Jei reikėtų pasirinkti tarp gyvenimo ir tavęs, aš pasirinkčiau tave.",
    "Tu esi mano meilės ir aistros įsikūnijimas.",
    "Aš noriu su tavimi kurti mūsų istoriją, nes su tavimi gyvenimas tampa įsimintinas.",
    "Tu esi mano gyvenimo reikšmė, mano gyvenimo stebuklas.",
    "Kai bučiuoju tave, jaučiu, kaip mūsų širdys susijungia į vieną.",
    "Aš visada žinojau, kad meilė egzistuoja, bet niekada nesupratau, kas tai, kol tavęs nepažinau.",
    "Tu esi kaip šviesa tamsoje, suteikianti mano gyvenimui prasmę.",
    "Kai tu mane apkabini, man atrodo, kad pasaulis sustoja ir niekas kitas neegzistuoja.",
    "Aš noriu su tavimi pasenti, nes su tavimi laikas tampa begalinis.",
    "Tu tapai mano gyvenimo ritmu, su kuriuo noriu eiti per visą pasaulį.",
    "Tavo meilė man yra viskas, ko man reikia, kad jausčiausi pilnas.",
    "Kai būnu su tavimi, aš esu pats geriausias žmogus, kokiu galiu būti.",
    "Tavo prisilietimas man suteikia daugiau džiaugsmo nei bet koks materialus turtas.",
    "Tu esi mano įkvėpimas, mano vidinė stiprybė.",
    "Tavo akys yra langas į pasaulį, kurį noriu matyti kiekvieną dieną.",
    "Tavo meilė - tai lėtas ir nuostabus šokis, kuris niekada nesibaigia.",
    "Aš noriu su tavimi praleisti amžinybę, nes tu esi mano pradžia ir pabaiga.",
    "Tavo šypsena yra mano rytinis pabudimas, mano dienos pradžia.",
    "Tu esi mano pasaulio spalvos, mano gyvenimo grožis.",
    "Kai tu mane lieči, jaučiu, kaip mano siela dainuoja.",
    "Tu esi mano sapnas, kurį noriu gyventi kasdien.",
    "Tavo akys - tai šaltinis, kuris mane nuolat žavi.",
    "Aš noriu, kad tu būtum mano ryto aušra ir mano vakaro žvaigždė.",
    "Tu esi viskas, apie ką svajojau, ir daugiau nei galėjau tikėtis.",
    "Tavo šypsena ir buvimas su manimi daro pasaulį žymiai geresnį.",
    "Tu esi mano šviesa ir tamsa, mano gyvenimo pradžia ir pabaiga.",
    "Nėra nieko vertingesnio už tavo meilę.",
    "Kai aš su tavimi, gyvenimas tampa nuostabus nuotykis.",
    "Tu esi mano širdies dainos melodinga nata.",
    "Tavo buvimas su manimi yra didžiausias gyvenimo stebuklas.",
    "Tavo rankos apkabina mano širdį, ir aš negaliu sustoti mylėti tavęs.",
    "Tu esi mano gyvenimo saulė ir mėnulis, tuščiomis akimirkomis.",
    "Tu sugebi paversti net paprasčiausią akimirką magiška.",
    "Tavo šypsena yra šiluma, kuri apšviečia mano tamsiąsias dienas.",
    "Mano gyvenimas yra geresnis, nes tu esi jame.",
    "Tu esi mano džiaugsmo ir laimės šaltinis, ir niekas man nesvarbiau nei tu.",
    "Kiekvienas momentas su tavimi yra dovana, kurią noriu atidaryti vėl ir vėl.",
    "Tavo meilė man yra tarsi vėjas, kuris užpildo mano širdį laime.",
    "Aš noriu praleisti kiekvieną akimirką su tavimi, nes tu esi mano viskas.",
    "Tu esi mano begalinė laimė, mano nepaliaujamas džiaugsmas.",
    "Kai matau tave, man atrodo, kad visas pasaulis pabunda iš sapno.",
    "Tu esi mano gyvenimo kvėpavimas, be kurio negalėčiau egzistuoti.",
    "Tavo rankos - mano ramybė, tavo buvimas - mano gyvenimas.",
    "Tu esi mano meilės pradžia ir pabaiga.",
    "Tu esi mano atsakymas į visus klausimus, kurie kildavo mano širdyje.",
    "Aš noriu, kad kiekviena diena būtų tavo šviesos apgaubta.",
    "Tavo meilė - tai jėga, kuri mane stumia į priekį kiekvieną dieną.",
    "Tu esi mano vidinė stiprybė, mano ramybė šioje chaotiškoje pasaulio vietoje.",
    "Tavo meilė man yra svarbesnė už viską, ką gali pasiūlyti pasaulis.",
    "Tu esi mano sielos draugas, mano gyvenimo meilė.",
    "Tavo šypsena uždega mano širdį, ir aš noriu, kad ji degtų amžinai.",
    "Mano gyvenimas tapo pilnas dėl tavęs.",
    "Kai žiūriu į tave, matau savo ateitį.",
    "Tu esi kaip stebuklas, kurio laukiau visą gyvenimą.",
    "Su tavimi aš noriu gyventi amžinai.",
    "Tavo buvimas mano gyvenime - tai vertybė, kurios negaliu įvertinti.",
    "Tavo meilė man yra vienas didžiausių gyvenimo turtų."
]

it_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
