simple = [
    "Tu esi mano saulėta diena.",
    "Ar tavo vardas Google? Nes tu turi viską, ko ieškau.",
    "Ar tiki meile iš pirmo žvilgsnio, ar turėčiau vėl praeiti pro šalį?",
    "Atrodai kaip kažkas, ką pieščiau savo svajonėse.",
    "Ar galiu pasiskolinti tavo širdį? Pažadu, grąžinsiu su meile.",
    "Tavo šypsena – mano mėgstamiausia melodija.",
    "Ar tu burtininkė? Nes kiekvieną kartą, kai tave matau, mano pasaulis sustoja.",
    "Jei būtum vaisius, būtum saldus mangas.",
    "Tavo akys – du žvaigždynai, kuriuos noriu tyrinėti.",
    "Jei gročiau gitarą, parašyčiau tau meilės dainą.",
    "Mano širdis šoka kiekvieną kartą, kai matau tave.",
    "Esi lyg kava – be tavęs mano rytas būtų nuobodus.",
    "Ar tau skauda? Nes tikriausiai ką tik nukritai iš dangaus.",
    "Net ir audringą dieną tavo šypsena gali išsklaidyti debesis.",
    "Tavo balsas skamba kaip gražiausia melodija pasaulyje.",
    "Ar tu magnetas? Nes mane traukia tik prie tavęs.",
    "Tu man esi lyg paslaptis, kurią noriu visą gyvenimą atskleisti.",
    "Mano širdis praleidžia plakimą kiekvieną kartą, kai matau tave.",
    "Ar galime padaryti nuotrauką kartu? Noriu įrodyti draugams, kad sutikau angelą.",
    "Tavo buvimas – geriausia dovana, kokią galėjau gauti.",
    "Kiekviena sekundė su tavimi – tai mažas rojus.",
    "Ar tiki likimu? Nes atrodo, kad mes buvome skirti vienas kitam.",
    "Tu tokia ypatinga, kad žodžiai tampa per silpni apibūdinti tavo grožį.",
    "Ar galiu būti tavo mylimasis? Pažadu, būsiu geriausias pasirinkimas.",
    "Tavo kvapas – lyg pavasario gėlės, kurios užburia visą pasaulį.",
    "Jei būčiau rašytojas, parašyčiau apie tave meilės romaną.",
    "Tavo akys švyti kaip dvi mėnulio šviesos naktyje.",
    "Tu tokia karšta, kad gali ištirpdyti visą sniegą žiemą.",
    "Jei būtum spalva, būtum mano mėgstamiausia.",
    "Tavo šypsena gali apšviesti net tamsiausią dieną.",
    "Aš norėčiau būti tavo pagalve, kad galėčiau būti šalia kiekvieną naktį.",
    "Tu man – lyg pasaka, kurią noriu skaityti dar ir dar kartą.",
    "Ar mes pažįstami iš praeito gyvenimo? Nes jaučiu, kad mes turėjome būti kartu.",
    "Tavo balsas – muzika mano sielai.",
    "Ar galiu laikyti tavo ranką? Noriu įsitikinti, kad esi tikra.",
    "Tavo akys – dvi mėlynos jūros, kuriose skęstu kasdien.",
    "Be tavęs, mano gyvenimas būtų nespalvotas.",
    "Ar galiu tau iškepti pyragą? Nes tu esi mano saldi svajonė.",
    "Tu toks nuostabus, kad net žodžiai tampa nereikalingi.",
    "Tavo buvimas mane užpildo džiaugsmu.",
    "Ar galiu būti tavo šešėlis? Noriu būti šalia tavęs visada.",
    "Jei meilė būtų liga, aš jau būčiau beviltiškai užsikrėtęs.",
    "Ar gali man pasakyti savo vardą? Noriu jį įrašyti į savo širdį.",
    "Tavo juokas – gražiausia melodija, kurią kada nors girdėjau.",
    "Mano širdis kiekvieną kartą stipriau plaka, kai esi šalia.",
    "Tavo akys spindi labiau nei žvaigždės danguje.",
    "Tavo prisilietimas – magija, kurios negaliu pamiršti.",
    "Tu mane užburiai, ir dabar aš negaliu tavęs pamiršti.",
    "Jei būtume filmas, mes būtume gražiausia meilės istorija.",
    "Ar tavo tėvai kepėjai? Nes tu tikras saldainis.",
    "Ar turi žemėlapį? Nes aš pasiklydau tavo akyse.",
    "Tavo šypsena – mano dienos saulės spindulys.",
    "Kiekviena minutė be tavęs atrodo kaip amžinybė.",
    "Tu esi priežastis, kodėl aš tikiu meile iš pirmo žvilgsnio.",
    "Ar galime kartu pasivaikščioti? Noriu prisiminti šią akimirką visam laikui.",
    "Aš tavęs ieškojau visą gyvenimą, ir pagaliau radau.",
    "Tu – pats gražiausias mano sapnas, pavirtęs realybe.",
    "Tavo žvilgsnis mane šildo labiau nei vasaros saulė.",
    "Jei turėčiau vieną norą, norėčiau visą gyvenimą praleisti su tavimi.",
    "Tu priversti mano širdį dainuoti laimės dainą.",
    "Tavo prisilietimas – lyg švelnus vėjo dvelksmas.",
    "Ar galiu būti tavo gyvenimo nuotykis?",
    "Tu esi tarsi paslėpta lobių skrynia – neįkainojama ir ypatinga.",
    "Aš tikiu magija, nes tu egzistuoji.",
    "Tavo meilė – mano mėgstamiausia istorija.",
    "Be tavęs mano gyvenimas būtų kaip naktis be mėnulio.",
    "Ar galiu būti tavo mėgstamiausia klaida?",
    "Tavo meilė – kaip vaivorykštė po lietaus.",
    "Esi kaip gražiausia poezijos eilutė – tobula.",
    "Mano širdis priklauso tau, ar priimsi ją?",
    "Aš nežinojau, kas yra tikra meilė, kol nesutikau tavęs.",
    "Esi tokia ypatinga, kad mano pasaulis sukasi aplink tave."
]

advance = [
    "Tavo akys – lyg gilios jūros, kuriose norėčiau paskęsti amžiams.",
    "Jei meilė būtų menas, tu būtum pats tobuliausias šedevras.",
    "Tavo balsas – tai melodija, kurią norėčiau girdėti kiekvieną savo gyvenimo dieną.",
    "Tu esi lyg knyga, kurios puslapius norėčiau skaityti visą gyvenimą.",
    "Jei galėčiau sustabdyti laiką, tai padaryčiau akimirkoje, kai šypsaisi man.",
    "Tavo prisilietimas – lyg švelnus vėjas, kuris užburia ir palieka neišdildomą jausmą.",
    "Kiekvieną kartą, kai matau tave, mano širdis sugroja simfoniją, kurios negaliu sustabdyti.",
    "Jei galėčiau būti bet kuo, norėčiau būti tavo mėgstamiausia mintis.",
    "Tavo juokas skamba lyg daina, kurios norisi klausytis vėl ir vėl.",
    "Aš nesu poetas, bet kai tave matau, mano širdis kuria eiles be žodžių.",
    "Jei būtum žvaigždė, būtum ryškiausia danguje – tokia, kurios niekas negali nepastebėti.",
    "Tavo akys slepia paslaptis, kurias norėčiau atrasti ir saugoti amžinai.",
    "Kiekvienas tavo prisilietimas įdega mano širdyje neišdildomą ugnį.",
    "Esi tarsi magija, kurios negaliu paaiškinti, bet jaučiu kiekviena savo esybės dalimi.",
    "Jei būčiau rašytojas, visos mano istorijos būtų apie tave.",
    "Tavo buvimas – lyg saulėtas rytas po ilgos ir šaltos nakties.",
    "Net jei pasaulis nustos suktis, mano meilė tau išliks amžina.",
    "Tavo vardas skamba mano mintyse lyg gražiausia daina.",
    "Tu esi vienintelė lygtis, kurios negaliu išspręsti, bet nenoriu nė bandyti.",
    "Tavo šypsena – mano mėgstamiausia vieta šiame pasaulyje.",
    "Aš neprisimenu savo gyvenimo be tavęs, nes atrodo, kad tu jį pripildei nuo pat pradžių.",
    "Kiekvieną kartą, kai tave matau, mano pasaulis tampa truputį geresnis.",
    "Jei turėčiau vieną norą, norėčiau praleisti amžinybę tavo glėbyje.",
    "Kai esi šalia, laikas sustoja, o kai tavęs nėra – jis juda per greitai.",
    "Tu esi priežastis, kodėl kiekviena diena atrodo pilna galimybių ir stebuklų.",
    "Jei meilė būtų daina, tu būtum mano mėgstamiausia melodija.",
    "Tavo akys pasako daugiau nei visi pasaulio žodžiai.",
    "Esi mano širdies raktas, kurio niekas kitas neturės.",
    "Aš nesu filosofas, bet su tavimi atrandu gyvenimo prasmę.",
    "Tu esi viskas, ko niekada nežinojau, kad man reikia, bet dabar negaliu be tavęs gyventi.",
    "Tavo kvapas, tavo balsas, tavo buvimas – viskas manyje kuria ramybę.",
    "Jei meilė būtų vynas, su tavimi norėčiau būti visada apsvaigęs.",
    "Tavo prisilietimas – tarsi elektros srovė, kuri pažadina mano sielą.",
    "Mano širdis yra drobė, o tu esi spalvos, kurios ją užpildo gyvybe.",
    "Ar gali pasakyti man savo paslaptį? Kaip tau pavyksta būti tokiai tobulai?",
    "Kiekviena minutė su tavimi – tai istorija, kurią noriu išgyventi vėl ir vėl.",
    "Jei gyvenimas būtų kelionė, norėčiau, kad būtum mano paskutinė stotelė.",
    "Tavo balsas – lyg lietus po sausros, atgaivinantis mano širdį.",
    "Tu esi lyg nakties dangus – paslaptinga, kerinti ir pilna stebuklų.",
    "Net jei turėčiau visą pasaulį, be tavęs jausčiausi tuščias.",
    "Kai esi šalia, kiekviena problema atrodo nereikšminga.",
    "Jei turėčiau galią sustabdyti laiką, sustabdyčiau jį su tavimi.",
    "Tavo meilė – tai ugnis, kuri šildo mano sielą.",
    "Aš nenoriu būti tavo istorijos skyriumi, noriu būti visa tavo knyga.",
    "Tu esi priežastis, kodėl tikiu stebuklais.",
    "Tavo prisilietimas įžiebia manyje jausmus, kurių negaliu nusakyti žodžiais.",
    "Jei meilė būtų upė, tu būtum jos srovė, kuri mane neša pasroviui.",
    "Aš neieškau tobulybės, bet kai žiūriu į tave, matau ją visame kame.",
    "Tu esi mano gyvenimo spalva, be tavęs viskas būtų pilka.",
    "Tavo meilė yra vynas, kuris su kiekviena diena tampa tik geresnis.",
    "Tavo širdis – tai vieta, kur norėčiau pasiklysti ir niekada nebegrįžti.",
    "Su tavimi kiekviena akimirka tampa nepakartojama.",
    "Tu esi mano ramybė audringoje jūroje.",
    "Aš nežinau, kas yra dangus, bet jei jis egzistuoja, tai tu esi jo dalis.",
    "Jei būčiau dailininkas, mano kiekvienas potėpis būtų skirtas tau.",
    "Tavo buvimas šalia yra viskas, ko man reikia.",
    "Jei meilė būtų menas, tu būtum Mona Liza.",
    "Mano širdis dainuoja tavo vardą kiekvieną akimirką.",
    "Tu esi ta svajonė, iš kurios nenoriu atsibusti.",
    "Tavo meilė mane moko, kad tikri jausmai neturi ribų.",
    "Jei turėčiau tūkstantį gyvenimų, kiekviename jų pasirinkčiau tave.",
    "Aš nesu poetinis žmogus, bet kai matau tave, širdis pati kuria eiles.",
    "Tavo juokas yra šilčiausia melodija, kurią girdėjau.",
    "Su tavimi net ir ilgiausia kelionė atrodo per trumpa.",
    "Tu esi tarsi žvaigždė, kuri šviečia mano gyvenime net ir tamsiausią naktį.",
    "Tavo meilė yra paslaptis, kurią noriu saugoti visą gyvenimą.",
    "Net jei pasaulis sugriūtų, aš vis dar stovėčiau šalia tavęs.",
    "Tavo prisilietimas – tai burtai, kurių niekada nenoriu pamiršti."
]

lt_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
