simple = [
    "Tu esi skaistāka par saulrietu.",  
    "Tavs smaids ir kā saule manā dienā.",  
    "Tu man liec smaidīt, pat ja nav iemesla.",  
    "Tavas acis ir kā zvaigznes – spožas un noslēpumainas.",  
    "Ja es būtu gleznotājs, tu būtu mana iedvesma.",  
    "Tava balss ir skaistākā melodija, ko esmu dzirdējis.",  
    "Es zaudēju laiku, kad skatos uz tevi.",  
    "Vai tev sāpēja, kad kriti no debesīm kā eņģelis?",  
    "Tu esi viss, ko es meklēju.",  
    "Es nevaru novērst acis no tevis.",  
    "Tu esi mana vismīļākā doma.",  
    "Es domāju par tevi pat sapņos.",  
    "Ja skaistums būtu noziegums, tu būtu ieslodzīta uz mūžu.",  
    "Es gribētu būt tavs spogulis, lai varētu tevi redzēt katru dienu.",  
    "Mēs noteikti esam satikušies kādā sapnī.",  
    "Ja tava mīlestība būtu jūra, es tajā peldētu mūžīgi.",  
    "Tavs smiekli ir manas mīļākās skaņas.",  
    "Vai es varu tev uzdāvināt zvaigzni? Nē, jo tu jau esi mana spožākā.",  
    "Es tevi mīlu vairāk nekā šokolādi.",  
    "Es varētu klausīties tevi runājam mūžīgi.",  
    "Tava enerģija ir lipīga – es vienmēr gribu būt tev blakus.",  
    "Tu esi tik īpaša, ka pat ziedi greizsirdīgi skatās uz tevi.",  
    "Vai mēs varam kopā uzrakstīt savu mīlas stāstu?",  
    "Tu dari manu pasauli krāsaināku.",  
    "Ja es būtu dzejnieks, tu būtu mans dzejolis.",  
    "Tavas acis ir tik dziļas, ka es tajās pazustu.",  
    "Man šķiet, ka mana sirds dejo katru reizi, kad es tevi redzu.",  
    "Vai tev ir karte? Es esmu apmaldījies tavās acīs.",  
    "Tu esi kā burvestība, kas mani apbūra.",  
    "Kad tu smaidi, visa pasaule kļūst skaistāka.",  
    "Es gribu būt tavs pirmais rīta sveiciens un pēdējais vakara čuksts.",  
    "Tu esi mana iecienītākā mīlas dziesma.",  
    "Kad es esmu ar tevi, laiks apstājas.",  
    "Manai sirdij ir tikai viens īpašnieks – tu.",  
    "Tu esi tik burvīga, ka pat mēness apskauž tavu gaismu.",  
    "Es nevaru noticēt, ka kāds tik skaists kā tu pastāv.",  
    "Tev piemīt noslēpumains šarms, kas mani apbur.",  
    "Man šķiet, ka mēs esam radīti viens otram.",  
    "Tu esi kā vismīļākā grāmata, ko gribas lasīt atkal un atkal.",  
    "Es varētu stundām ilgi skatīties tavās acīs.",  
    "Es zinu, ka eņģeļi pastāv, jo es satiku tevi.",  
    "Tavas lūpas ir kā visgaršīgākais vīns.",  
    "Vai es varu tevi turēt rokās mūžīgi?",  
    "Kad es domāju par tevi, mana sirds sāk pukstēt straujāk.",  
    "Tavs skatiens mani padara vājprātīgi laimīgu.",  
    "Tu esi mana vismīļākā pasaka.",  
    "Vai tu esi burvis? Jo katru reizi, kad es tevi redzu, es zaudēju dūšu.",  
    "Es gribu tevi iepazīt vēl vairāk.",  
    "Tu dari manu dienu gaišāku.",  
    "Es nevaru sagaidīt, kad atkal tevi redzēšu.",  
    "Tu esi kā pavasara vēsma – svaiga un dzīvības pilna.",  
    "Es gribu ar tevi dalīties visos savos sapņos.",  
    "Tava klātbūtne ir mana mīļākā vieta.",  
    "Tu esi kā zieds, kas nekad nevīst.",  
    "Mans prāts saka nē, bet mana sirds kliedz jā!",  
    "Tu esi skaistāka par jebkuru gleznainu ainavu.",  
    "Es varētu būt tavs bruņinieks spožās bruņās.",  
    "Tu esi mana vismīļākā doma katru dienu.",  
    "Ja es būtu rakstnieks, tu būtu mana mīlas romāna varone.",  
    "Tu esi tik burvīga, ka man gribas tevi turēt cieši un nekad neatlaist.",  
    "Kā tu dari, lai viss izskatās tik skaisti, kad esi tuvumā?",  
    "Man pietiek tikai viena skatiena, lai sajustu, cik īpaša tu esi.",  
    "Tu padari manu sirdi traku.",  
    "Es vēlos būt tavs mīļākais skatiens.",  
    "Vai es varu būt tava mīlas dziesma?",  
    "Tu esi kā siltā vasaras diena manā dzīvē.",  
    "Es gribu būt tavs vismīļākais sapnis.",  
    "Es vēlos, lai mūsu stāsts nekad nebeigtos.",  
    "Tu esi kā brīnums, kuru es nekad negribu palaist garām.",  
    "Kad es esmu ar tevi, pasaule kļūst gaišāka.",  
    "Tu esi viss, ko esmu jebkad vēlējies.",  
    "Man šķiet, ka tava mīlestība ir mana vislielākā dāvana.",  
    "Ja es būtu dzejnieks, tu būtu mana iedvesma katram vārdam.",  
    "Es jūtu, ka esmu atradis savu otru pusi.",  
    "Tu esi kā mūzika, kas nekad nebeidzas.",  
    "Kad es domāju par tevi, manas lūpas automātiski smaida.",  
    "Tu esi kā sapnis, kuru negribu pamest.",  
    "Vai mēs varam kopā radīt laimīgu nākotni?",  
    "Tavas acis ir mana mīļākā ainava.",  
    "Es gribu tevi mīlēt no rīta līdz vakaram.",  
    "Ja es varētu izvēlēties jebkuru vietu pasaulē, es izvēlētos būt blakus tev.",  
    "Es nekad neesmu juties tik dzīvs kā tad, kad esmu ar tevi.",  
    "Tavs smaids ir mana mīļākā daļa no dienas.",  
    "Tu esi manas dzīves skaistākais pārsteigums.",  
    "Es nezinu, kas ir perfekcija, bet, ja tā eksistē, tad tā esi tu.",  
    "Ja es būtu putns, es lidotu pie tevis katru dienu.",  
    "Tevi redzot, mana sirds sāk pukstēt ātrāk nekā jebkad.",  
]

advance = [
    "Tava balss ir kā mūzika, kas manā sirdī spēlē vismaigākās melodijas.",
    "Ja es varētu rakstīt zvaigznēs, es uzrakstītu tavu vārdu visā debesjumā.",
    "Kad es skatos uz tevi, laiks apstājas un pasaule kļūst mazāk svarīga.",
    "Tu esi kā dzeja, kuru man gribas lasīt atkal un atkal, līdz galvenais varonis kļūst par daļu no manas dzīves.",
    "Katru reizi, kad mūsu acis satiekas, es jūtu elektrību, kas skrien cauri manam ķermenim.",
    "Ja mana sirds būtu pils, tad tu būtu tās karaliene.",
    "Tu esi kā reta grāmata – jo vairāk es tevi iepazīstu, jo grūtāk ir atrauties no tevis.",
    "Tavi skūpsti droši vien spēj izdziedināt jebkuru brūci manā sirdī.",
    "Vai tu zināji, ka katra sekunde, ko pavadu bez tevis, ir veltīga?",
    "Tu esi manas dzīves uguns, kas nekad nedzēšas.",
    "Tavs smaids ir tik bīstams, ka tas varētu apstādināt satiksmi uz visiem laikiem.",
    "Tu esi kā rīta rasa – svaiga, dzīvīga un tik patīkami veldzējoša.",
    "Ja laime būtu cilvēks, tai būtu tavs vārds un tava seja.",
    "Tava klātbūtne ir kā grāmata, kuru gribas lasīt lēnām, lai tā nekad nebeigtos.",
    "Tava smarža ir kā pavasara vējš, kas piepilda manas plaušas ar tīru ekstāzi.",
    "Ja mūsu sirdis būtu melodija, tad tās spēlētu visskaistāko simfoniju.",
    "Tu esi kā mākslas darbs, kas iedvesmo mani katru reizi, kad uz tevi skatos.",
    "Ja es būtu fotogrāfs, es gribētu notvert katru tavu mirkli un saglabāt to uz mūžību.",
    "Tavas rokas šķiet kā radītas, lai tās satvertu manējās un nekad neatlaistu.",
    "Tu esi kā sapnis, no kura negribu pamosties.",
    "Es vēlos būt tuvāk tavai dvēselei nekā jebkurš cits šajā pasaulē.",
    "Ja man būtu jāizvēlas starp pasaules bagātībām un vienu vakaru ar tevi, es nešauboties izvēlētos tevi.",
    "Es gribu būt tava pēdējā doma pirms miega un pirmā doma, kad tu pamosties.",
    "Tavas acis ir kā okeāns, kurā esmu gatavs noslīkt bez nožēlas.",
    "Tu esi mans visdārgākais noslēpums, kuru es vēlos atklāt katru dienu no jauna.",
    "Ja mūsu sirdis būtu puzles gabaliņi, tās saskanētu nevainojami.",
    "Es gribu būt tavs iecienītākais svešinieks, kurš kļūst par neaizvietojamu mīlestību.",
    "Ja tava mīlestība būtu valoda, es gribētu to iemācīties līdz pilnībai.",
    "Mans sapnis ir reiz atskatīties uz mūsu dzīvi un zināt, ka mēs uzrakstījām visskaistāko mīlas stāstu.",
    "Ja es būtu dzejnieks, es katru dienu rakstītu sonetus tikai par tevi.",
    "Tu esi kā siltā vasaras nakts – maiga, vilinoša un pilna noslēpumu.",
    "Ja tava mīlestība būtu vīns, es gribētu to baudīt līdz mūža galam.",
    "Tu esi mana lielākā piedzīvojuma sākums un mans mierīgākais patvērums vienlaikus.",
    "Ja mīlestība ir māksla, tad mēs kopā veidojam šedevru.",
    "Es nekad nezināju, cik skaista var būt pasaule, līdz tajā ienāci tu.",
    "Ja es varētu tvert vienu mirkli un saglabāt to mūžīgi, tas būtu brīdis, kad skatos tavās acīs.",
    "Kad tu ej garām, pat vējš aiztur elpu.",
    "Tu esi kā skaista dziesma, kas skan manā prātā un nekad neapnīk.",
    "Ja es būtu astronoms, tu būtu mana vismīļākā zvaigzne.",
    "Tavs smaids ir kā dienasgaisma manā pelēkajā pasaulē.",
    "Tu esi kā noslēpumaina grāmata, kuru gribas lasīt lēnām un saprast katru tās vārdu.",
    "Ja mūsu dzīves būtu filma, es gribētu, lai tā būtu bezgalīga romantika.",
    "Tu esi kā rīts pēc ilgas nakts – svaiga, mīļa un pilna cerību.",
    "Tu esi mana atbilde uz visiem jautājumiem, ko dzīve man uzdod.",
    "Ja laime būtu vieta, es atrastu to tieši tev blakus.",
    "Es gribu būt tavs visskaistākais piedzīvojums un tava maigākā atmiņa.",
    "Kad es dzirdu tavu balsi, es jūtos kā mājās.",
    "Tava tuvība ir viss, kas man nepieciešams, lai justos pilnīgs.",
    "Ja man būtu jāizvēlas viena lieta, ko mīlēt visu mūžu, es izvēlētos tevi.",
    "Mans prāts saka, ka esmu neprātīgs, bet mana sirds čukst, ka esmu laimīgs, jo mīlu tevi.",
    "Es gribu būt tavs vismīļākais skatiens, visjutekliskākais pieskāriens un visdziļākā elpa.",
    "Tu esi mans maigākais sapnis un visskaistākā realitāte.",
    "Tu esi kā kaislīgs stāsts, kas mani pilnībā pārņem.",
    "Ja mūsu likteņi būtu grāmatas, es gribētu, lai mūsu stāsti saplūst vienā.",
    "Es vēlos, lai mans sirdspuksts saskan ar tavu.",
    "Ja mīlestība ir spēle, es gribu spēlēt to kopā ar tevi līdz uzvarai.",
    "Es gribu būt tavs pirmais rīta smaids un tavs pēdējais vakara čuksts.",
    "Tu esi kā debess dzirkstošā gaisma, kas vada mani cauri nakts tumsai.",
    "Ja mana sirds būtu atslēga, tad tikai tavs smaids to varētu atvērt.",
    "Es gribu, lai mana dzīve būtu saistīta ar tavu līdz pašam galam.",
    "Kad tu esi blakus, pat klusums starp mums šķiet kā skaistākā melodija.",
]

lv = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
