simple = [
    "Awak ni ibarat bintang, sentiasa bersinar dalam hidup saya.",
    "Senyuman awak buat hati saya cair.",
    "Saya tak pandai matematik, tapi saya tahu awak + saya = cinta.",
    "Boleh tak saya simpan awak dalam hati saya selamanya?",
    "Saya tak perlukan kamera, sebab setiap kali tengok awak, saya nampak kecantikan sebenar.",
    "Awak ni macam teh tarik – manis dan sentiasa buat saya ketagih.",
    "Kalau saya jadi langit, awaklah pelangi saya.",
    "Awak ni ibarat mimpi yang saya tak nak bangun daripadanya.",
    "Saya rasa saya perlukan polis, sebab hati saya dah dicuri awak.",
    "Awak suka hujan? Sebab setiap kali hujan turun, hati saya ingat awak.",
    "Awak ni macam lagu kegemaran saya – saya boleh dengar awak berulang kali.",
    "Kalau saya ada bunga untuk setiap kali saya fikirkan awak, taman saya dah penuh.",
    "Awak ni macam WiFi – bila jauh, hati rasa tak sambung.",
    "Awak pandai sihir ke? Sebab saya asyik terbayang muka awak je.",
    "Saya suka awak lebih daripada saya suka nasi lemak.",
    "Kalau saya ikan, awak laut saya – tempat saya hidup.",
    "Mata saya tak pernah salah – ia nampak cinta bila tengok awak.",
    "Hati saya macam Google – jawapan dia selalu 'awak'.",
    "Saya nak jadi cermin mata awak – supaya saya boleh dekat dengan awak setiap hari.",
    "Awak buat saya senyum walau tanpa sebab.",
    "Cinta kita ibarat WiFi – kadang hilang, tapi bila ada, kuat sangat.",
    "Awak ni punca hati saya berdebar tiap kali jumpa.",
    "Saya bukan photographer, tapi saya boleh tangkap hati awak.",
    "Awak ni ibarat teh ais – sejuk tapi menyegarkan hati saya.",
    "Kalau awak jadi bulan, saya sanggup jadi langit untuk menemani awak.",
    "Setiap kali saya tengok awak, saya lupa semua masalah dunia.",
    "Awak ni macam alarm – sentiasa buat jantung saya berdegup laju.",
    "Hanya satu senyuman awak cukup untuk cerahkan hari saya.",
    "Awak buat saya percaya cinta pandang pertama itu wujud.",
    "Saya tak perlukan bintang jatuh, sebab awak dah cukup sempurna.",
    "Awak comel sangat, kucing saya pun jealous.",
    "Setiap mesej dari awak macam lagu romantik di telinga saya.",
    "Saya tak boleh tidur sebab awak asyik muncul dalam fikiran saya.",
    "Awak ni macam matematik – rumit tapi saya suka kira-kira dengan awak.",
    "Kalau cinta boleh diukur, awak dah melebihi had maksimum.",
    "Saya bukan penulis, tapi awak ilham cinta saya.",
    "Kalau saya lukis hati, bentuknya pasti macam awak.",
    "Awak buat saya lupa password telefon sendiri.",
    "Kalau saya robot, awak sistem operasi saya.",
    "Saya boleh dengar suara awak sepanjang hari tanpa bosan.",
    "Awak ni ibarat donut – manis dan buat saya ketagih.",
    "Cinta saya pada awak ibarat coding – kadang error, tapi tetap nak try lagi.",
    "Awak suka kopi? Sebab awak buat saya berjaga sepanjang malam.",
    "Kalau saya ada RM1 untuk setiap kali saya fikirkan awak, saya dah kaya sekarang.",
    "Awak ni macam meme kegemaran saya – tak pernah gagal buat saya senyum.",
    "Saya tak pandai pick-up line, tapi saya pandai suka awak.",
    "Hanya satu 'hai' dari awak boleh buat hati saya tenang.",
    "Saya tak perlukan GPS, sebab hati saya dah tetap ke arah awak.",
    "Awak ni ibarat aplikasi – sentiasa running dalam fikiran saya.",
    "Kalau cinta itu bahasa, awak adalah perbendaharaan kata saya.",
    "Awak ni macam bateri – cas penuh semangat saya.",
    "Saya tak perlukan cahaya bila awak ada.",
    "Awak buat saya lupa ex saya dalam 0.01 saat.",
    "Kalau awak bintang, saya sanggup jadi langit malam.",
    "Awak ni ibarat lirik lagu cinta – indah dan penuh makna.",
    "Saya mungkin nerd, tapi awak superhero hati saya.",
    "Saya rasa macam watak utama bila awak pandang saya.",
    "Awak ni macam coding yang clean – simple tapi perfect.",
    "Saya tak pernah percaya cinta online, sampai awak muncul.",
    "Awak adalah jawapan dari setiap doa saya.",
    "Kalau saya boleh peluk satu benda je hari ni, saya nak peluk awak.",
    "Awak suka Marvel? Sebab hati saya dah kena 'snap' dengan awak.",
    "Saya tak tahu sihir, tapi saya tahu awak buat hati saya terbang.",
    "Awak buat saya lupa yang saya tengah diet – sebab saya lapar cinta.",
    "Kalau saya planet, awak orbit saya.",
    "Awak ni macam puzzle terakhir yang lengkapkan hidup saya.",
    "Kalau saya buat wishlist, nama awak kat nombor satu.",
    "Awak adalah sebab kenapa saya check phone 100 kali sehari.",
    "Saya tak pandai bernyanyi, tapi hati saya nyanyi nama awak.",
    "Awak macam aplikasi premium – tak semua orang layak dapat.",
    "Setiap kali awak hantar emoji senyum, saya senyum lebih besar.",
    "Awak ni macam filter Instagram – buat semuanya nampak lebih indah.",
    "Saya rasa awak dan saya ada bug – asyik crash bila jauh.",
    "Awak adalah 'highlight' dalam hari saya yang membosankan.",
    "Saya tak tahu apa itu sempurna, sampai saya jumpa awak.",
    "Awak ni macam coding logic – selalu buat saya fikir panjang.",
    "Saya tak perlukan bulan dan bintang, cukup awak dalam hidup saya.",
    "Saya tak tahu kenapa, tapi awak selalu buat saya gementar.",
    "Awak ni macam secret ingredient – buat semuanya jadi lebih baik.",
    "Saya rasa awak bukan manusia biasa – awak luar biasa.",
    "Setiap kali saya nampak nama awak, hati saya senyum sendiri.",
    "Awak macam power bank – selalu cas hati saya.",
    "Awak dan saya macam function dan return – saling melengkapi.",
    "Saya rasa dunia ini lebih indah sebab adanya awak.",
    "Kalau saya ada superpower, saya nak slow-mo bila dengan awak.",
    "Saya bukan pujangga, tapi hati saya penuh dengan nama awak.",
    "Awak macam lagu cinta yang repeat dalam kepala saya.",
    "Saya bukan jurugambar, tapi saya tengok awak macam masterpiece.",
    "Kalau cinta ini game, awak MVP saya.",
    "Awak ni macam coding clean – susah nak cari, tapi bila dapat, puas hati.",
    "Awak macam bug yang saya tak nak fix.",
    "Saya rasa saya ada virus – virus cinta dari awak.",
    "Kalau hati saya laptop, awak password-nya.",
    "Awak ni macam background music yang saya tak pernah nak pause.",
    "Awak buat saya rasa setiap hari macam Valentine's Day.",
    "Saya tak kisah buffering, asalkan akhirnya saya dapat awak.",
    "Awak buat jantung saya loading laju-laju.",
    "Saya rasa awak dan saya boleh jadi love story paling sweet.",
    "Saya suka tengok mata awak – sebab saya nampak masa depan kita di dalamnya.",
    "Awak ni ibarat shortcut – terus ke hati saya.",
    "Saya tak perlukan AI, sebab awak cukup bijak curi hati saya.",
    "Awak buat saya nak tulis kod tentang cinta setiap hari.",
    "Kalau cinta boleh dihantar sebagai commit, saya push cinta saya ke repo awak.",
    "Awak dan saya macam syntax dan semantik – tak lengkap tanpa satu sama lain.",
    "Saya tak perlukan debugger bila dengan awak – semua rasa betul.",
    "Awak buat saya percaya pada keajaiban.",
    "Awak tak perlu makeup – senyuman awak dah cukup cantik.",
    "Saya tak tahu masa depan, tapi saya harap awak ada dalamnya.",
    "Awak adalah definisi sempurna dalam kamus hati saya."
]

advance = [
    "Saya bukan penyair, tapi setiap kali melihat awak, hati saya berpuisi sendiri.",
    "Bolehkah awak pinjamkan peta? Saya sesat dalam senyuman awak.",
    "Saya tidak percaya pada cinta pandang pertama, tapi senyuman awak buat saya ragu-ragu.",
    "Awak macam magnet, sebab saya rasa tertarik setiap kali nampak awak.",
    "Jika kecantikan awak adalah dosa, maka awak pasti seorang pendosa yang paling menawan.",
    "Bibir awak nampak sejuk, nak saya panaskan dengan satu ciuman?",
    "Awak suka kopi? Sebab saya rasa kita mempunyai ‘chemistry’ yang kuat.",
    "Saya tak pandai matematik, tapi saya tahu awak + saya = pasangan yang sempurna.",
    "Jika awak bintang, saya sanggup menjadi langit agar dapat memeluk awak setiap malam.",
    "Saya bukan jurugambar, tapi saya ingin menyimpan awak dalam setiap ingatan saya.",
    "Bolehkah saya jadi Google awak? Sebab saya ada semua jawapan untuk awak.",
    "Awak bukan WiFi, tapi kenapa saya rasa begitu terhubung dengan awak?",
    "Saya rasa kita kena ambil gambar bersama, sebab saya nak tunjuk pada anak cucu saya nanti bagaimana cinta sejati bermula.",
    "Hati saya macam bateri telefon, ia selalu penuh bila dengan awak.",
    "Saya bukan peramal, tapi saya nampak masa depan saya penuh dengan awak di dalamnya.",
    "Jika mencintai awak adalah pekerjaan, saya mahu menjadi pekerja sepenuh masa.",
    "Awak ni sihir ke? Sebab setiap kali awak senyum, dunia saya berhenti sekejap.",
    "Bolehkah saya pinjam jam tangan awak? Sebab saya nak tunjukkan masa depan kita bersama.",
    "Saya selalu lupa nama orang, tapi nama awak dah terpahat dalam hati saya.",
    "Saya boleh berhenti minum kopi, tapi saya tak boleh berhenti daripada memikirkan awak.",
    "Hati saya macam GPS, ia hanya tunjuk ke satu arah - awak.",
    "Awak macam lagu kegemaran saya, sebab saya nak dengar suara awak berulang kali.",
    "Saya bukan ahli fizik, tapi daya tarikan antara kita sangat kuat.",
    "Saya rasa saya patut bawa payung, sebab setiap kali awak senyum, hati saya mencair.",
    "Bolehkah awak ajar saya bagaimana untuk tidak jatuh cinta kepada awak?",
    "Jika saya punya satu peluang untuk membuat satu permintaan, saya akan minta untuk sentiasa ada di sisi awak.",
    "Jika hidup saya adalah filem, awak adalah babak paling indah yang pernah wujud.",
    "Adakah awak tahu awak ada sesuatu yang tak ada pada orang lain? Ya, hati saya.",
    "Saya bukan saintis, tapi saya pasti ada reaksi kimia antara kita.",
    "Saya bukan doktor, tapi melihat awak sahaja sudah cukup untuk menyembuhkan hari saya.",
    "Saya tak tahu berenang, tapi saya sanggup tenggelam dalam cinta awak.",
    "Kalau awak adalah mimpi, saya tak nak bangun lagi.",
    "Jika awak adalah cahaya, saya mahu menjadi cermin agar dapat memantulkan kecantikan awak.",
    "Awak adalah nota muzik yang menjadikan melodi hati saya sempurna.",
    "Saya bukan astronomi, tapi awak adalah bintang paling terang di langit hati saya.",
    "Saya tak pandai bermain catur, tapi saya pasti awak adalah ratu dalam hidup saya.",
    "Jika mencintai awak adalah permainan, saya tak pernah mahu menang sebab saya mahu bermain selamanya.",
    "Saya bukan pelukis, tapi awak memberi warna dalam kehidupan saya.",
    "Saya rasa saya dah tahu makna sebenar kecantikan, sebab saya dah jumpa awak.",
    "Jika saya boleh jadi apa sahaja, saya mahu jadi sebab awak tersenyum setiap hari.",
    "Bolehkah saya jadi bayang awak? Sebab saya mahu sentiasa bersama awak.",
    "Saya bukan malaikat, tapi hati saya sentiasa tertarik kepada awak seperti magnet.",
    "Awak macam matahari, sebab setiap kali awak dekat, hati saya jadi lebih hangat.",
    "Saya tak percaya pada takdir, tapi saya percaya bahawa kita memang ditakdirkan bersama.",
    "Saya tak perlu peta harta karun, sebab harta paling berharga adalah senyuman awak.",
    "Bolehkah awak sebut nama saya? Sebab saya nak tahu macam mana ia kedengaran dari bibir awak.",
    "Saya tak pandai teka-teki, tapi saya tahu jawapan kepada kebahagiaan saya – ia adalah awak.",
    "Jika hati boleh berbicara, ia akan menjerit nama awak setiap saat.",
    "Saya bukan jurutera, tapi saya mahu membina masa depan bersama awak.",
    "Saya bukan penulis, tapi setiap kali saya nampak awak, saya rasa mahu menulis puisi tentang awak.",
    "Awak ada pemadam? Sebab saya nak padam semua kenangan lama saya dan tulis yang baru bersama awak.",
    "Saya bukan pelawak, tapi saya mahu menjadi sebab awak ketawa setiap hari.",
    "Jika dunia ini hitam putih, awak adalah warna yang membuatnya indah.",
    "Saya bukan pesulap, tapi awak telah mencuri hati saya tanpa saya sedari.",
    "Saya bukan ahli sains, tapi saya rasa kehadiran awak adalah bukti bahawa keajaiban wujud.",
    "Saya tak pernah percaya pada cinta pandang pertama, sehingga saya bertemu awak.",
    "Saya bukan bintang filem, tapi saya mahu berlakon dalam kisah cinta bersama awak.",
    "Saya rasa saya perlu pakai cermin mata hitam, sebab cahaya kecantikan awak terlalu terang.",
    "Saya bukan ahli muzik, tapi degupan jantung saya selari dengan kehadiran awak.",
    "Awak tahu apa yang lebih indah daripada bulan dan bintang? Senyuman awak.",
    "Saya nak jadi air mata awak, supaya saya boleh lahir dari mata awak dan mati di bibir awak.",
    "Saya bukan malaikat, tapi saya sanggup jatuh dari syurga hanya untuk bersama awak.",
    "Jika cinta adalah seni, maka awak adalah masterpiece yang sempurna."
]

ms_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
