simple = [
    "Je ogen zijn als sterren, ze verlichten mijn nacht.",
    "Ben je een magneet? Want ik word steeds naar je toe getrokken.",
    "Als schoonheid tijd was, was jij een eeuwigheid.",
    "Ik geloof in liefde op het eerste gezicht, want ik zag jou en wist het meteen.",
    "Jij bent de reden waarom ik glimlach zonder reden.",
    "Is het hier warm, of ben jij gewoon zo heet?",
    "Als kusjes sneeuwvlokken waren, zou ik je een sneeuwstorm sturen.",
    "Ben je een camera? Want elke keer als ik je zie, glimlach ik.",
    "Mijn hart sloeg een slag over toen ik jou zag.",
    "Ik zou je graag meenemen naar de bioscoop, maar je bent mooier dan elke film.",
    "Je lach is zo mooi dat hij mijn dag oplicht.",
    "Als ik een bloem had voor elke keer dat ik aan je dacht, had ik een tuin.",
    "Jij en ik, samen? Dat klinkt als een geweldig idee.",
    "Je stem is als muziek voor mijn oren.",
    "Ik moet een toverstaf hebben, want telkens als ik je zie, voel ik magie.",
    "Kan ik je telefoon lenen? Ik moet mijn moeder vertellen dat ik mijn droommeisje heb gevonden.",
    "Ik heb geen pick-up line nodig, je hebt me al betoverd.",
    "Je hebt iets gestolen... mijn hart.",
    "Ik dacht dat ik gelukkig was, totdat ik jou ontmoette.",
    "Ben je een engel? Want je bent uit de hemel gevallen.",
    "Ik kan uren naar je kijken zonder me te vervelen.",
    "Ik wist niet dat ik kon verdwalen, totdat ik verdronk in je ogen.",
    "Je hebt een prachtige lach, en ik wil de reden ervoor zijn.",
    "Ik ben geen fotograaf, maar ik kan ons samen wel een mooie toekomst zien.",
    "Kun je me vasthouden? Ik denk dat ik val... voor jou.",
    "Ik ben allergisch voor schoonheid… en nu nies ik de hele tijd!",
    "Mijn horoscoop zei dat ik vandaag de liefde van mijn leven zou ontmoeten. Jij bent dat, toch?",
    "Zijn we al getrouwd in een ander leven?",
    "Als je een lied was, zou ik je op repeat zetten.",
    "Je hebt mijn hart gestolen, mag ik het terugkrijgen met een kus?",
    "Ik moet een kaart hebben, want ik ben verdwaald in je ogen.",
    "Kan ik je hand even vasthouden? Ik wil kijken hoe engelen voelen.",
    "Mijn hart slaat sneller als ik bij je ben.",
    "Ben jij de zon? Want je verlicht mijn dag.",
    "Ik weet niet wat mooier is: de sterrenhemel of jouw lach.",
    "Mag ik je naam? Ik wil de kerstman vertellen wat ik wil voor Kerstmis.",
    "Ik wil de reden zijn waarom je lacht elke ochtend.",
    "Ik hoop dat je geen GPS nodig hebt, want ik wil je nooit verliezen.",
    "Jij bent de enige reden dat ik in sprookjes geloof.",
    "Als ik je zie, vergeet ik mijn tekst.",
    "Ben je een schilder? Want je hebt mijn hart geschilderd met liefde.",
    "Je hebt iets speciaals... een stukje van mijn hart.",
    "Zijn je ouders bakkers? Want je bent een zoet taartje.",
    "Ik wilde een zinvolle conversatie, maar toen zag ik je en vergat alles.",
    "Mijn hart zingt een lied elke keer dat ik jou zie.",
    "Wil je mijn persoonlijke zonnestraal zijn?",
    "Jouw lach is als koffie in de ochtend, het maakt alles beter.",
    "Ik zou alles doen om je gelukkig te zien.",
    "Laten we samen verdwalen in de magie van de liefde.",
    "Ik ben geen genie, maar ik kan je drie wensen vervullen.",
    "Als je in mijn hart zou kijken, zou je alleen jouw naam zien.",
    "Ik geloof in het lot, want het bracht me naar jou.",
    "Ben jij een droom? Want ik wil nooit wakker worden.",
    "Jij maakt mijn wereld compleet.",
    "Als liefde een taal was, zou ik vloeiend spreken met jou.",
    "Je hebt een speciale plaats in mijn hart, en dat zal altijd zo blijven.",
    "Je hebt mijn hart veroverd zonder enige moeite.",
    "Als je een ster was, zou je de helderste in de hemel zijn.",
    "Ik zou liever in je armen zijn dan ergens anders op de wereld.",
    "Mijn liefde voor jou is als een roos die nooit verwelkt.",
    "Ik hou van de manier waarop je lacht, het is aanstekelijk.",
    "Elke keer als ik je zie, slaat mijn hart een slag over.",
    "Wil je samen met mij het mooiste liefdesverhaal schrijven?",
    "Mijn liefde voor jou groeit elke dag.",
    "Als ik in je ogen kijk, zie ik mijn toekomst.",
    "Mijn hart danst op het ritme van jouw liefde.",
    "Je bent de reden waarom mijn wereld kleurrijk is.",
    "Liefde is mooi, maar met jou is het magisch.",
    "Wil je mijn prins(es) op het witte paard zijn?",
    "Als ik jou zie, vergeet ik al mijn zorgen.",
    "Ik geloof niet in perfectie, maar jij komt heel dicht in de buurt.",
    "Je bent niet alleen mooi van buiten, maar ook van binnen.",
    "Jij bent het mooiste hoofdstuk in mijn levensverhaal.",
    "Mijn hart is alleen voor jou gereserveerd.",
    "Als ik je lach zie, kan ik niet anders dan me gelukkig voelen.",
    "Jij bent als een warme zomerbries, verfrissend en betoverend.",
    "Je hebt een speciaal plekje in mijn hart, en niemand anders kan dat innemen.",
    "Wil je samen verdwalen in een wereld vol liefde?",
    "Je glimlach verlicht zelfs de donkerste dagen.",
    "Ik ben geen dichter, maar jij inspireert mij tot mooie woorden.",
    "Ben jij een regenboog? Want je maakt mijn wereld kleurrijk.",
    "Je maakt mijn hart sneller kloppen en mijn hoofd duizelen.",
    "Jij bent de melodie die mijn hart zingt.",
    "Ben je een magiër? Want elke keer als ik je zie, verdwijnt al mijn verdriet.",
    "Ik hoef geen sprookjes, jij bent mijn happy ending.",
    "Jouw stem is als een liefdesliedje dat ik nooit moe word.",
    "Ik heb mijn geluk gevonden… en dat ben jij.",
    "Als liefde een kunst is, ben jij mijn meesterwerk.",
    "Je bent als een droom waaruit ik nooit wakker wil worden.",
    "Je bent de mooiste verrassing die het leven me ooit heeft gegeven.",
]

advance = [
    "Jij bent als een goed boek, elke pagina die ik omsla, maakt me meer verliefd.",
    "Als ik een dichter was, zou ik sonnetten over je schrijven, maar zelfs poëzie zou je schoonheid niet recht doen.",
    "Je ogen hebben een diepte waarin ik mezelf keer op keer wil verliezen.",
    "Ik heb wetenschappelijk bewijs nodig om te bewijzen dat je niet een engel bent die uit de hemel is gevallen.",
    "Je lach is niet alleen mooi, het is de symfonie die mijn hart dirigeert.",
    "Als kusjes woorden waren, zou ik je een roman sturen.",
    "Jouw aanwezigheid voelt als een zachte bries op een warme zomerdag – verfrissend en verslavend.",
    "Ik zou de tijd willen stilzetten wanneer ik bij jou ben, zodat dit moment nooit eindigt.",
    "Jij bent als een zeldzame ster, schitterend en onmogelijk te negeren.",
    "Mijn hart spreekt een taal die alleen jij begrijpt.",
    "Liefde op het eerste gezicht? Nee, het is liefde bij elke blik die ik op jou werp.",
    "Als perfectie een naam had, zou het die van jou zijn.",
    "Elke seconde zonder jou voelt als een verloren moment van geluk.",
    "Je ogen zijn als de oceaan – diep, mysterieus en ik verdwaal er graag in.",
    "Jouw stem is als een liefdesmelodie die ik telkens opnieuw wil horen.",
    "Jij en ik, we zijn geen toevallige ontmoeting; we zijn een verhaal dat het universum heeft geschreven.",
    "Ik heb je niet nodig om mijn wereld compleet te maken, maar met jou is alles zoveel mooier.",
    "Ik wil niet alleen je verleden kennen, maar ook deel uitmaken van je toekomst.",
    "Jij bent als een schilderij van een meester: tijdloos en onbetaalbaar.",
    "Elke keer dat je lacht, breek je de wetten van de natuurkunde, want mijn hart slaat over.",
    "Als we ooit verdwalen, wil ik alleen verdwaald zijn in jouw ogen.",
    "Je hebt een energie die sterker is dan zwaartekracht – ik word onvermijdelijk naar je toe getrokken.",
    "Ik zou zelfs in de regen wachten, als ik wist dat jij degene was die kwam.",
    "Ik wil je hand vasthouden, niet alleen vandaag, maar voor de rest van mijn leven.",
    "Ik ken veel talen, maar de mooiste is de taal van jouw liefde.",
    "Ben jij een tijdreiziger? Want elke keer als ik bij je ben, verlies ik alle besef van tijd.",
    "Elke seconde zonder jou is als een lied zonder melodie – leeg en betekenisloos.",
    "Als je een parfum was, zou ik je voor altijd dragen.",
    "Je bent als een verslaving waarvoor ik geen genezing wil.",
    "Jouw liefde is als de wind: ik kan het niet zien, maar ik voel het in alles wat ik doe.",
    "Elke keer als ik je zie, wordt mijn wereld iets kleurrijker.",
    "Jouw aanwezigheid in mijn leven voelt als een mooi gedicht – ritmisch, betekenisvol en vol emotie.",
    "Je hebt geen toverstok nodig, want je hebt me al betoverd.",
    "Je lach is als een vuurwerkshow – magisch en onvergetelijk.",
    "Jouw liefde is als een onuitgesproken gedicht dat ik keer op keer wil lezen.",
    "Ik ben misschien geen astronaut, maar ik zweef als ik bij jou ben.",
    "Ik heb geen kompas nodig, want mijn hart leidt me altijd naar jou.",
    "Als liefde een schilderij was, zou jij de mooiste kleuren zijn.",
    "Jij bent als een sterrenhemel: adembenemend en mysterieus.",
    "Ik zou graag een pagina in je dagboek zijn, zodat ik elke dag dicht bij je kon zijn.",
    "Jouw ogen weerspiegelen een wereld die ik voor altijd wil verkennen.",
    "Ik heb geen wens nodig, want mijn wens is al uitgekomen – jij.",
    "Je aanwezigheid is als een gedicht dat mijn ziel raakt op manieren die woorden niet kunnen uitleggen.",
    "Je hoeft me geen kaart te geven – mijn hart kent de weg naar jou al uit het hoofd.",
    "Ik hoef geen kaarsen, want jouw liefde verlicht mijn wereld.",
    "Als jij een droom was, zou ik nooit wakker willen worden.",
    "Jij hebt iets dat niemand anders heeft – mijn hart.",
    "Ik zou kilometers lopen, alleen om even bij je te zijn.",
    "Jouw liefde is als een lied dat ik op repeat zet.",
    "Je hebt een glimlach die zelfs de donkerste dagen verlicht.",
    "Als je een bloem was, zou ik je nooit plukken – ik zou gewoon elke dag van je schoonheid genieten.",
    "Als je me één kus gaf voor elke keer dat ik aan je dacht, zou ik voor altijd bij je blijven.",
    "Ik zou duizend woorden kunnen zeggen, maar geen van hen zou je schoonheid echt beschrijven.",
    "Ik wil niet de wereld voor je veranderen, ik wil je gewoon laten zien hoe mooi de wereld met jou is.",
    "Elke minuut zonder jou is een minuut te lang.",
    "Je bent als een zachte bries op een hete zomerdag – perfect en verfrissend.",
    "Mijn liefde voor jou is als een oceaan – diep, oneindig en ondoorgrondelijk.",
    "Je hebt een manier om mijn dag beter te maken zonder iets te zeggen.",
    "Jouw liefde voelt als thuiskomen na een lange reis.",
    "Als ik je zie, voel ik iets dat woorden niet kunnen beschrijven.",
    "Je bent niet alleen mooi, je bent betoverend.",
    "Jij bent het begin van elk gedicht dat ik wil schrijven.",
    "Als jouw liefde een schilderij was, zou het een meesterwerk zijn.",
    "Je bent als een lied waarvan de melodie nooit uit mijn hoofd gaat.",
    "Elke seconde met jou voelt als een eeuwigheid van geluk.",
    "Jouw glimlach is het mooiste geschenk dat ik elke dag kan ontvangen.",
    "Als ik je zie, vergeet ik alles om me heen.",
    "Jij bent de droom die ik nooit wil vergeten.",
    "Ik ben geen dichter, maar jij inspireert me om poëzie te schrijven.",
    "Jouw liefde is als een sterrenregen – magisch en zeldzaam.",
    "Elke keer dat ik je zie, realiseer ik me dat schoonheid echt bestaat.",
    "Je hebt een manier om mijn hart sneller te laten kloppen zonder iets te zeggen.",
    "Ik zou een miljoen keer ‘ik hou van je’ kunnen zeggen en het zou nog steeds niet genoeg zijn.",
    "Je bent als een boek dat ik nooit wil sluiten.",
    "Als liefde een kunstwerk was, zou jij de Mona Lisa zijn.",
    "Je hebt een schoonheid die tijdloos is.",
    "Ik wil je niet alleen vandaag, ik wil je voor altijd.",
    "Als ik één wens mocht doen, zou ik wensen dat jij voor altijd bij me bleef.",
    "Je bent als een perfecte melodie die in mijn hoofd blijft hangen.",
    "Ik heb geen dromen meer nodig, want jij bent mijn mooiste werkelijkheid.",
    "Jij bent de reden waarom ik in liefde geloof.",
    "Als jouw liefde een sprookje was, zou ik nooit het einde willen lezen.",
    "Je hebt een hart dat mooier is dan alle sterren aan de hemel.",
]

nl_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
