simple = [
    "Czy bolało, gdy spadłaś z nieba?",
    "Jesteś jak magnes, przyciągasz mnie do siebie.",
    "Twoje oczy błyszczą jaśniej niż gwiazdy.",
    "Czy masz mapę? Bo zgubiłem się w Twoich oczach.",
    "Jesteś jak kawa – gorąca i uzależniająca.",
    "Czy możemy zrobić razem zdjęcie? Chcę pokazać Mikołajowi, czego sobie życzę na święta.",
    "Czy jesteś czarownicą? Bo zaczarowałaś moje serce.",
    "Jesteś jak sen, którego nie chcę się budzić.",
    "Jesteś jak słońce, rozświetlasz mój dzień.",
    "Twoje imię powinno być Google, bo masz wszystko, czego szukam.",
    "Czy wierzysz w miłość od pierwszego wejrzenia, czy mam przejść obok jeszcze raz?",
    "Masz może plaster? Bo właśnie przewróciłem się na twój widok.",
    "Twoje oczy są jak ocean, mogę w nich utonąć.",
    "Czy jesteś aniołem? Bo wyglądasz nieziemsko.",
    "Gdyby piękno było czasem, byłabyś wiecznością.",
    "Czy jesteś Wi-Fi? Bo czuję z Tobą silne połączenie.",
    "Nie jestem fotografem, ale mogę nas sobie wyobrazić razem.",
    "Twoje usta muszą być wykonane z miodu, bo nie mogę przestać na nie patrzeć.",
    "Czy masz kompas? Bo właśnie zgubiłem się w Twoim uśmiechu.",
    "Jesteś jak gwiazda – zbyt daleko, by dotknąć, ale zbyt piękna, by oderwać wzrok.",
    "Czy jesteś magikiem? Bo zawsze, gdy na Ciebie patrzę, cały świat znika.",
    "Twoja uroda sprawia, że zapominam o wszystkich problemach.",
    "Czy możemy zrobić razem zdjęcie? Bo chcę pokazać swoim znajomym, że anioły istnieją.",
    "Jesteś jak książka, której nie mogę przestać czytać.",
    "Czy możesz mnie przytulić? Mówią, że to najlepsze lekarstwo na smutek.",
    "Czy masz ogień? Bo właśnie rozpaliłaś moje serce.",
    "Jesteś jak wino – im dłużej Cię znam, tym bardziej mnie zachwycasz.",
    "Czy mogę Cię zaprosić na kolację? Bo czuję, że mamy dużo do omówienia.",
    "Czy masz lustro w kieszeni? Bo widzę w nim anioła.",
    "Czy mogę Cię pocałować? Czy mam poczekać na magiczny moment?",
    "Twój uśmiech jest jak promień słońca w pochmurny dzień.",
    "Jesteś jak muzyka – każda chwila z Tobą brzmi idealnie.",
    "Czy masz sekundę? Bo właśnie straciłem serce na Twój widok.",
    "Jeśli piękno byłoby przestępstwem, dostałabyś dożywocie.",
    "Twoja obecność sprawia, że świat staje się piękniejszy.",
    "Czy możemy zatańczyć? Bo moje serce już bije w Twoim rytmie.",
    "Jesteś jak poezja – każda chwila z Tobą jest rymem do szczęścia.",
    "Czy wiesz, że masz coś, czego nikt inny nie ma? Mój uśmiech tylko dla Ciebie.",
    "Gdybyś była snem, nigdy nie chciałbym się obudzić.",
    "Czy masz mapę? Bo zgubiłem się w Twoim uśmiechu.",
    "Czy masz imię, czy mogę nazywać Cię swoją miłością?",
    "Czy mogę pożyczyć Twój telefon? Chcę zadzwonić do mamy i powiedzieć, że właśnie spotkałem miłość mojego życia.",
    "Jesteś jak lato – ciepła, promienna i pełna życia.",
    "Twoje spojrzenie to magia, która kradnie moje serce.",
    "Nie mogę uwierzyć, że anioły chodzą po ziemi.",
    "Jesteś tak piękna, że zapomniałem, co chciałem powiedzieć.",
    "Czy chcesz być moją gwiazdą przewodnią?",
    "Twój uśmiech sprawia, że czuję się jak w niebie.",
    "Nie potrzebuję cukru do herbaty – wystarczy mi Twój słodki uśmiech.",
    "Czy mogę być Twoim cieniem? Bo nie chcę się od Ciebie oddalać.",
    "Czy możemy przejść na Ty, czy wolisz, żebym mówił do Ciebie 'moja miłości'?",
    "Jesteś jak diament – rzadki, piękny i niepowtarzalny.",
    "Czy mogę Cię trzymać za rękę? Chcę zobaczyć, czy anioły są prawdziwe.",
    "Jesteś moim szczęściem w ludzkiej postaci.",
    "Nie jestem poetą, ale każda chwila z Tobą to najpiękniejszy wiersz.",
    "Jesteś jak melodia, która gra w moim sercu bez przerwy.",
    "Czy mogę Cię zaprosić na spacer? Chciałbym dłużej podziwiać Twój uśmiech.",
    "Masz w sobie coś, co sprawia, że zapominam o całym świecie.",
    "Gdyby miłość była sztuką, Ty byłabyś arcydziełem.",
    "Jesteś jak kawa – gorąca i dodajesz mi energii.",
    "Czy możemy zamienić kilka słów, zanim ukradniesz moje serce na zawsze?",
    "Czy możesz się do mnie uśmiechnąć? Chcę zobaczyć, jak wygląda szczęście.",
    "Jesteś jak wiosna – świeża, piękna i pełna życia.",
    "Czy mogę być Twoim księżycem, jeśli Ty będziesz moim słońcem?",
    "Jeśli uśmiech byłby walutą, byłabyś najbogatszą osobą na świecie.",
    "Jesteś jak magia – nie mogę przestać o Tobie myśleć.",
    "Twój śmiech to najpiękniejsza melodia, jaką kiedykolwiek słyszałem.",
    "Czy jesteś z cukru? Bo słodkość w Tobie jest niesamowita.",
    "Nie wiem, co jest piękniejsze – Twoje oczy czy Twój uśmiech.",
    "Czy możemy razem napisać historię pełną miłości?",
    "Jesteś jak promień słońca w deszczowy dzień.",
    "Czy wiesz, że każda sekunda z Tobą to najpiękniejszy moment mojego dnia?",
    "Nie potrzebuję gwiazd, bo Twoje oczy świecą jaśniej.",
    "Czy mogę być Twoim kompasem? Bo chcę prowadzić Cię do szczęścia.",
    "Gdyby czas zatrzymał się w chwili, kiedy Cię widzę, chciałbym, żeby trwało to wiecznie.",
    "Jesteś jak najpiękniejszy sen, który stał się rzeczywistością.",
]

advance = [
    "Czy Twoje serce ma miejsce na sublokatora? Bo chętnie się wprowadzę.",
    "Jesteś jak sztuka współczesna – nie wszyscy rozumieją, ale ja nie mogę oderwać wzroku.",
    "Czy masz w sobie grawitację? Bo nie mogę się od Ciebie oderwać.",
    "Nie jestem fizykiem, ale przyciąganie między nami jest niewiarygodne.",
    "Twoje oczy są jak czarne dziury – przyciągają i pochłaniają całe moje myśli.",
    "Czy jesteś hasłem do mojego Wi-Fi? Bo czuję, że łączysz mnie z czymś niesamowitym.",
    "Jesteś jak dobra książka – im dłużej Cię znam, tym trudniej mi się od Ciebie oderwać.",
    "Czy jesteś krawcem? Bo właśnie zszyłaś moje złamane serce.",
    "Jesteś jak najtrudniejsza zagadka matematyczna – fascynujesz i nie dajesz mi spokoju.",
    "Gdyby moje serce było aplikacją, to Ty byłabyś jego najnowszą aktualizacją.",
    "Nie jestem poetą, ale każda chwila z Tobą to gotowy wiersz miłosny.",
    "Czy możemy stworzyć razem równanie miłości? Bo czuję, że jesteśmy idealnym rozwiązaniem.",
    "Czy jesteś błyskiem w aparacie? Bo sprawiasz, że moje serce przyspiesza na Twój widok.",
    "Czy jesteś kompozytorem? Bo Twoje słowa grają na moich emocjach jak najpiękniejsza symfonia.",
    "Twoja obecność to jak efekt motyla – wystarczy jeden uśmiech, a mój świat się zmienia.",
    "Czy masz magiczną różdżkę? Bo za każdym razem, gdy się uśmiechasz, znikają wszystkie moje troski.",
    "Twoje imię powinno być hashtagiem, bo chcesz być w każdej mojej myśli.",
    "Gdyby moje serce było komputerem, Ty byłabyś jego jedynym procesem działającym w tle.",
    "Nie jesteś cukierkiem, ale i tak jesteś najsłodszą rzeczą, jaką widziałem.",
    "Jesteś jak dobra kawa – pobudzasz mnie i sprawiasz, że czuję się szczęśliwy.",
    "Czy wiesz, że Twoje spojrzenie ma więcej mocy niż cała elektrownia?",
    "Czy jesteś kryptografem? Bo tylko Ty możesz rozszyfrować kod mojego serca.",
    "Twoje oczy są jak dwie gwiazdy neutronowe – gęste od tajemnic i nieodparcie przyciągające.",
    "Gdyby miłość była melodią, to Ty byłabyś jej najpiękniejszym refrenem.",
    "Jesteś jak portal do innego wymiaru – patrzę na Ciebie i zapominam o wszystkim innym.",
    "Czy możemy zrobić eksperyment? Chciałbym sprawdzić, czy Twoje usta rzeczywiście smakują jak marzenie.",
    "Czy masz swoją własną grawitację? Bo przyciągasz mnie z siłą, której nie potrafię się oprzeć.",
    "Nie potrzebuję latarki – wystarczy Twój uśmiech, który rozjaśnia każdy mój dzień.",
    "Jesteś jak droga mleczna – w Tobie widzę cały wszechświat.",
    "Gdybyś była kodem źródłowym, byłabyś perfekcyjnie zoptymalizowana pod kątem mojego serca.",
    "Nie jestem astrologiem, ale wszystkie gwiazdy mówią, że jesteś moim przeznaczeniem.",
    "Jeśli miłość była językiem programowania, to Ty byłabyś moją główną funkcją.",
    "Czy jesteś aplikacją w chmurze? Bo zawsze jesteś w moich myślach, niezależnie od miejsca.",
    "Twoje spojrzenie to jak aktualizacja oprogramowania – wszystko działa lepiej, gdy Cię widzę.",
    "Czy mogę zapamiętać Twój uśmiech na zawsze, czy muszę go sobie zapisywać w sercu co sekundę?",
    "Czy wiesz, że każda sekunda bez Ciebie to kod, który się nie kompiluje?",
    "Jesteś jak najlepszy algorytm – zawsze prowadzący do szczęśliwego zakończenia.",
    "Czy mogę Cię przytulić? Chcę sprawdzić, czy moje serce nadal bije po takim uderzeniu piękna.",
    "Jesteś jak idealny kod – nie ma w Tobie błędów, a ja ciągle chcę Cię analizować.",
    "Gdyby Twoje imię było w słowniku, obok niego byłoby napisane: 'definicja doskonałości'.",
    "Czy mogę zaktualizować Twój status? Bo chciałbym być Twoją jedyną aplikacją miłosną.",
    "Jesteś jak najpiękniejsza biblioteka w Pythonie – bez Ciebie mój kod (życie) nie działa.",
    "Czy jesteś teorią względności? Bo czas zwalnia, gdy jesteś blisko.",
    "Czy jesteś symfonią? Bo Twoja obecność komponuje najpiękniejszą melodię w moim sercu.",
    "Jesteś jak najwyższy poziom zabezpieczeń – nikt poza mną nie powinien mieć do Ciebie dostępu.",
    "Twoje usta to jak zmienna w kodzie – każda myśl krąży wokół ich wartości.",
    "Czy jesteś czarną dziurą? Bo pochłaniasz całe moje serce.",
    "Nie jestem grafikiem, ale chcę stworzyć z Tobą najpiękniejszy obraz miłości.",
    "Twoje oczy to jak interfejs użytkownika – intuicyjne, piękne i sprawiają, że czuję się wyjątkowo.",
    "Jesteś jak najlepsza wersja oprogramowania – nigdy nie potrzebujesz aktualizacji, bo jesteś doskonała.",
    "Gdybym mógł wybrać supermoc, chciałbym zatrzymywać czas, by każda chwila z Tobą trwała wiecznie.",
    "Czy mogę być Twoim menedżerem zadań? Bo chcę, by Twoje myśli skupiały się tylko na mnie.",
    "Czy jesteś wtyczką do mojego życia? Bo bez Ciebie nic nie działa tak, jak powinno.",
    "Jesteś jak idealny startup – obiecująca, wyjątkowa i sprawiasz, że chcę w Ciebie inwestować całe swoje serce.",
    "Czy mogę być Twoim hasłem? Bo tylko Ty powinnaś mnie znać i używać.",
    "Nie jestem hakerem, ale właśnie włamałaś się do mojego serca.",
    "Czy możemy założyć startup miłości? Mam pomysł na coś wyjątkowego – nas dwoje.",
    "Jesteś jak najlepszy model AI – im więcej Cię poznaję, tym bardziej mnie zachwycasz.",
    "Gdybyś była wersją beta, nigdy bym nie chciał aktualizacji.",
    "Czy Twoje imię to kod źródłowy? Bo ciągle chcę je analizować.",
    "Czy wiesz, że gdybyś była systemem operacyjnym, wybrałbym tylko Ciebie?",
]

pl_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
