simple = [
    "Você acredita em amor à primeira vista ou devo passar por aqui de novo?",
    "Se beleza fosse tempo, você seria a eternidade.",
    "Posso te emprestar um beijo? Prometo devolver.",
    "Seu nome é Wi-Fi? Porque sinto uma conexão entre nós.",
    "Se eu fosse um gato, passaria todas as minhas vidas com você.",
    "Aposto que seu pai é padeiro, porque você é um sonho.",
    "Se você fosse um legume, seria um doce de batata.",
    "Seu sorriso ilumina meu dia mais que o sol.",
    "Você não é Google, mas tem tudo que eu procuro.",
    "Meu coração bate mais rápido sempre que vejo você.",
    "Se eu pudesse rearranjar o alfabeto, colocaria U e I juntos.",
    "Você não é um dicionário, mas dá significado à minha vida.",
    "Você deve ser mágico(a), porque sempre que te vejo, o mundo desaparece.",
    "Se beijos fossem flocos de neve, eu te daria uma nevasca.",
    "Seu sorriso deveria ser ilegal, porque é viciante.",
    "Se o amor fosse um crime, eu estaria preso por te amar tanto.",
    "Posso te seguir para casa? Meu coração se perdeu nos seus olhos.",
    "Você tem um mapa? Porque me perdi no brilho dos seus olhos.",
    "Se você fosse uma música, seria minha favorita.",
    "Você roubou meu coração, posso pegar de volta com um beijo?",
    "Se eu tivesse uma estrela para cada vez que penso em você, teria uma galáxia.",
    "Você é tão doce que diabéticos precisam te evitar.",
    "Se beleza fosse um crime, você estaria na prisão perpétua.",
    "Se você fosse um café, seria o mais doce e forte.",
    "O que uma estrela do mar e eu temos em comum? Ambos estamos caídos por você.",
    "Se você fosse uma flor, seria a mais bela do jardim.",
    "Você tem um espelho no bolso? Porque vejo meu futuro nos seus olhos.",
    "Me chama de relógio e diz que você não vive sem mim.",
    "Você é como Wi-Fi, porque sinto sua falta quando estou longe.",
    "Se você fosse uma rede social, seria a que mais gosto de seguir.",
    "Se cada estrela fosse um motivo para te amar, o céu estaria cheio.",
    "Você tem um GPS? Porque cada caminho me leva até você.",
    "Eu não sou fotógrafo, mas posso capturar seu coração?",
    "Se você fosse uma cor, seria a mais vibrante de todas.",
    "Você é mais quente que um café recém-feito.",
    "Você é feita de açúcar? Porque sua doçura é irresistível.",
    "Eu poderia viver sem você, mas não seria a mesma coisa.",
    "Você me fez acreditar que contos de fadas são reais.",
    "Se eu fosse um zumbi, te amaria pelo seu cérebro e coração.",
    "O céu roubou suas estrelas para colocar nos seus olhos.",
    "Se amar fosse um jogo, eu estaria ganhando ao seu lado.",
    "Me chama de novela, porque quero estar na sua rotina diária.",
    "Você é como um arco-íris, porque ilumina os dias mais cinzentos.",
    "Você deve ser um anjo, porque só pode ter caído do céu.",
    "Se meu coração fosse uma bateria, estaria sempre carregado por você.",
    "Me empresta um sorriso? O meu se perdeu no seu olhar.",
    "Eu queria ser uma lágrima, para nascer nos seus olhos e morrer nos seus lábios.",
    "Você é como um sonho do qual nunca quero acordar.",
    "Se cada suspiro meu fosse um beijo, você estaria coberta deles.",
    "Você é mais doce que brigadeiro.",
    "Eu te amaria até se você fosse um cactus, porque sou forte.",
    "Seu olhar tem o poder de parar o tempo.",
    "Se você fosse uma tempestade, eu enfrentaria sem guarda-chuva.",
    "Seu sorriso ilumina até os dias mais nublados.",
    "Você é como um presente que nunca para de surpreender.",
    "Acho que sou um detector de metais, porque fui atraído(a) pelo seu brilho.",
    "Posso ser seu guarda-chuva? Para te proteger da tristeza.",
    "Se eu fosse um astronauta, exploraria sua galáxia.",
    "Você é como um doce, impossível de resistir.",
    "Se eu pudesse escolher um superpoder, seria te fazer feliz para sempre.",
    "Você é mais encantador(a) que um pôr do sol à beira-mar.",
    "Você é a resposta para todas as minhas perguntas.",
    "Meu coração bate no ritmo do seu sorriso.",
    "Se você fosse um enigma, eu passaria a vida tentando decifrar.",
    "Seu amor é a melhor música que já ouvi.",
    "Me chama de café e diz que não vive sem mim.",
    "Se você fosse um feitiço, eu estaria completamente encantado.",
    "Acho que preciso de óculos, porque não consigo tirar os olhos de você.",
    "Se você fosse um doce, seria aquele que nunca enjoa.",
    "Você é como uma constelação, porque ilumina meu céu.",
    "Se eu pudesse ser um objeto, seria um cobertor para te abraçar sempre.",
    "Você é como uma poesia que nunca canso de ler.",
    "Se eu fosse um livro, minha história favorita seria sobre nós.",
    "Você é como um fogo que aquece meu coração.",
    "Se seu sorriso fosse uma melodia, eu escutaria em loop.",
    "Você é um sonho que nunca quero parar de sonhar.",
    "Se seu olhar fosse um oceano, eu mergulharia para sempre.",
    "Você é como o sol, sempre iluminando meu mundo.",
    "Se eu fosse uma estrela, escolheria brilhar ao seu lado.",
    "Você me faz acreditar que a felicidade tem nome.",
    "Se seu amor fosse um idioma, seria minha língua materna.",
    "Você tem um lugar VIP no meu coração.",
    "Se amar você fosse uma profissão, eu trabalharia sem folga.",
    "Se você fosse um sorvete, eu te provaria todos os dias.",
    "Seus olhos têm a cor exata do meu destino.",
    "Você é o motivo pelo qual o amor foi inventado.",
    "Se seu abraço fosse um lugar, eu nunca mais sairia.",
    "Você me faz acreditar que almas gêmeas existem.",
    "Se você fosse uma joia, seria a mais rara e preciosa.",
    "Você é minha notificação favorita da vida.",
    "Se amor fosse um jogo, eu escolheria você para ser meu time.",
    "Você ilumina meu mundo como fogos de artifício no céu noturno.",
    "Se eu fosse um pintor, sua beleza seria minha obra-prima.",
]

advance = [
    "Se você fosse um código, seria o algoritmo perfeito para otimizar minha felicidade.",
    "Meu amor por você é como um loop infinito: nunca termina.",
    "Se beleza fosse energia, você iluminaria o universo inteiro.",
    "Se os átomos vibram com energia, é impossível não vibrar ao seu lado.",
    "Sua presença é como uma API bem documentada: clara, eficiente e indispensável.",
    "Se eu pudesse armazenar meu amor por você, precisaria de um disco infinito.",
    "Você é como um bug raro: impossível de encontrar e difícil de esquecer.",
    "Me chama de Wi-Fi e diz que sente minha falta quando estou longe.",
    "Se você fosse um algoritmo, seria O(1) para encontrar meu coração.",
    "Sua beleza é um banco de dados relacional: estruturada, organizada e impossível de não consultar.",
    "Se paixão fosse uma variável, você seria meu valor constante.",
    "Eu não sou programador de IA, mas meu coração só responde a você.",
    "Se minha vida fosse um código, você seria o import mais importante.",
    "Você é como um firewall: ninguém entra no meu coração sem passar por você.",
    "Me chama de processador e diz que você precisa de mim para funcionar.",
    "Se você fosse um site, seria HTTPS: seguro e confiável.",
    "Eu tentaria te esquecer, mas meu cache emocional não permite.",
    "Você é como um framework moderno: facilita tudo e deixa tudo mais bonito.",
    "Você deve ser um QR Code, porque basta um olhar para eu querer te decifrar.",
    "Seu amor é um banco de dados NoSQL: flexível e sempre se adaptando às minhas emoções.",
    "Se o amor fosse um sistema operacional, você seria minha versão estável.",
    "Você tem a latência mais baixa entre meu coração e minha felicidade.",
    "Meu amor por você é open-source: pode ser visto, mas só você pode modificar.",
    "Você é o front-end perfeito para a interface do meu coração.",
    "Me chama de kernel e diz que sem mim seu sistema não funciona.",
    "Se meu coração fosse um software, você seria o desenvolvedor principal.",
    "Você não é uma IA, mas me faz pensar que perfeição existe.",
    "Você tem um firewall? Porque é impossível invadir seu coração.",
    "Se minha vida fosse um código, cada linha seria sobre você.",
    "Você é um bug que eu nunca quero corrigir.",
    "Você deve ser um supercomputador, porque meu coração processa rápido demais quando te vê.",
    "Eu tentaria te deletar da minha mente, mas meu sistema não permite.",
    "Você tem uma interface tão intuitiva que meu coração aprendeu a te amar sem esforço.",
    "Você não é um algoritmo de recomendação, mas sempre aparece nos meus pensamentos.",
    "Eu poderia ser um programador sem erros, mas falho toda vez que tento resistir a você.",
    "Você é como um update inesperado, sempre trazendo algo melhor para minha vida.",
    "Se cada vez que penso em você fosse um pixel, eu criaria a imagem mais linda do mundo.",
    "Se seu amor fosse um software pago, eu assinaria para sempre.",
    "Você tem um design responsivo, porque se encaixa perfeitamente em qualquer parte da minha vida.",
    "Você não é um código, mas compila perfeitamente no meu coração.",
    "Se eu fosse um hacker, invadiria seu coração só para nunca mais sair.",
    "Você é meu favorito no repositório de emoções.",
    "Meu amor por você é como um script bem otimizado: rápido, eficiente e sem falhas.",
    "Você é mais viciante que redes sociais e mais necessário que Wi-Fi.",
    "Se amor fosse um app, você seria minha única notificação ativada.",
    "Você tem um layout tão bonito que nenhum designer conseguiria criar algo melhor.",
    "Você é como um update: sempre me surpreende e me faz querer mais.",
    "Você deve ser uma linguagem funcional, porque meu amor por você não tem efeitos colaterais.",
    "Você não é um cookie, mas deixa rastros em tudo que eu faço.",
    "Se amor fosse uma rede neural, você seria o treinamento perfeito.",
    "Seu olhar tem mais resolução que qualquer tela 8K.",
    "Você é como um código limpo: elegante, simples e impossível de não admirar.",
    "Eu tentaria formatar meu coração, mas sei que você sempre estaria na memória.",
    "Seu sorriso é um erro 404: impossível de não notar.",
    "Você é meu commit favorito na história da minha vida.",
    "Se paixão fosse um comando, você seria um loop sem condição de parada.",
    "Se você fosse um pixel, seria a mais nítida definição da perfeição.",
    "Meu coração sem você é como um código sem sintaxe: não funciona.",
    "Você tem um design tão incrível que deveria ganhar um prêmio UX de amor.",
    "Você é um cache que eu nunca quero limpar.",
    "Você não é um algoritmo de criptografia, mas meu coração é totalmente protegido por você.",
    "Se meu amor fosse um patch, ele corrigiria todas as suas inseguranças.",
    "Você é a única variável no código do meu coração.",
    "Eu tentaria depurar meus sentimentos, mas não há erro: eu te amo.",
    "Você é um código minificado: compacto, eficiente e essencial para mim.",
    "Se eu tivesse que escolher entre viver sem internet ou sem você, adeus, Wi-Fi.",
    "Você tem um ping tão rápido no meu coração que não há latência entre meu amor e você.",
    "Se meu amor fosse um deploy, ele rodaria sem falhas em qualquer ambiente.",
    "Você é como um cloud server: sempre presente, confiável e essencial para mim.",
    "Se você fosse um DOM, eu te manipularia com carinho.",
    "Meu coração por você tem a melhor performance de todos os tempos.",
    "Você tem uma interface tão amigável que qualquer um se apaixonaria.",
    "Se amor fosse código, o seu seria perfeitamente indentado no meu coração.",
    "Você tem mais segurança que qualquer firewall, porque protege meu coração.",
    "Seu amor é como um servidor dedicado: só roda para mim.",
    "Você é meu deploy preferido: sempre funcionando perfeitamente.",
    "Você deve ser uma API REST, porque minha vida sem você não faz sentido.",
    "Se você fosse um CSS, estilizaria minha vida de felicidade.",
    "Você é meu framework favorito: fácil de usar e impossível de substituir.",
    "Se o amor fosse um código, você seria meu repositório principal.",
    "Seu olhar é um script que roda sem precisar de permissão.",
    "Você é meu sistema operacional perfeito: confiável, estável e essencial.",
    "Eu tentaria desinstalar você do meu coração, mas o sistema não permite.",
    "Você é um modal que apareceu na minha vida e nunca quero fechar.",
    "Se você fosse um arquivo, seria read-only para qualquer um, menos para mim.",
    "Meu amor por você é como uma função recursiva: sempre volta para você.",
    "Você é o pixel perfeito na tela da minha vida.",
    "Eu tentaria resetar meu coração, mas você sempre estaria na memória RAM do amor.",
    "Você é um bot que automatizou minha felicidade.",
    "Você é uma variável global no código da minha vida.",
    "Se amor fosse JSON, o seu seria sempre bem estruturado.",
    "Você é um componente essencial na minha arquitetura emocional.",
    "Meu amor por você nunca entra em overflow.",
    "Você é um script assíncrono que sempre executa no fundo do meu coração.",
    "Você é a documentação perfeita do que é o amor.",
    "Você não é uma query SQL, mas selecionou meu coração com precisão.",
    "Seu amor é como uma API bem-feita: sempre responde do jeito certo.",
    "Você é um sistema sem bugs, porque é perfeito para mim.",
    "Se minha vida fosse um código, você seria meu main().",
    "Você é um prompt perfeito, porque me faz gerar os melhores sentimentos."
]

pt_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
