simple = [
    "Ești mai frumoasă decât un apus de soare pe malul mării.",
    "Ai furat stelele și le-ai ascuns în ochii tăi?",
    "Când zâmbești, îmi luminezi întreaga zi.",
    "Dacă frumusețea ar fi un păcat, ai fi cea mai mare păcătoasă.",
    "Ai un magnetism irezistibil, mă atragi fără să vrei.",
    "Numele tău trebuie să fie magie, pentru că ai fermecat inima mea.",
    "Dacă aș putea, ți-aș trimite un milion de săruturi în fiecare zi.",
    "O secundă lângă tine valorează mai mult decât o viață întreagă fără tine.",
    "Cum e posibil ca cineva să fie atât de perfect?",
    "Dacă aș avea un bănuț pentru fiecare gând despre tine, aș fi miliardar.",
    "Când mă uit la tine, uit de tot restul lumii.",
    "Ești mai dulce decât ciocolata mea preferată.",
    "Nu am nevoie de soare când ești lângă mine, tu îmi încălzești inima.",
    "Dacă frumusețea ar avea o definiție, ar fi numele tău.",
    "Aș călători până la capătul lumii doar ca să-ți văd zâmbetul.",
    "Ai ochi ca două oceane în care mă pierd mereu.",
    "Dacă aș putea opri timpul, aș păstra acest moment pentru totdeauna.",
    "În fiecare floare văd zâmbetul tău.",
    "Dacă iubirea ar avea un nume, ar fi al tău.",
    "Zâmbetul tău este ca un răsărit de soare într-o zi ploioasă.",
    "Dacă ai fi un vis, nu aș vrea să mă trezesc niciodată.",
    "Aș vrea să fiu motivul pentru care zâmbești în fiecare zi.",
    "Când ești lângă mine, lumea devine un loc mai bun.",
    "Dacă aș putea citi gândurile, aș vrea să știu dacă mă visezi și tu.",
    "Ești mai strălucitoare decât orice stea de pe cer.",
    "Inima mea bate doar pentru tine.",
    "Te-ai născut să fii iubită, iar eu m-am născut să te iubesc.",
    "Ai fost vreodată întrebată dacă ești un înger?",
    "Când sunt cu tine, timpul se oprește.",
    "Dacă aș avea trei dorințe, toate ar fi despre tine.",
    "Mi-ai schimbat lumea doar printr-un singur zâmbet.",
    "Ești dovada vie că perfecțiunea există.",
    "Când mă privești, mă topesc ca un fulg de nea la soare.",
    "Dacă inima mea ar putea vorbi, ți-ar spune cât de mult te iubește.",
    "Nu am nevoie de nimic altceva când te am pe tine.",
    "Aș vrea să te păstrez lângă mine pentru totdeauna.",
    "Când sunt cu tine, uit de tot ce e rău în lume.",
    "Îmi faci inima să bată mai repede de fiecare dată când te văd.",
    "Ești visul meu devenit realitate.",
    "Te iubesc mai mult decât cuvintele pot exprima.",
    "Dacă aș putea să aleg între tine și respirație, aș folosi ultimul suflu să-ți spun că te iubesc.",
    "Ești cel mai frumos cadou pe care viața mi l-a oferit.",
    "Nimic nu este mai important pentru mine decât fericirea ta.",
    "Mi-e dor de tine chiar și când ești lângă mine.",
    "Ești motivul pentru care mă trezesc zâmbind în fiecare dimineață.",
    "Tu ești poezia pe care inima mea o scrie în fiecare zi.",
    "Când ești lângă mine, nu-mi trebuie nimic altceva.",
    "Aș vrea să îți spun ceva frumos, dar frumusețea ta mă lasă fără cuvinte.",
    "Mi-aș da inima întreagă, dar deja e a ta.",
    "Nu ai nevoie de machiaj, frumusețea ta este naturală și unică.",
    "Zâmbetul tău este singura lumină de care am nevoie în întuneric.",
    "Dacă ar exista un concurs de frumusețe pentru suflete, ai fi campioană absolută.",
    "Când mă gândesc la tine, inima îmi bate mai tare.",
    "Mi-aș dori să fiu o lacrimă, să mă nasc în ochii tăi și să mor pe buzele tale.",
    "Tu ești răspunsul la toate rugăciunile mele.",
    "Aș vrea să te țin în brațe și să nu te mai las niciodată.",
    "Aș merge prin foc și apă doar pentru tine.",
    "Fără tine, viața mea ar fi ca o noapte fără stele.",
    "Ochii tăi îmi spun tot ce inima mea vrea să audă.",
    "Mă pierd în frumusețea ta de fiecare dată când te privesc.",
    "Numele tău e scris în inima mea.",
    "Ai făcut ca lumea mea să fie mai frumoasă doar prin simpla ta prezență.",
    "Tu ești piesa lipsă din puzzle-ul inimii mele.",
    "Inima mea nu știa ce înseamnă iubirea până nu te-am întâlnit pe tine.",
    "Tu ești începutul și sfârșitul fiecărei zile pentru mine.",
    "Dacă viața ar fi o melodie, tu ai fi refrenul meu preferat.",
    "Nu vreau nimic altceva decât să fiu lângă tine.",
    "Aș vrea să te fac să râzi în fiecare zi.",
    "Ești mai dulce decât mierea și mai strălucitoare decât aurul.",
    "Dacă frumusețea ar fi artă, tu ai fi capodopera supremă.",
    "Ai fost trimisă pe pământ ca un dar pentru mine.",
    "Când mă gândesc la tine, simt că pot cuceri lumea.",
    "Aș putea să mă uit la tine o veșnicie și tot nu m-aș sătura.",
    "Îți aud vocea în fiecare adiere de vânt.",
    "Dacă te-aș putea ține de mână, nu te-aș mai lăsa niciodată.",
    "Îmi umpli inima cu bucurie doar prin simpla ta existență.",
    "Tu ești definiția perfecțiunii pentru mine.",
    "Aș vrea să îți șoptesc la ureche toate gândurile mele frumoase despre tine.",
    "Dacă aș putea, ți-aș picta chipul pe cer.",
    "Mă pierd în ochii tăi și nu vreau să fiu găsit.",
    "Te iubesc mai mult decât luna iubește stelele.",
    "Tu ești motivul pentru care cred în dragoste.",
    "Ești cea mai frumoasă poveste pe care vreau să o trăiesc.",
]

advance = [
    "Dacă ar exista o hartă a inimii mele, numele tău ar fi marcat în centrul ei.",
    "Privirea ta este un labirint din care nu vreau să găsesc ieșirea.",
    "Dacă iubirea ar fi o artă, tu ai fi capodopera supremă.",
    "Când îți aud vocea, simt că toată simfonia universului cântă doar pentru mine.",
    "Ești precum un poem scris de stele pe cerul infinit al sufletului meu.",
    "Dacă dragostea mea pentru tine ar fi o carte, nu ar exista destule pagini să o cuprindă.",
    "Fiecare secundă lângă tine este un vers într-o poezie nesfârșită a iubirii.",
    "Ești singura ecuație pe care inima mea vrea să o rezolve pentru totdeauna.",
    "Tu nu ești doar o stea pe cer, ești întregul univers în ochii mei.",
    "Dacă frumusețea ar avea un ecou, glasul tău ar fi cântecul eternității.",
    "Ești combinația perfectă între mister și magie, iar eu sunt captivat fără scăpare.",
    "Când mă uit la tine, văd un viitor pictat în cele mai frumoase culori ale iubirii.",
    "Dacă timpul s-ar opri de fiecare dată când mă gândesc la tine, am trăi o eternitate împreună.",
    "Ești dovada vie că perfecțiunea nu este doar un ideal, ci o realitate palpabilă.",
    "Când te privesc, sufletul meu dansează pe ritmul inimii tale.",
    "Fiecare cuvânt pe care îl rostești este o melodie pe care vreau să o ascult toată viața.",
    "Dacă iubirea mea pentru tine ar fi o galaxie, ai fi soarele în jurul căruia gravitează toate stelele mele.",
    "Tu nu ești doar visul meu, ci realitatea pe care mi-am dorit-o dintotdeauna.",
    "Ai transformat lumea mea într-un basm din care nu vreau să mă trezesc niciodată.",
    "Dacă aș fi un pictor, fiecare tablou ar fi o încercare disperată de a-ți surprinde frumusețea.",
    "Când îți aud numele, inima mea bate într-un ritm pe care doar tu îl poți înțelege.",
    "Dacă iubirea mea pentru tine ar avea o formă, ar fi un ocean fără sfârșit.",
    "Tu ești singura variabilă pe care o accept în ecuația fericirii mele.",
    "Ești punctul culminant al fiecărui gând romantic pe care îl am.",
    "Dacă inima mea ar putea vorbi, ar șopti numele tău la nesfârșit.",
    "Ești ca o stea căzătoare – rară, spectaculoasă și capabilă să îndeplinești dorințe.",
    "Nu există niciun algoritm care să descrie frumusețea și farmecul tău.",
    "Dacă dragostea mea pentru tine ar fi o poveste, ar fi una fără sfârșit.",
    "Ești energia care îmi alimentează fiecare vis și speranță.",
    "Te iubesc într-un mod pe care nici măcar poezia nu îl poate exprima complet.",
    "Ochii tăi sunt ca două portaluri către o lume unde totul este perfect.",
    "Tu nu ești doar o prezență în viața mea, ești însăși esența fericirii mele.",
    "Dacă inima mea ar avea un limbaj propriu, fiecare cuvânt ar fi despre tine.",
    "Ești acea melodie pe care vreau să o ascult în fiecare zi, pentru tot restul vieții.",
    "Mă fascinezi mai mult decât orice carte pe care am citit-o vreodată.",
    "Tu ești răsăritul și apusul inimii mele, ziua și noaptea sufletului meu.",
    "Ești ca un vers nescris, dar perfect simțit în inima mea.",
    "Dacă iubirea ar fi un univers, atunci noi am fi galaxia cea mai strălucitoare.",
    "Tu nu ești doar un vis, ești realitatea mea preferată.",
    "Când ești lângă mine, timpul devine o iluzie, iar iubirea – singura realitate.",
    "Ești precum o constelație unică pe cerul existenței mele.",
    "Dacă aș putea trăi într-un singur moment, l-aș alege pe cel în care",
]

ro_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
