simple = [
    "Si taká krásna, že mi vyrážaš dych.",
    "Máš úsmev, ktorý dokáže rozžiariť aj najtmavšiu noc.",
    "Si ako magnet a ja sa k tebe stále priťahujem.",
    "Keby som mal jednu želanie, bolo by to stráviť večnosť s tebou.",
    "Si sladšia ako med.",
    "Tvoj hlas je pre moje uši najkrajšia melódia.",
    "Si dôvod, prečo sa mi v noci nechce spať.",
    "Keď sa na teba pozriem, zabúdam na všetky svoje problémy.",
    "Tvoje oči sú ako hviezdy, ktoré osvetľujú môj svet.",
    "Mám pocit, že som ťa poznal celý svoj život.",
    "Si nádherná ako letný západ slnka.",
    "Môžem si ťa odniesť domov? Lebo si poklad!",
    "Keď si pri mne, čas prestáva existovať.",
    "Si tá najlepšia časť môjho dňa.",
    "Ak by si bola kniha, bola by si mojím obľúbeným príbehom.",
    "Si ako sen, ktorý sa stal skutočnosťou.",
    "Každý deň s tebou je ako rozprávka.",
    "Mám pocit, že ťa hľadám celý svoj život.",
    "Ak by som mohol zastaviť čas, urobil by som to, keď som s tebou.",
    "Si to najkrajšie, čo som kedy videl.",
    "Tvoje oči sú hlbšie ako oceán.",
    "Môžem sa stratiť v tvojom úsmeve?",
    "Si ako slnko po daždi – rozžiariš môj deň.",
    "Ak by som mohol mať jednu vec na svete, bola by si to ty.",
    "Keď sa na teba pozerám, cítim sa ako v raji.",
    "Tvoje objatie je moje obľúbené miesto.",
    "Si ako šálka kávy – dokážeš ma prebudiť k životu.",
    "Si ako báseň, ktorú by som mohol čítať stále dookola.",
    "Keby som bol maliar, namaľoval by som iba teba.",
    "Tvoja krása sa nedá opísať slovami.",
    "Si ako melódia, ktorá mi stále hrá v hlave.",
    "Môžem si požičať tvoje srdce? Sľubujem, že ti ho vrátim.",
    "Si krásna ako letná noc plná hviezd.",
    "Tvoje pery vyzerajú, akoby boli stvorené na bozky.",
    "Keď sa usmeješ, svet je krajší.",
    "Si ako záhada, ktorú chcem stále riešiť.",
    "Tvoj smiech je najkrajší zvuk, aký som kedy počul.",
    "Keď si pri mne, všetko je dokonalé.",
    "Ak by som mohol byť kdekoľvek na svete, bol by som pri tebe.",
    "Môžem byť tvojím rytierom v žiarivej zbroji?",
    "Si ako kniha, ktorú nikdy nechcem prestať čítať.",
    "Ak by si bola farba, bola by si tá najjasnejšia.",
    "Keď sa na teba pozriem, zabúdam na všetko okolo.",
    "Si ako lúč slnka v daždivý deň.",
    "Tvoj pohľad ma dokáže zohriať viac ako horúci čaj.",
    "Si ako kvapka rosy na rannej lúke – nádherná a osviežujúca.",
    "Tvoje pery sú ako čerešne – sladké a neodolateľné.",
    "Máš úsmev, ktorý dokáže roztopiť aj ľad.",
    "Ak by som mal opísať dokonalosť jedným slovom, bolo by to tvoje meno.",
    "Tvoja prítomnosť je ako kúzlo – robí všetko krajším.",
    "Si ako najkrajšia hviezda na nočnej oblohe.",
    "Keď ťa vidím, môj deň je hneď lepší.",
    "Si krásna nielen zvonka, ale aj zvnútra.",
    "Máš srdce zo zlata.",
    "Si môj najväčší poklad.",
    "Si ako sladký sen, z ktorého sa nechcem prebudiť.",
    "Každý moment s tebou je nezabudnuteľný.",
    "Tvoje objatie je ako domov – teplé a bezpečné.",
    "Si ako kvet, ktorý rozžiari každú miestnosť.",
    "Si ako hudba, ktorá ma napĺňa radosťou.",
    "Keď si pri mne, mám pocit, že môžem zvládnuť čokoľvek.",
    "Si ako vánok v horúcom lete – osviežujúca a upokojujúca.",
    "Tvoja prítomnosť je ako liek na všetky moje starosti.",
    "Si ako kniha, ktorú nikdy nechcem dočítať.",
    "Každý deň s tebou je ako sviatok.",
    "Si ako perla v mori – vzácna a jedinečná.",
    "Tvoj úsmev je to najkrajšie, čo som dnes videl.",
    "Si ako hviezda padajúca z neba – úžasná a žiarivá.",
    "Si môj najkrajší sen, ktorý sa stal skutočnosťou.",
    "Si ako sladký koláčik – neviem sa ťa nabažiť.",
    "Tvoj smiech je ako hudba pre moje srdce.",
    "Si ako dúha po búrke – nádherná a plná farieb.",
    "Keď ťa vidím, mám pocit, že celý svet sa zastavil.",
    "Si ako čarovný elixír, ktorý mi dodáva energiu.",
    "Tvoj hlas je ako najjemnejšia melódia.",
    "Si krásna ako jar v plnom rozkvete.",
    "Každý deň s tebou je ako darček.",
    "Si moja inšpirácia a dôvod na úsmev.",
    "Si ako rozprávková princezná.",
    "Môžem si požičať tvoju ruku? Chcem ťa viesť celým životom.",
    "Si ako kométa na nočnej oblohe – oslnivá a jedinečná.",
    "Si môj splnený sen.",
    "Si tá najlepšia vec, čo sa mi kedy stala.",
    "Keď ťa vidím, viem, že láska existuje.",
    "Si ako šťastná náhoda, ktorá mi zmenila život.",
    "Tvoj úsmev je môj najobľúbenejší pohľad.",
    "Si krásna nielen na pohľad, ale aj v srdci.",
    "Si ako slnko, ktoré rozjasňuje môj život.",
    "Môžem byť tvojím ochrancom na celý život?",
    "Si ako báseň, ktorá nikdy nekončí.",
    "Tvoj smiech je ako najlepšia pieseň.",
    "Keď ťa vidím, cítim sa ako v raji.",
]

advance = [
    "Keby láska mala tvár, určite by vyzerala ako ty.",
    "Tvoje oči nie sú len krásne, sú ako portál do sveta, v ktorom chcem žiť.",
    "Každý deň bez teba je ako kniha bez slov – prázdny a bez významu.",
    "Ak by som mohol byť kdekoľvek na svete, bol by som v tvojom náručí.",
    "Si ako báseň, ktorej význam pochopím až po celý život.",
    "Keď sa usmeješ, mám pocit, že sa rozsvieti celý vesmír.",
    "Tvoje pery sú ako hádanka, ktorú túžim vyriešiť bozkom.",
    "Keď sa na teba pozriem, vidím svoju budúcnosť plnú lásky.",
    "Si ako víno – s každým dňom len zreješ a si krajšia.",
    "Ak by láska bola umenie, ty by si bola majstrovské dielo.",
    "Tvoja vôňa je ako tajná záhrada, do ktorej sa chcem navždy stratiť.",
    "Tvoje objatie je ako bezpečný prístav v búrke môjho života.",
    "Si ako zakázané ovocie – neodolateľná a sladká.",
    "Ak by som mal počítať všetky dôvody, prečo ťa milujem, nikdy by som neskončil.",
    "Tvoje pery vyzerajú ako stvorené na to, aby som ich ochutnal.",
    "Keď sa naše pohľady stretnú, cítim elektrinu, ktorá ma prechádza celým telom.",
    "Si ako hviezda, ktorá mi osvetľuje cestu v najtemnejšej noci.",
    "Ak by som mohol písať básne, každé slovo by bolo o tebe.",
    "Každý dotyk tvojich rúk ma rozpáli viac ako letné slnko.",
    "Si ako symfónia, ktorej tóny hrajú v mojom srdci.",
    "Tvoja duša je taká nádherná, že ju chcem spoznávať každý deň.",
    "Si ako klenot ukrytý v piesku, ktorý som mal to šťastie nájsť.",
    "Keby som mal jednu noc na zemi, strávil by som ju len s tebou.",
    "Si ako rozprávka, ktorú nikdy nechcem prestať čítať.",
    "Tvoj smiech je ako melódia, ktorú chcem počúvať do konca života.",
    "Keď sa ma dotkneš, mám pocit, že sa zastavil čas.",
    "Tvoje slová sú ako šepot vetra, jemné a plné tajomstiev.",
    "Si ako magnet, ktorý ma priťahuje bližšie a bližšie.",
    "Každý okamih bez teba je ako zima bez snehu – smutný a neúplný.",
    "Si ako západ slnka – krásna, hypnotizujúca a neopakovateľná.",
    "Keby som mohol, zakonzervoval by som každý moment s tebou do večnosti.",
    "Si ako búrka, ktorá mi prevrátila svet hore nohami – ale milujem to.",
    "Tvoj pohľad je ako tajomná kniha, ktorú túžim rozlúštiť.",
    "Si ako teplý letný dážď – osviežujúca a nečakane nádherná.",
    "Keď ma objímeš, cítim, že patrím presne tam, kde mám byť.",
    "Ak by sa dal nakresliť obraz šťastia, bola by si na ňom ty.",
    "Si ako zakázaný sen, ktorý sa mi vkradol do reality.",
    "Tvoje srdce bije ako najkrajšia melódia, ktorú chcem počúvať stále.",
    "Každý moment s tebou je ako tichá pieseň, ktorú si chcem zapamätať navždy.",
    "Si ako lúč slnka, ktorý dokáže rozmraziť aj ten najchladnejší deň.",
    "Keby láska mala hlas, znela by presne ako ty.",
    "Si ako hádanka, ktorej riešenie je pre mňa najkrajším objavom.",
    "Každá sekunda s tebou je ako drahokam v mojej zbierke spomienok.",
    "Si ako báseň, ktorú chcem čítať znova a znova.",
    "Keď sa na teba pozriem, cítim, že som našiel všetko, čo som kedy hľadal.",
    "Tvoje objatie je pre mňa ako najkrajšie útočisko na svete.",
    "Si ako hviezdna obloha, plná tajomstiev a nekonečnej krásy.",
    "Ak by som mohol zachytiť tvoju krásu do obrazu, maliari by závideli.",
    "Si ako nádherný sen, z ktorého sa nechcem prebudiť.",
    "Keď sa naše pery stretnú, cítim, že vesmír je presne taký, aký má byť.",
    "Si ako zakázané tajomstvo, ktoré ma neustále priťahuje.",
    "Ak by som mal jednu možnosť zastaviť čas, bolo by to vždy, keď si pri mne.",
    "Si ako najlepšia kniha – nemôžem prestať obracať stránky.",
    "Každá tvoja myšlienka je pre mňa ako dar, ktorý chcem rozbaľovať navždy.",
    "Si ako vzácna perla v oceáne – jedinečná a neporovnateľná.",
    "Tvoje bozky chutia ako raj, z ktorého nechcem odísť.",
    "Keď ťa držím v náručí, cítim, že som konečne doma.",
    "Si ako najvzácnejší poklad, ktorý som hľadal celý život.",
    "Každý dotyk tvojej pokožky je ako elektrický impulz priamo do môjho srdca.",
    "Si ako tanec svetla a tieňa – fascinujúca a neodolateľná.",
    "Tvoja prítomnosť je pre mňa ako dýchanie – nemôžem bez nej žiť.",
    "Keď sa naše pohľady stretnú, svet prestáva existovať.",
    "Si ako letný dážď – nečakaná, osviežujúca a nádherná.",
    "Si jediná konštanta v mojom chaotickom svete.",
    "Tvoje srdce je pre mňa najkrajšia krajina, ktorú chcem spoznávať.",
    "Si ako neprečítaný román, ktorého každé slovo ma fascinuje.",
    "Tvoje bozky sú ako vietor, ktorý ma odnáša do sveta snov.",
    "Keď si pri mne, cítim, že som konečne našiel svoj domov.",
    "Si ako nočná obloha posiata hviezdami – hypnotizujúca a nekonečná.",
    "Tvoje oči majú v sebe hĺbku oceánu a tajomstvo vesmíru.",
    "Si ako labyrint, v ktorom sa chcem stratiť navždy.",
    "Tvoje dotyky sú ako maliarske ťahy na plátne mojej duše.",
    "Keď ťa pobozkám, cítim, že sme jediné dve bytosti v celom vesmíre.",
    "Si ako rieka, ktorá ma unáša do sveta lásky a túžby.",
    "Tvoje srdce je najvzácnejší poklad, aký som kedy objavil.",
    "Každá sekunda bez teba je ako zima bez snehu – smutná a chladná.",
]

sk_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
