simple = [
    "Ti si razlog zašto verujem u ljubav.",
    "Tvoj osmeh može osvetliti i najtamniju noć.",
    "Ako je ljubav umetnost, ti si moje remek-delo.",
    "Znaš li da tvoj pogled može zaustaviti vreme?",
    "Da imam dinar za svaki put kada pomislim na tebe, bio bih milioner.",
    "Bez tebe, moj svet bi bio crno-beli.",
    "Da li si magnet? Jer me neodoljivo privlačiš.",
    "S tobom je svaki trenutak bajka.",
    "Tvoje oči su kao okean, mogu se izgubiti u njima.",
    "Da mogu birati gde da budem, bio bih pored tebe.",
    "Tvoj glas je muzika za moje srce.",
    "Da si pesma, bila bi moj omiljeni hit.",
    "Tvoja lepota je kao san iz kojeg ne želim da se probudim.",
    "Ako je ljubav igra, ti si moj omiljeni nivo.",
    "Tvoj dodir je poput čarolije.",
    "Biti s tobom je kao dobitak na lutriji.",
    "Ti si moj omiljeni razlog za osmeh.",
    "Voleo bih da mogu zamrznuti trenutak kad te gledam.",
    "Tvoje usne su kao med, a ja sam pčela.",
    "Nebo je ljubomorno na tvoju lepotu.",
    "Kad bih imao jedno želju, poželeo bih da te zauvek volim.",
    "S tobom svaki dan izgleda kao proleće.",
    "Ti si najlepša pesma koju moje srce peva.",
    "Tvoje srce i moje srce imaju isti ritam.",
    "Znaš li da je tvoj osmeh zarazan?",
    "Ti si moj najslađi san.",
    "Sa tobom je čak i kišni dan savršen.",
    "Ako je ljubav putovanje, želim da ga prođem s tobom.",
    "Zračiš svetlošću kao zvezda na noćnom nebu.",
    "Kad bi postojala olimpijska disciplina za lepotu, osvojila bi zlato.",
    "Mogu li te držati za ruku? Samo da se uverim da nisi san.",
    "Moje srce preskače otkucaj svaki put kad te vidim.",
    "Da li si vila? Jer si jednostavno čarobna.",
    "Bez tebe, svaki dan je prazan list papira.",
    "Tvoj miris je bolji od najlepšeg parfema.",
    "Pogled na tebe leči i najtužnije srce.",
    "Ako bi ljubav imala oblik, bila bi u obliku tebe.",
    "Mogu li ti ukrasti poljubac? Obećavam da ću ga vratiti.",
    "Ti si najbolja stvar koja mi se dogodila.",
    "Tvoj dodir je poput sunčeve svetlosti na mojoj koži.",
    "Ljubav s tobom je kao najlepša bajka.",
    "Znaš li da su svi moji putevi vodili do tebe?",
    "Tvoje prisustvo je sve što mi treba da budem srećan.",
    "Sa tobom, čak i običan dan postaje poseban.",
    "Ti si jedina osoba zbog koje gubim dah.",
    "Tvoje ruke su moj omiljeni zagrljaj.",
    "S tobom svaki sat traje minut.",
    "Moj svet je bolji kada si u njemu.",
    "Biti pored tebe je kao san koji ne želim da završi.",
    "Tvoje usne su kao savršena melodija.",
    "Ako bih morao da opišem sreću u jednoj reči, to bi bilo tvoje ime.",
    "Ti si najlepši deo mog dana.",
    "S tobom, ljubav je najlepša avantura.",
    "Nijedna reč ne može opisati koliko si posebna.",
    "Tvoj osmeh može rastopiti i najhladnije srce.",
    "Ti si sunce mog života.",
    "Moje srce pripada tebi i samo tebi.",
    "Znaš li da si razlog mog osmeha svakog dana?",
    "Tvoje oči su kao dve zvezde koje osvetljavaju moj svet.",
    "Da si pesma, bila bi najlepši refren.",
    "Sa tobom, i običan trenutak postaje nezaboravan.",
    "Ne trebaju mi reči da ti kažem koliko te volim.",
    "Da mogu crtati, naslikao bih te svaki dan.",
    "Ti si odgovor na svaku moju molitvu.",
    "Voleo bih da svaki trenutak provodim s tobom.",
    "Tvoj glas je najlepša pesma koju sam ikada čuo.",
    "Ljubav u tvojim očima je sve što mi treba.",
    "Bez tebe, život bi bio kao knjiga bez priče.",
    "Svaka sekunda provedena s tobom je blago.",
    "Sa tobom je svaki poljubac magičan.",
    "Mogu li te zagrliti? Samo da vidim kako je biti u raju.",
    "S tobom, svaki trenutak je savršen.",
    "Kad bi ljubav imala oblik, nosila bi tvoje ime.",
    "Da mogu, ukrao bih sve tvoje suze i pretvorio ih u osmehe.",
    "Tvoj osmeh je moje omiljeno umetničko delo.",
    "Moj svet bez tebe nema boje.",
    "Ti si pesma koju želim da slušam zauvek.",
    "Voleo bih da se budim pored tebe svakog jutra.",
    "Tvoja lepota je kao zalazak sunca – neponovljiva.",
    "Kad te vidim, zaboravim na sve probleme.",
    "Ti si moje najdraže mesto na svetu.",
    "Svaki put kada se nasmeješ, moje srce zaigra.",
    "Tvoje oči su kao tajna u koju želim da zaronim.",
    "Moje srce kuca samo za tebe.",
    "Da li veruješ u ljubav na prvi pogled ili da prođem ponovo?",
    "Kad bih imao moć da zaustavim vreme, zaustavio bih ga svaki put kada te pogledam.",
    "Ti si sve što mi treba da budem srećan.",
    "Da si san, nikada ne bih želeo da se probudim.",
    "Svaki put kad te pogledam, zaljubim se ponovo.",
    "Ne znam šta mi se više sviđa kod tebe – tvoj osmeh, tvoj pogled ili tvoje srce.",
    "Da li znaš da sam izgubio mapu? Jer sam se izgubio u tvojim očima.",
    "Tvoj dodir je poput toplog letnjeg povetarca.",
    "Svaka pesma o ljubavi me podseća na tebe.",
    "Kad bih bio pesnik, napisao bih stotine pesama o tebi.",
    "Tvoj osmeh osvetljava i najtamniji dan.",
    "Ako bi ljubav bila jezik, ti bi bila moja najlepša rečenica.",
    "Tvoj dodir čini da se osećam kao kod kuće."
]

advance = [
    "Ako su tvoje oči univerzum, onda sam ja astronaut koji želi da istraži svaku njihovu tajnu.",
    "Kada bih mogao da napišem simfoniju, svaka nota bi bila inspirisana tobom.",
    "Tvoj osmeh nije samo lepota – to je čarolija koja menja moj svet.",
    "Da li si ti pesnikinja? Jer svaka tvoja reč zvuči kao najlepša poezija.",
    "Voleo bih da budem knjiga u tvojim rukama, da me čitaš svake noći pre spavanja.",
    "Kad bi moje srce moglo da govori, svaka rečenica bi počinjala s tvojim imenom.",
    "Tvoj dodir je kao najfinija svila, nežan i neodoljiv.",
    "Ako je ljubav matematička jednačina, onda si ti moje savršeno rešenje.",
    "Kad bih mogao da zaustavim vreme, učinio bih to svaki put kad se pogledamo.",
    "Znaš li da si ti inspiracija za sve moje snove?",
    "Kad bi moj život bio knjiga, svaka stranica bi bila posvećena tebi.",
    "Tvoje prisustvo je poput vetra u vreloj letnjoj noći – osvežavajuće i neophodno.",
    "Kad te vidim, svaki problem u mom životu postaje nebitan.",
    "Da li veruješ u sudbinu? Jer svaki znak pokazuje da pripadamo jedno drugom.",
    "Tvoje reči su poput poezije, svaka nosi svoju lepotu i ritam.",
    "Ako postoji paralelni univerzum, siguran sam da smo i tamo zaljubljeni.",
    "Tvoj glas je melodija koju bih voleo da slušam zauvek.",
    "Biti pored tebe je kao slušati najlepšu simfoniju pod svetlom zvezda.",
    "Da li znaš da svaki put kada me pogledaš, svet postane malo lepši?",
    "Ako ljubav ima jezik, onda je tvoj osmeh najlepša rečenica koju razumem.",
    "Kad bi postojala medalja za savršenstvo, ti bi bila njen večiti vlasnik.",
    "Tvoje prisustvo u mom životu je kao biser u školjci – dragoceno i retko.",
    "Znaš li da u tvom pogledu mogu pročitati celu galaksiju emocija?",
    "Ako bih bio slikar, svaka moja slika bila bi portret tebe.",
    "Kada bi ljubav bila melodija, svaka nota bi bila tvoje ime.",
    "S tobom i najjednostavniji trenuci postaju magični.",
    "Mogu li da budem tvoj senka? Tako bih te pratio svuda, a da me ne primetiš.",
    "Kad te vidim, razumem zašto pesnici pišu o ljubavi.",
    "Da li znaš da sam izgubio osećaj za vreme otkako si u mom životu?",
    "Ako je tvoj poljubac odgovor, mogu li ponovo postaviti pitanje?",
    "Kada bi postojala knjiga o ljubavi, prva stranica bi bila o tebi.",
    "Znaš li da svaki trenutak proveden s tobom ostavlja neizbrisiv trag u mom srcu?",
    "Tvoj osmeh je šifra koja otključava moje srce.",
    "Kada bih mogao da zaustavim trenutak, bio bi to onaj kada se smeješ.",
    "Tvoj glas mi je omiljena pesma koju nikad ne želim da prestanem da slušam.",
    "Ako bi ljubav imala ukus, siguran sam da bi bila sladak kao tvoj poljubac.",
    "Sa tobom ne postoji prošlost ni budućnost – samo beskonačan trenutak sadašnjosti.",
    "Kad te nema, vreme prolazi sporo, ali kada si tu, leti kao vetar.",
    "Znaš li da se zaljubljujem u tebe iznova i iznova, svaki dan?",
    "Tvoje ruke su moje omiljeno mesto na svetu.",
    "Kad bi ljubav bila putovanje, svaki korak bih želeo da napravim s tobom.",
    "Tvoj pogled je poput noćnog neba – pun tajni i beskonačne lepote.",
    "Mogu li biti razlog tvog osmeha, onako kako si ti razlog mog?",
    "Tvoj dodir je kao treptaj zvezde – nežan, ali ostavlja trag.",
    "Kad bi ljubav bila priča, ti bi bila najlepši zaplet.",
    "Svaki trenutak s tobom je dragocen kao zlatnik iz davnih vremena.",
    "Tvoj osmeh je jedina valuta kojom želim da budem plaćen.",
    "Ako je ljubav nauka, onda si ti moja najlepša hipoteza.",
    "Da li znaš da tvoj pogled može obrisati sve loše misli iz mog uma?",
    "Tvoje srce i moje srce pričaju istim jezikom.",
    "Mogu li da budem deo tvoje najlepše priče?",
    "Kad bih mogao da poželim jednu stvar, bilo bi to da zauvek ostaneš kraj mene.",
    "Ako su tvoji poljupci san, molim te, ne budi me nikad.",
    "Tvoj osmeh je moj najdraži pejzaž.",
    "Da li znaš da svaki put kad se nasmeješ, stvaraš još jednu zvezdu na nebu?",
    "Sa tobom, svaki trenutak je umetnost vredna divljenja.",
    "Da li veruješ u čuda? Jer ti si moje čudo.",
    "Mogu li da budem olovka koja ispisuje tvoju ljubavnu priču?",
    "Tvoj glas je pesma koju želim da slušam svako jutro.",
    "Znaš li da svaki put kad te dodirnem, osećam vatromet u svom srcu?",
    "Tvoj pogled je najlepša poezija koju sam ikada pročitao.",
    "Kad bih imao samo jednu želju, bila bi da zauvek gledam tvoj osmeh.",
    "Tvoja blizina je moj omiljeni osećaj na svetu.",
    "Sa tobom, čak i tišina ima svoj zvuk – zvuk ljubavi.",
    "Ako bih mogao da nacrtam sreću, imala bi oblik tvog osmeha.",
    "Tvoj poljubac je poput retkog vina – opija me sa svakim gutljajem.",
    "Kad bih bio vreme, zaustavio bih se svaki put kad si pored mene.",
    "Tvoj dodir budi u meni osećaje koje ne mogu opisati rečima.",
    "Znaš li da moje srce igra valcer svaki put kada te ugledam?",
    "Mogu li biti priča koju ćeš prepričavati unucima kao svoju najveću ljubav?",
    "Ako su tvoje usne knjiga, želim da budem onaj koji će ih neprestano čitati.",
    "Sa tobom, svaki zalazak sunca postaje umetničko delo.",
    "Da li znaš da si ti moj savršeni trenutak u večnosti?",
    "Tvoj osmeh je pesma koja mi se neprestano ponavlja u mislima.",
    "Ako bih mogao da uhvatim zvezdu za svaki tvoj osmeh, imao bih sopstveno sazvežđe.",
    "Mogu li biti razlog zašto ti srce brže kuca?",
    "Tvoj poljubac je kompas koji uvek pokazuje pravo mesto – tvoje srce.",
    "Ako su tvoje ruke raj, želim da budem tvoj večni stanovnik."
]

sr_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
