simple = [
    "Du måste vara en kamera, för varje gång jag tittar på dig, ler jag.",
    "Är du en magiker? För varje gång jag tittar på dig, försvinner alla andra.",
    "Är du trött? För du har sprungit genom mina tankar hela dagen.",
    "Jag är ingen fotograf, men jag kan föreställa oss tillsammans.",
    "Är du en ängel? För himlen saknar en av sina egna.",
    "Om skönhet var en brott, skulle du vara dömd för livet.",
    "Jag tror på kärlek vid första ögonkastet… Måste jag gå förbi igen?",
    "Kan du hålla min hand? Jag vill visa mina vänner att jag har rört en ängel.",
    "Är du WiFi? För jag känner en stark anslutning.",
    "Du lyser upp mitt liv som solen på en sommardag.",
    "Ditt leende är som en soluppgång, det gör min dag ljusare.",
    "Om du var en blomma, skulle du vara den vackraste i trädgården.",
    "Är du en tjuv? För du har stulit mitt hjärta.",
    "Om kyssar var snöflingor, skulle jag skicka dig en storm.",
    "Du måste vara en regnbåge, för du lyser upp min dag.",
    "Om jag fick en krona för varje gång jag tänkte på dig, skulle jag vara rik.",
    "Jag vet inte om du är en dröm eller verklighet, men jag vill aldrig vakna.",
    "Ditt skratt är som musik för mina öron.",
    "Kan du le en gång till? Jag glömde andas.",
    "Du måste vara en trollkarl, för varje gång du ser på mig, blir jag förtrollad.",
    "Är du ett pussel? För du är den saknade biten i mitt liv.",
    "Ditt namn borde vara Google, för du har allt jag söker.",
    "Jag kan inte spela schack, men du och jag är ett perfekt drag.",
    "Jag måste vara en snöflinga, för jag smälter när jag ser dig.",
    "Om skönhet var tid, skulle du vara evigheten.",
    "Får jag låna en karta? Jag gick vilse i dina ögon.",
    "Du måste vara en diamant, för du är ovärderlig.",
    "Jag tappade mitt nummer, kan jag få ditt istället?",
    "Jag är inte en poet, men du inspirerar mig att skriva kärlekssånger.",
    "Jag vill vara den anledningen till att du ler varje dag.",
    "Kan jag få din bild? Så jag kan visa jultomten vad jag önskar mig.",
    "Är du gjord av koppar och tellur? För du är Cu-Te.",
    "Jag vet inte om det är kärlek vid första ögonkastet, men jag kan titta på dig igen.",
    "Ditt hjärta måste vara en skatt, för jag vill stjäla det.",
    "Är du en eld? För du värmer mitt hjärta.",
    "Om jag var en katt, skulle jag spendera alla mina nio liv med dig.",
    "Jag trodde att lycka började med 'H', men nu ser jag att det börjar med 'Du'.",
    "Om jag kunde omorganisera alfabetet, skulle jag sätta U och J tillsammans.",
    "Jag är som en snöflinga, unik och redo att smälta i dina händer.",
    "Du är den saknade låten i mitt hjärtas melodi.",
    "Jag behöver ingen karta, för jag har hittat min väg till dig.",
    "Är du en stjärna? För du lyser upp min mörkaste natt.",
    "Är du en kanelbulle? För du är söt och oemotståndlig.",
    "Om vi var i en film, skulle det vara en kärlekshistoria.",
    "Jag behöver solglasögon, för ditt leende lyser för starkt.",
    "Jag kan inte trolla, men jag kan få ditt hjärta att hoppa över ett slag.",
    "Är du en bok? För jag kan inte sluta läsa dig.",
    "Är du en måne? För du lyser upp min natt.",
    "Du är mitt kaffe på morgonen – det bästa sättet att börja dagen.",
    "Om kärlek var ett spel, skulle jag spela för alltid med dig.",
    "Kan jag hålla din hand? Jag vill se om våra hjärtan slår i takt.",
    "Ditt skratt är som en melodi jag vill lyssna på för alltid.",
    "Jag kanske inte är en prins, men jag kan behandla dig som en prinsessa.",
    "Är du en skattkarta? För du leder mig till något värdefullt.",
    "Du måste vara en dröm, för du är för perfekt för att vara sann.",
    "Jag vet inte vad du gjorde med mig, men jag kan inte sluta tänka på dig.",
    "Du är den enda fisken i havet för mig.",
    "Är du en fyr? För du lyser upp mitt mörker.",
    "Jag behöver inget filter när jag är med dig – du gör världen vackrare.",
    "Jag måste vara en magnet, för jag dras till dig.",
    "Du gör mitt hjärta snabbare än en sportbil.",
    "Du är som en vacker solnedgång, jag kan inte sluta beundra dig.",
    "Är du en parfym? För du har lämnat ett oförglömligt intryck på mig.",
    "Om du var en låt, skulle du vara min favoritmelodi.",
    "Du är den gnista som tänder min eld.",
    "Dina ögon är som en galax, jag kan förlora mig i dem.",
    "Jag vill vara anledningen till att du ler varje morgon.",
    "Är du en nyckel? För du har låst upp mitt hjärta.",
    "Du är som en dröm jag aldrig vill vakna från.",
    "Är du en emoji? För du gör mig 😊 varje gång jag ser dig.",
    "Kan vi ta en bild tillsammans? Jag vill visa mina vänner att änglar finns.",
    "Jag tror att vi är som pusselbitar – vi passar perfekt ihop.",
    "Är du en dikt? För du är ren poesi.",
    "Du är min favoritplats att gå vilse i.",
    "Är du ett moln? För du får mig att sväva.",
    "Om jag var en målare, skulle jag bara måla dig.",
    "Ditt leende gör världen lite ljusare.",
    "Är du ett ljus? För du lyser upp min dag.",
    "Jag skulle gå genom eld och vatten för att vara vid din sida.",
    "Ditt hjärta är som en magnet, och jag är järn.",
    "Är du en saga? För jag vill ha ett lyckligt slut med dig.",
    "Kan du peka på kartan? Jag försöker hitta vägen till ditt hjärta.",
    "Du är som choklad – söt, oemotståndlig och beroendeframkallande.",
    "Är du en blomma? För du sprider skönhet omkring dig.",
    "Jag önskar att jag var en spegel, så jag kunde se dig varje morgon.",
    "Är du en superhjälte? För du har räddat mitt hjärta.",
    "Jag kanske inte är en vetenskapsman, men jag känner kemin mellan oss.",
    "Om mitt hjärta hade en radio, skulle du vara favoritkanalen.",
]

advance = [
    "Dina ögon är som svarta hål, för jag faller djupare in i dem varje gång jag ser dig.",
    "Jag är som en matematisk ekvation utan lösning utan dig vid min sida.",
    "Ditt leende är som en kodsnutt som alltid kompilerar utan fel.",
    "Om mitt hjärta var en algoritm, skulle du vara dess mest optimerade lösning.",
    "Är du kvantfysik? För du får min verklighet att kännas osäker och spännande.",
    "Om vi vore en funktion, skulle vi alltid returnera sann kärlek.",
    "Du är den enda variabeln jag vill ha i min ekvation för lycka.",
    "Mitt hjärta slår snabbare än en överklockad processor när jag ser dig.",
    "Du är som ett elegant kodstycke – vacker, effektiv och omöjlig att förbättra.",
    "Om skönhet var ett programmeringsspråk, skulle du vara syntaxen till mitt hjärta.",
    "Du är som en kryptografisk nyckel – den enda som kan låsa upp mitt hjärta.",
    "Ditt skratt är som ett perfekt sammansatt ackord i en symfoni av kärlek.",
    "Om kärlek var ett pussel, skulle du vara den sista biten jag alltid letat efter.",
    "Är du en stjärna? För du lyser upp min mörkaste natt och guidar mig hem.",
    "Om jag kunde navigera genom ditt hjärta som jag gör på Google Maps, skulle jag alltid hitta hem.",
    "Vår kemi är som en kvantfluktuation – oförutsägbar men alltid närvarande.",
    "Jag måste vara en satellit, för jag kan inte sluta kretsa kring dig.",
    "Är du en galax? För jag vill förlora mig i ditt universum för alltid.",
    "Om kärlek var en kod, skulle du vara min huvudmetod.",
    "Du är som en poetisk algoritm, vacker och logisk på samma gång.",
    "Om jag var en hacker, skulle ditt hjärta vara mitt slutmål.",
    "Du är som en AI som redan vet exakt vad jag behöver för att vara lycklig.",
    "Är du en dröm? För du känns för perfekt för att vara verklighet.",
    "Du är den starkaste WiFi-signalen i mitt liv – och jag vill aldrig koppla bort.",
    "Jag behöver ingen GPS, för mitt hjärta vet alltid vägen till dig.",
    "Dina ögon är som ett parallellt universum där bara vi existerar.",
    "Är du en paradox? För du är både en storm och en frid på samma gång.",
    "Jag önskar att jag kunde pausa tiden när jag är med dig, så vi aldrig behövde skiljas åt.",
    "Är du ett svart hål? För jag kan inte undkomma din gravitation.",
    "Om vårt kärleksliv var en roman, skulle den vara en internationell bästsäljare.",
    "Du är som en kvantpartikel – jag kan aldrig förutsäga var du är, men jag vet att jag vill vara nära dig.",
    "Du är som en kryptovaluta – värdefull, unik och oersättlig.",
    "Om du var en komet, skulle jag önska att du aldrig lämnade min himmel.",
    "Om kärlek var ett språk, skulle jag skriva hela min värld i versaler bara för dig.",
    "Du får mina sinnen att överbelastas, precis som en dåligt optimerad server.",
    "Är du en git commit? För jag vill aldrig förlora den versionen av dig.",
    "Om vi var en kod, skulle vi aldrig ha buggar – bara oändlig kompatibilitet.",
    "Du är som en fraktal – komplex, vacker och oändligt fascinerande.",
    "Är du en AI? För du har redan lärt dig alla mina svagheter och styrkor.",
    "Jag vill vara den algoritm som alltid ger dig den optimala lösningen för lycka.",
    "Om våra hjärtan var en blockchain, skulle vår kärlek vara den starkaste länken.",
    "Du är den mest värdefulla variabeln i mitt livs ekvation.",
    "Är du en neutronstjärna? För du har en enorm dragningskraft på mig.",
    "Om jag kunde skriva en kod för kärlek, skulle du vara dess enda parameter.",
    "Du är som en kvantteleportation – jag förstår inte riktigt hur det fungerar, men det känns magiskt.",
    "Om vi var två trådar i en process, skulle vi alltid köra i perfekt synk.",
    "Du är den mest komplicerade och samtidigt vackraste algoritmen jag någonsin försökt förstå.",
    "Om jag hade en enda variabel att optimera i livet, skulle det vara tiden jag spenderar med dig.",
    "Är du ett nätverk? För jag känner en stark och stabil anslutning med dig.",
    "Du är som en supernova – du lyser upp hela mitt universum.",
    "Om mitt hjärta var en server, skulle du ha exklusiv åtkomst.",
    "Är du en tidsresenär? För jag ser en framtid med dig varje gång jag tittar i dina ögon.",
    "Om vår kärlek var en programmeringsspråk, skulle det vara den mest eleganta syntaxen någonsin.",
    "Ditt leende har en högre frekvens än någon annan våglängd av lycka jag känt.",
    "Du är som en perfekt organiserad databas – allt om dig är på rätt plats.",
    "Om kärlek var en chattbot, skulle våra konversationer aldrig ta slut.",
    "Du är som en kvantsuperposition – jag vet att du är där, men du är så mycket mer än bara en sak.",
    "Om våra hjärtan var en RSA-kryptering, skulle vi ha den perfekta nyckeln till varandra.",
    "Är du en optimerad kod? För du tar bort all onödig osäkerhet i mitt liv.",
    "Ditt skratt är som en ekokammare av lycka som aldrig tystnar.",
    "Jag vill vara den algoritm som alltid prioriterar dig över allt annat.",
    "Du är som en perfekt kryptoalgoritm – säker, värdefull och oersättlig.",
    "Om du var ett moln, skulle jag spara alla mina drömmar hos dig.",
    "Är du en firmware-uppdatering? För du förbättrar mitt liv varje gång du är nära.",
    "Om vår kärlek var en API, skulle den alltid returnera en 200 OK-status.",
    "Du är som en dark mode-inställning – du gör allt bättre och mer behagligt.",
    "Är du ett programmeringsfel? För du får hela mitt system att krascha av kärlek.",
    "Om våra hjärtan var en blockchain, skulle vår kärlek vara omöjlig att manipulera.",
    "Är du en simulation? För att du känns för perfekt för att vara sann.",
    "Om kärlek var en maskininlärningsmodell, skulle du vara min bästa träningsexempel.",
    "Är du en server med låg latency? För du svarar alltid perfekt på mina känslor.",
    "Om du var en frekvens, skulle du vara den perfekta harmonin i mitt liv.",
    "Är du en grafdatabas? För alla mina vägar leder till dig.",
    "Jag tror vi har en naturlig logisk relation – vi är menade för varandra.",
    "Om vi var två satser i en kod, skulle vi alltid exekveras tillsammans.",
    "Du är som en säker krypteringsnyckel – du håller mitt hjärta tryggt.",
]

sv_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
