simple = [
    "Ang ganda mo, parang araw. Laging nagpapaliwanag ng araw ko.",
    "Pwede ba kitang tawaging Google? Kasi nasa'yo na lahat ng hinahanap ko.",
    "Buti pa ang kape, mainit. Pero mas mainit ang tingin ko sa’yo.",
    "Nahulog ako... hindi sa hagdan, kundi sa’yo.",
    "Para kang exam, hindi kita kayang sagutan kahit anong gawin ko.",
    "Kapag kasama kita, parang may WiFi signal—lahat nagiging konektado.",
    "Sana nagdala ako ng mapa, kasi naliligaw na ako sa mga mata mo.",
    "Para kang ulan, hindi ko kayang tigilan ang pag-iisip sa’yo.",
    "Kape ka ba? Kasi hindi ako makatulog kakaisip sa’yo.",
    "Para kang magnet, palagi mo akong hinihila palapit sa’yo.",
    "Ang ganda mo, parang tula na hindi ko kayang tapusin.",
    "Masarap ba ang buhay mo? Kasi parang gusto kitang tikman.",
    "May dala ka bang flashlight? Kasi pinapaliwanag mo ang madilim kong mundo.",
    "Pwede ba kitang halikan? Para malaman ko kung totoo kang anghel.",
    "Para kang vitamin, hindi ako mabubuhay nang wala ka.",
    "Ang puso ko parang traffic light, laging tumitigil kapag ikaw ang dumadaan.",
    "Pwede ba kitang yakapin? Para malaman kung totoo kang mainit sa pakiramdam.",
    "May doctor ka ba? Kasi nasaktan ako nang mahulog sa’yo.",
    "Para kang alarma, kasi ikaw lang ang gumigising sa natutulog kong puso.",
    "Pwede ba kitang samahan sa kape? Kasi gusto kitang painitin.",
    "Kung bibigyan mo ako ng pag-asa, sisiguraduhin kong hindi kita bibiguin.",
    "Para kang Netflix, kasi gusto kitang panoorin buong gabi.",
    "Hindi kita malilimutan, kasi ikaw ang pinaka-espesyal sa puso ko.",
    "Pwede bang magtanong? Paano mo ako nakuha nang ganito kabilis?",
    "Kung musika ka, ikaw ang paborito kong kanta.",
    "Para kang libro, gusto kitang basahin nang paulit-ulit.",
    "Huwag ka nang lumayo, gusto kitang yakapin habang-buhay.",
    "Hindi ko alam kung paano mo nagawa, pero nahulog ako sa’yo.",
    "Pwede ba kitang mahalin? Kasi wala na akong ibang gusto.",
    "Ikaw ang inspirasyon ko sa bawat umaga.",
    "Sa mundo ng matematikal, ikaw ang formula ng kaligayahan ko.",
    "Hindi ako marunong sa pick-up lines, pero marunong akong magmahal.",
    "Pwede ba kitang itabi sa unan ko? Para palagi kitang katabi sa gabi.",
    "Parang may spell ka, kasi hindi kita malimutan.",
    "Sana ikaw ang last piece ng puzzle ng buhay ko.",
    "Alam mo bang ikaw ang soundtrack ng puso ko?",
    "Hindi kita bibiguin, kasi ikaw ang gusto kong makasama habang-buhay.",
    "Ikaw ang dahilan kung bakit hindi ko na kailangan ng alarm clock.",
    "Kung love song ka, ikaw ang kinakanta ng puso ko.",
    "Parang cellphone ka, hindi kita kayang iwan kahit lowbatt na ako.",
    "Pwede bang ipahiram mo ang puso mo? Kasi gusto kong magpahinga sa'yo.",
    "Kung may magic ako, ikaw ang gagawin kong akin magpakailanman.",
    "Kung may wishing star, ikaw ang hihilingin ko.",
    "Ikaw ang kahulugan ng ‘perfect’ para sa akin.",
    "Para kang ulap, hindi kita kayang abutin pero gusto kitang yakapin.",
    "Sana may pause button ang buhay, para hindi matapos ang moment natin.",
    "Ikaw ang melody na paulit-ulit kong gustong pakinggan.",
    "Sana tayo na lang, para wala nang problema.",
    "Ang puso ko ay parang elevator, laging bumabagsak kapag nakikita kita.",
    "Kung pag-ibig ang laro, ikaw ang gusto kong makalaro habang-buhay.",
    "Para kang bula, kasi bigla kang lumitaw sa buhay ko at hindi na nawala.",
    "Ikaw ang missing piece ng buhay ko.",
    "Kung ako ay ilog, ikaw ang dagat na nais kong marating.",
    "Ang mata mo ay parang bituin, nagbibigay liwanag sa madilim kong gabi.",
    "Ikaw ang melody ng buhay kong walang tunog dati.",
    "Para kang ginto, kasi ikaw lang ang mahalaga sa akin.",
    "Pwede ba kitang i-hug? Para malaman kung tunay kang tao o panaginip lang.",
    "Ikaw ang dahilan kung bakit naniniwala ako sa happy endings.",
    "Mahal kita hindi dahil sa kung ano ka, kundi dahil kung paano mo ako napapasaya.",
    "Ikaw ang sagot sa lahat ng tanong ng puso ko.",
    "Gusto kitang gawing wallpaper ng puso ko.",
    "Ang ganda mo, parang sunset na hindi ko pagsasawaang pagmasdan.",
    "Para kang chocolate, hindi ako nagsasawa sa’yo.",
    "Maaari ba kitang tawagin kong ‘sakin’? Kasi gusto kitang ipaglaban.",
    "Gusto ko lang sabihin na napaka-special mo sa akin.",
    "Pwede ba kitang yayain sa isang date ng walang katapusan?",
    "Mahal kita higit pa sa kaya kong ipaliwanag.",
    "Para kang kandila, nagbibigay liwanag sa madilim kong buhay.",
    "Kung laro ito, ikaw ang grand prize na gusto kong mapanalunan.",
    "Ikaw ang perpektong halo ng tamis at saya sa buhay ko.",
    "Gusto kitang isama sa panaginip ko at gawin itong totoo.",
    "Sa milyun-milyong bituin, ikaw lang ang nag-iisang nagniningning sa puso ko.",
    "Ikaw ang rason kung bakit masaya ang bawat araw ko.",
    "Sana ikaw ang sagot sa lahat ng tanong ng buhay ko.",
    "Para kang salamin, kasi kitang-kita kita sa puso ko.",
    "Kung ikaw ay pelikula, ikaw ang gusto kong ulit-ulitin.",
    "Pwede ba kitang tawaging ‘aking’? Kasi gusto kitang mahalin habambuhay.",
    "Hindi kita ipagpapalit kahit sa pinakamagandang panaginip.",
    "Ikaw ang pangarap na gusto kong gawing realidad.",
    "Ikaw ang inspiration ko sa bawat hakbang ng buhay ko.",
    "Para kang bituin sa langit, hindi ko man maabot, pero gusto kitang mahalin.",
    "Ikaw ang gusto kong pasalamatan araw-araw.",
    "Pwede ba kitang mahalin nang walang expiration date?",
    "Hindi ako makatulog, kasi ikaw ang nasa isip ko.",
    "Sana ikaw ang forever ko.",
]

advance = [
    "Hindi ako marunong sa chess, pero sigurado akong ikaw ang winning move ko.",
    "Kung may entrance exam sa puso mo, pwede bang ako na ang automatic pass?",
    "Hindi ako marunong mag-paint, pero kaya kitang iguhit sa puso ko habang-buhay.",
    "Para kang password, hindi ko ma-crack pero alam kong ikaw lang ang tamang sagot.",
    "Kung ang buhay ay isang libro, gusto kong ikaw ang bawat pahina nito.",
    "Parang coding ka, ang dami mong syntax pero ikaw pa rin ang output ng puso ko.",
    "Hindi kita i-uninstall kahit magka-crash na ang system ko sa'yo.",
    "Parang algorithm ka, kasi ikaw lang ang tamang solution sa buhay ko.",
    "Pwede ba kitang gawing default setting ng puso ko?",
    "Kung may firewall ang puso mo, hahayaan mo bang ako lang ang may access?",
    "Sa dami ng variables sa buhay ko, ikaw lang ang constant.",
    "Kung CPU ako, ikaw ang cooling system ko kasi pinapakalma mo ako.",
    "Ang pag-ibig ko sa’yo parang WiFi, kahit invisible, ramdam mo ang signal.",
    "Para kang AI, kasi hindi kita kayang lampasan kahit anong gawin ko.",
    "Kung ikaw ay isang error, hahayaan kong hindi ito i-debug para manatili ka sa akin.",
    "Para kang API, gusto kitang i-integrate sa buhay ko habambuhay.",
    "Kung ikaw ay isang code, gusto kong ikaw ang forever na loop ng buhay ko.",
    "Para kang software update, kasi mas gumaganda ang buhay ko tuwing kasama kita.",
    "Kung ang pag-ibig ay isang game, ikaw ang ultimate boss level na ayaw kong talunin.",
    "Para kang database, kasi lahat ng gusto ko ay nasa’yo na.",
    "Kung meron mang glitch sa mundo, sana ang glitch ay lagi tayong magkasama.",
    "Hindi kita pwedeng i-format, kasi ikaw lang ang operating system ng puso ko.",
    "Para kang source code, kahit hindi ko maintindihan minsan, ikaw pa rin ang gusto kong pag-aralan habambuhay.",
    "Ikaw ang patch update na nag-ayos ng lahat ng bugs sa buhay ko.",
    "Gusto kitang gawing cloud storage ng puso ko para hindi na kita mawala.",
    "Kung ako ay isang mobile app, ikaw ang forever premium subscription ko.",
    "Ikaw ang firewall ko, kasi kahit anong dumating, ikaw lang ang kayang mag-protekta sa puso ko.",
    "Para kang encryption, kasi walang ibang makaka-decode ng puso ko kundi ikaw.",
    "Kung tayo ay isang game, sana may infinite lives para hindi tayo magtapos.",
    "Ikaw ang syntax sa code ng puso ko, wala kang katulad.",
    "Kung ikaw ay isang binary, ikaw ang 1 sa lahat ng 0 ko.",
    "Hindi kita i-restart kahit maghang na ang mundo sa pagmamahal ko sa’yo.",
    "Para kang blockchain, walang makakabura ng value mo sa buhay ko.",
    "Ikaw ang AI assistant ko, kasi ikaw lang ang nagbibigay ng tamang sagot sa puso ko.",
    "Kung may control panel ang puso mo, sana ako ang admin nito.",
    "Kung ang buhay ko ay isang function, ikaw ang forever return value ko.",
    "Para kang HTML, kasi ikaw ang structure ng buhay ko.",
    "Kung ang puso ko ay isang program, ikaw ang pinaka-importanteng variable.",
    "Kung may bug man ang puso ko, ikaw lang ang bug na hindi ko kayang ayusin.",
    "Para kang CSS, kasi ikaw ang nagdadagdag ng style at kulay sa mundo ko.",
    "Ang pagmamahal ko sa’yo parang blockchain, hindi mababago at hindi mawawala.",
    "Kung ang buhay ko ay isang webpage, ikaw ang meta tag ng puso ko.",
    "Ikaw ang QR code na hindi ko kayang i-scan, pero alam kong ikaw lang ang sagot.",
    "Ikaw ang top result sa search engine ng puso ko.",
    "Kung may error 404 ang puso mo, ako ang solusyon sa lost connection mo.",
    "Kung ikaw ay isang framework, gusto kitang gamitin habambuhay.",
    "Ang puso ko parang AI model, self-learning pero ikaw lang ang pinaka-tamang data.",
    "Kung ako ay isang hacker, ikaw ang gusto kong i-hack para habambuhay kang mapasakin.",
    "Ikaw ang hardware na bumubuo ng system ng buhay ko.",
    "Kung love story ito, ikaw ang forever trending topic sa puso ko.",
    "Para kang CPU, kasi ikaw ang nagpapatakbo ng buong sistema ko.",
    "Ikaw ang auto-save function ng puso ko, kasi hindi kita kayang mawala.",
    "Kung may virus ka sa puso ko, hindi ko ito ide-delete kasi gusto kitang manatili.",
    "Para kang keyboard, kasi hindi ko kayang mag-function nang wala ka.",
    "Kung merong cheat code ang buhay, gusto kong gamitin ito para mapasakin ka.",
    "Ikaw ang pinaka-high priority task sa CPU ng puso ko.",
    "Kung ikaw ay isang programming language, ikaw ang pipiliin kong gamitin habambuhay.",
    "Hindi kita i-uninstall kahit ma-full storage na ang puso ko.",
    "Kung ako ang server, ikaw ang client na gusto kong pagsilbihan habang-buhay.",
    "Ikaw ang CDN ng puso ko, kasi kahit saan ako mapunta, ikaw pa rin ang pinakamalapit sa akin.",
    "Kung may lag man sa buhay ko, ikaw ang fastest connection na bumabalik sa akin.",
    "Ikaw ang pinaka-secure na password ng puso ko, hindi ko ipapamigay kahit kanino.",
    "Para kang captcha, kahit mahirap intindihin minsan, alam kong totoo ka.",
    "Kung ang puso ko ay isang motherboard, ikaw ang pinakasentral na parte nito.",
    "Ikaw ang infinite loop na hindi ko gustong i-break.",
    "Ikaw ang main function ng buhay ko, wala kang katulad.",
    "Kung ang buhay ko ay isang HTML document, ikaw ang title tag nito.",
    "Para kang JavaScript, kasi dinadala mo ang interactivity sa puso ko.",
    "Ikaw ang perfect algorithm sa messy data ng buhay ko.",
    "Hindi ko na kailangang mag-debug, kasi ikaw lang ang gusto kong solution.",
    "Kung meron akong AI model, ikaw lang ang gusto kong training data.",
    "Para kang git repository, hindi kita kayang i-reset kasi ayokong mawala ka.",
    "Kung meron akong IDE, gusto kong i-code ang future natin magkasama.",
    "Ikaw ang preferred language ng puso ko, kahit anong mangyari.",
    "Kung ang puso ko ay isang command line, ikaw lang ang tamang syntax nito.",
    "Ikaw ang database ng puso ko, kasi hindi kita kayang burahin.",
    "Kung may software update ang puso ko, ikaw ang gusto kong install forever.",
    "Para kang server uptime, gusto kitang gawing 100% sa buhay ko.",
    "Ikaw ang master branch sa git repository ng puso ko.",
    "Kung meron akong cloud storage, gusto kong i-save ang bawat moment natin doon.",
    "Ikaw ang backbone framework ng buhay ko.",
    "Hindi kita i-rollback kahit may bugs, kasi ikaw lang ang tamang version ng buhay ko.",
    "Kung meron mang git commit sa buhay ko, ikaw ang final version ko.",
    "Para kang HTTPS, kasi ikaw lang ang secured connection ng puso ko.",
    "Hindi kita i-delete kahit may storage limit na ang puso ko.",
    "Kung may AI assistant ang buhay ko, sana ikaw ang magbigay ng sagot sa lahat ng tanong ko.",
    "Hindi ko na kailangan ng backup system, kasi ikaw ang forever ko.",
]

tl_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
