simple = [
    "Senin gülüşün, en güzel şiirden daha etkileyici.",
    "Gözlerin yıldızlardan bile daha parlak.",
    "Yanında zaman duruyor gibi hissediyorum.",
    "Seninle konuşmak, en sevdiğim şarkıyı dinlemek gibi.",
    "Kalbim, adını ezberlemiş gibi atıyor.",
    "Senin yanında olmak, baharın gelişini hissetmek gibi.",
    "Gözlerin kaybolmak isteyeceğim bir okyanus gibi.",
    "Sesin, en huzurlu melodiden bile daha güzel.",
    "Seninle her an, sonsuzluk gibi geliyor.",
    "Eğer seni rüyalarımda görebiliyorsam, hiç uyanmak istemem.",
    "Senin yanında olmak, en güzel rüyanın içinde olmak gibi.",
    "Gülüşün, en karanlık günümü bile aydınlatıyor.",
    "Senin yanındayken başka hiçbir şeyin önemi yok.",
    "Ellerin, tutulacak en güzel eller.",
    "Gözlerin, kaybolmak isteyeceğim bir masal diyarı gibi.",
    "Seninle konuşmak, kalbime şiir yazdırıyor.",
    "Her an seni düşünmekten kendimi alamıyorum.",
    "Senin adını duyunca bile içim ısınıyor.",
    "Kalbim, seninle olunca daha hızlı atıyor.",
    "Seninle geçen her saniye, ömre bedel.",
    "Bir gülüşünle tüm dünyam değişiyor.",
    "Senin sesini duymak, en güzel melodiye denk.",
    "Beni benden alan tek şey gözlerin.",
    "Seninle her şey daha anlamlı.",
    "Eğer aşk bir sanat ise, sen başyapıtsın.",
    "Yanında olmak, huzurun tanımı gibi.",
    "Kalbimin attığını hissetmek için seni düşünmem yetiyor.",
    "Senin yanındayken zamanın nasıl geçtiğini unutuyorum.",
    "Gözlerin, yıldızlardan bile daha büyüleyici.",
    "Senin yanında her şey daha güzel.",
    "Kalbim, senin için çarpıyor.",
    "Sana her baktığımda daha çok aşık oluyorum.",
    "Senin gülüşün, içimi ısıtan güneş gibi.",
    "Seninle konuşmak, en sevdiğim şarkıyı dinlemekten daha güzel.",
    "Yanında olunca dünyadaki en şanslı insan gibi hissediyorum.",
    "Seninle her şey daha anlamlı hale geliyor.",
    "Gözlerin beni benden alıyor.",
    "Senin yanındayken her şey yerli yerinde gibi hissediyorum.",
    "Bir gülüşünle tüm dünyam aydınlanıyor.",
    "Seninle olmak, rüyaların gerçeğe dönüşmesi gibi.",
    "Bana baktığında içimde kelebekler uçuşuyor.",
    "Seninle her an, sonsuzluk gibi.",
    "Senin adını duyunca bile gülümsüyorum.",
    "Seninle her gün, en güzel gün.",
    "Gözlerin kalbimin derinliklerine işliyor.",
    "Kalbim, senin için atıyor.",
    "Bir gülüşünle tüm dünyam değişiyor.",
    "Senin yanında kendimi kaybediyorum.",
    "Sana her baktığımda yeniden aşık oluyorum.",
    "Senin gülüşün, içimi ısıtan bir güneş gibi.",
    "Sesin, en huzurlu melodiden bile güzel.",
    "Yanında olmak, en güzel rüyaya dalmak gibi.",
    "Gözlerin, yıldızlardan bile parlak.",
    "Seninle her şey anlam kazanıyor.",
    "Kalbim, seni düşündükçe hızlanıyor.",
    "Sana her baktığımda içim huzur doluyor.",
    "Senin yanında zamanın nasıl geçtiğini unutuyorum.",
    "Gözlerin, beni benden alıyor.",
    "Sana her baktığımda daha çok seviyorum.",
    "Seninle olmak, mutluluğun tanımı gibi.",
    "Kalbim, sadece senin için atıyor.",
    "Seninle her şey daha güzel.",
    "Bana baktığında içimde kelebekler uçuşuyor.",
    "Seninle her gün, en güzel gün.",
    "Bir gülüşünle tüm dünyam aydınlanıyor.",
    "Seninle olmak, rüyaların gerçeğe dönüşmesi gibi.",
    "Gözlerin, beni büyülüyor.",
    "Seninle konuşmak, en güzel hikayeyi dinlemek gibi.",
    "Kalbim, seni düşündükçe hızlanıyor.",
    "Senin yanında her şey daha anlamlı hale geliyor.",
    "Bana baktığında içim huzur doluyor.",
    "Gözlerin, kaybolmak isteyeceğim bir okyanus gibi.",
    "Seninle konuşmak, kalbime şiir yazdırıyor.",
    "Yanında olunca dünyadaki en şanslı insan gibi hissediyorum.",
    "Gözlerin, yıldızlardan bile daha büyüleyici.",
    "Senin yanındayken her şey yerli yerinde gibi hissediyorum.",
    "Bir gülüşünle tüm dünyam değişiyor.",
    "Seninle her şey anlam kazanıyor.",
    "Kalbim, senin için çarpıyor.",
    "Sana her baktığımda içim huzur doluyor.",
    "Senin yanında zamanın nasıl geçtiğini unutuyorum.",
    "Gözlerin beni benden alıyor.",
    "Seninle olmak, mutluluğun tanımı gibi.",
    "Kalbim, sadece senin için atıyor.",
    "Seninle her şey daha güzel.",
    "Sana her baktığımda daha çok seviyorum.",
    "Yanında olmak, en güzel rüyaya dalmak gibi.",
    "Gözlerin, yıldızlardan bile parlak.",
    "Seninle her şey anlam kazanıyor.",
    "Kalbim, seni düşündükçe hızlanıyor.",
    "Bana baktığında içimde kelebekler uçuşuyor.",
    "Seninle her gün, en güzel gün.",
    "Bir gülüşünle tüm dünyam aydınlanıyor.",
    "Seninle olmak, rüyaların gerçeğe dönüşmesi gibi.",
    "Gözlerin, beni büyülüyor.",
    "Seninle konuşmak, en güzel hikayeyi dinlemek gibi.",
    "Kalbim, seni düşündükçe hızlanıyor.",
    "Senin yanında her şey daha anlamlı hale geliyor.",
    "Bana baktığında içim huzur doluyor."
]

simple = [
    "Gözlerine her baktığımda kayboluyorum, ama hiç kimse beni bulmasın istiyorum.",
    "Senin yanında olunca dünya dönmeyi bırakıyor, çünkü benim evrenim sadece sen oluyorsun.",
    "Gülüşün, karanlık gecemde doğan güneş gibi… İçimi sıcacık yapıyor.",
    "Kalbim sana her attığında yeni bir şiir yazıyor, ama en güzeli senin varlığın.",
    "Eğer aşk bir masalsa, ben seninle sonsuz sayfalı bir hikayenin içinde kaybolmak istiyorum.",
    "Parmakların yıldızlara dokunuyor olmalı, çünkü seninle her şey gökyüzü kadar büyüleyici.",
    "Senin sesini duymak, en sevdiğim melodinin hiç bitmemesini istemek gibi.",
    "Gözlerin öyle derin ki, kaybolsam bile bulunmak istemem.",
    "Seni düşünmek, en sevdiğim kitabı defalarca okumak gibi; her seferinde yeni bir anlam buluyorum.",
    "Kalbimde senin için ayrılmış bir oda var ve anahtarını sadece sen taşıyorsun.",
    "Yanında olmak, en huzurlu rüyanın içinde uyanmak gibi.",
    "Senin adını duyduğumda bile gülümsüyorum, bir de yanımda olduğunda halimi düşün.",
    "Seninle geçen her saniye, zamanı durdurmak istediğim bir an gibi.",
    "Ellerini tutmak, yıldızları avuçlarımda hissetmek gibi.",
    "Senin gözlerinde dans eden ışık, içimi ısıtan en güzel ateş.",
    "Sadece varlığın bile ruhumu şiirlerle dolduruyor.",
    "Eğer aşk bir denizse, seninle birlikte sonsuza kadar yüzmek isterim.",
    "Senin yanındayken nefes almayı unutuyorum, çünkü kalbim her şeyi senin için yapıyor.",
    "Kalbimdeki en özel melodi, senin sesinin yankısı.",
    "Yanındayken hayat bir film gibi, ama en güzel sahnesi hep senin olduğun yer.",
    "Seni her gördüğümde kalbim yeniden aşık oluyormuş gibi çarpıyor.",
    "Gözlerin, karanlık gecelerime doğan en parlak ay gibi.",
    "Yanında olunca dünya daha renkli, daha canlı, daha büyülü.",
    "Aklımda tek bir melodi var ve o da senin sesin.",
    "Seninle geçen her an, kalbimde sonsuza kadar yankılanacak bir anı.",
    "Senin varlığın bile tüm kasvetli havayı dağıtan güneş gibi.",
    "Ellerini tuttuğumda, dünyadaki tüm yıldızlara dokunmuş gibi hissediyorum.",
    "Sana her baktığımda, bir tablonun en güzel detaylarını keşfediyormuş gibi hissediyorum.",
    "Seni her düşündüğümde içimde kelebekler uçuşuyor, ama bu kelebekler sana ulaşmak istiyor.",
    "Aşkı tarif etmem gerekirse, seni anlatırdım.",
    "Seninle konuşmak, gökyüzündeki yıldızlarla sohbet etmek gibi.",
    "Seninle her konuşmamda, kalbimde yeni bir şarkı yazılıyor.",
    "Hayatımın en güzel sürprizi, seni tanımış olmam.",
    "Kalbim, sadece senin dilini konuşuyor.",
    "Gözlerine her baktığımda, sonsuz bir evrenin içinde kayboluyorum.",
    "Eğer bir mevsim olsaydın, kesinlikle en güzel bahar olurdun.",
    "Gözlerin, bana unutulmaz masallar anlatıyor.",
    "Kalbimde bir not defteri var ve her sayfasında sen varsın.",
    "Senin yanında dünya bile daha yavaş dönüyor, çünkü her anı uzatmak istiyorum.",
    "Gülüşün, en güzel şarkının nakaratı gibi; tekrar tekrar dinlemek istiyorum.",
    "Aşkı öğrenmek istiyorsam, sadece sana bakmam yeter.",
    "Ellerini tuttuğumda zaman duruyor gibi hissediyorum.",
    "Seni tanıdıktan sonra, her şiir seni anlatıyor gibi geliyor.",
    "Seninle konuşmak, içimdeki tüm çiçekleri açtırıyor.",
    "Kalbim, senin gülüşüne ayarlanmış bir ritimde atıyor.",
    "Seni her düşündüğümde kalbimde bir yıldız parlıyor.",
    "Gözlerin, en gizemli romanın en büyüleyici sayfası gibi.",
    "Seninle her an, bir ömre bedel.",
    "Yanında olmak, sonsuz bir baharın içinde uyanmak gibi.",
    "Bir tek seninle birlikteyken, gerçek huzuru hissediyorum.",
    "Aşkın ne olduğunu bilmiyordum, ta ki seni tanıyana kadar.",
    "Sana her dokunduğumda dünyadaki tüm renkler daha parlak oluyor.",
    "Senin yanındayken kendimi bir masalın baş kahramanı gibi hissediyorum.",
    "Her sabah seni düşünerek uyanmak, en güzel güne başlama şekli.",
    "Kalbinin ritmi, benim en sevdiğim şarkının temposu gibi.",
    "Seninle geçen her an, sonsuzluk kadar değerli.",
    "Bir gülüşünle tüm dertlerimi unutuyorum.",
    "Eğer mutluluk bir kelimeyle anlatılsaydı, o kelime kesinlikle sen olurdun.",
    "Senin yanında zamanın nasıl geçtiğini unutuyorum.",
    "Gözlerinde kaybolmak, ama asla bulunmak istememek gibi.",
    "Kalbim senin adını fısıldıyor her gece.",
    "Senin varlığın bile hayatımda mucizeler yaratıyor.",
    "Eğer gözlerin bir şiirse, ben o şiiri ezberlemek isterim.",
    "Seninle konuşmak, rüzgarın okyanusa fısıldadığı en güzel şarkıyı dinlemek gibi.",
    "Ellerini tuttuğumda, kalbim bir maraton koşucusu gibi hızlanıyor.",
    "Senin yanındayken bile seni özlüyorum.",
    "Kalbimde bir yer var ve orası sadece senin için ayrılmış.",
    "Seninle her gün yeniden aşık oluyorum.",
    "Gözlerin, gökyüzündeki en parlak yıldızlardan bile daha etkileyici.",
    "Sana bakarken gözlerimi kaçırmamın sebebi, güzelliğinin beni büyülemesi.",
    "Seni düşündüğümde bile kalbim daha hızlı atıyor.",
    "Senin yanında olmak, en sevdiğim rüyanın içinde yaşamak gibi.",
    "Gözlerin, en güzel manzaranın bile önüne geçiyor.",
    "Sana her baktığımda, ruhumun derinliklerine işleyen bir huzur hissediyorum.",
    "Seninle her an, ömrümün en değerli anısı oluyor.",
    "Sana olan sevgim, gökyüzündeki yıldızlar kadar sonsuz.",
    "Eğer bir şiir olsaydın, en güzel mısraları sana yazardım."
]

tr_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
