simple = [
    "Em có biết anh yêu em không?",
    "Em làm anh quên hết mọi thứ xung quanh.",
    "Ánh mắt của em khiến anh không thể rời mắt.",
    "Em là điều tuyệt vời nhất mà anh từng gặp.",
    "Có phải em là thiên thần không?",
    "Em đẹp đến mức làm anh không thể thở nổi.",
    "Em có muốn cùng anh đi uống cà phê không?",
    "Anh muốn làm quen với em, được không?",
    "Nụ cười của em làm sáng bừng cả căn phòng.",
    "Anh có thể gọi em là 'mặt trời' không, vì em chiếu sáng cả cuộc đời anh.",
    "Em có thể làm anh quên đi tất cả nỗi buồn.",
    "Em là người duy nhất làm anh cảm thấy như vậy.",
    "Anh chỉ muốn được gần em mãi mãi.",
    "Em có tin vào tình yêu sét đánh không?",
    "Ánh mắt em làm trái tim anh đập loạn nhịp.",
    "Chỉ cần em cười, cả thế giới này sẽ đẹp hơn.",
    "Anh nghĩ em là người duy nhất có thể làm anh hạnh phúc.",
    "Anh muốn dành thời gian bên em, có thể không?",
    "Anh muốn được gọi em là của anh.",
    "Cảm giác bên em thật tuyệt vời.",
    "Em luôn là điều khiến anh mỉm cười mỗi ngày.",
    "Có ai đó đang nghĩ đến em đây.",
    "Anh không thể rời mắt khỏi em.",
    "Em có biết em quyến rũ như thế nào không?",
    "Anh chỉ muốn giữ em bên mình mãi mãi.",
    "Có thể em không biết, nhưng em làm trái tim anh loạn nhịp.",
    "Em như một ngôi sao sáng giữa bầu trời tối.",
    "Anh nghĩ anh đã tìm được người đặc biệt rồi.",
    "Em làm anh cảm thấy như mình là người may mắn nhất.",
    "Em có thể làm cho anh cười cả ngày.",
    "Anh muốn đưa em đi đâu đó thật đặc biệt.",
    "Tình yêu của anh dành cho em là mãi mãi.",
    "Em có muốn cùng anh ngắm hoàng hôn không?",
    "Mỗi lần nhìn thấy em, anh lại cảm thấy như lần đầu tiên.",
    "Anh có thể biết tên của em được không?",
    "Em làm anh muốn trở thành người tốt hơn mỗi ngày.",
    "Nếu em là một giấc mơ, thì anh không muốn tỉnh dậy.",
    "Em luôn là lý do khiến anh hạnh phúc.",
    "Câu hỏi duy nhất anh muốn hỏi là, em có yêu anh không?",
    "Em làm anh cảm thấy mình thật may mắn.",
    "Em là người làm cuộc sống anh thêm màu sắc.",
    "Anh đã ngắm nhìn em cả ngày rồi.",
    "Không có gì đẹp hơn nụ cười của em.",
    "Em luôn làm cho mọi thứ trở nên tuyệt vời hơn.",
    "Có thể em không biết, nhưng em là người làm anh mơ mộng.",
    "Em là điều ngọt ngào nhất trong cuộc sống anh.",
    "Anh không thể rời mắt khỏi vẻ đẹp của em.",
    "Chỉ cần có em, mọi thứ sẽ trở nên hoàn hảo.",
    "Mỗi lần em nói chuyện, trái tim anh lại đập nhanh hơn.",
    "Anh muốn được nắm tay em mãi mãi.",
    "Em có cảm nhận được sự đặc biệt giữa chúng ta không?",
    "Anh thấy mình may mắn khi được gặp em.",
    "Em là nguồn cảm hứng để anh làm mọi việc.",
    "Anh không thể ngừng nghĩ về em.",
    "Tình yêu của anh dành cho em là không thể diễn tả.",
    "Anh muốn dành cả cuộc đời này bên em.",
    "Em có muốn cùng anh xem một bộ phim không?",
    "Anh không cần gì cả, chỉ cần em bên cạnh.",
    "Có phải em là người làm thế giới này đẹp hơn không?",
    "Em là lý do anh tin vào tình yêu.",
    "Anh có thể làm gì để em luôn cười?",
    "Em có thể trở thành phần quan trọng trong cuộc đời anh không?",
    "Anh sẽ làm mọi thứ để em hạnh phúc.",
    "Em là những giấc mơ đẹp nhất của anh.",
    "Anh luôn muốn làm cho em cảm thấy đặc biệt.",
    "Em là người khiến trái tim anh ngừng đập.",
    "Chỉ cần em cười, thế giới này đã trở nên đẹp hơn.",
    "Anh nghĩ em có một sức hút không thể cưỡng lại.",
    "Em là lý do anh cảm thấy thế giới này tốt đẹp hơn.",
    "Anh không thể tìm thấy ai khác như em.",
    "Em là ngôi sao sáng nhất trong bầu trời của anh.",
    "Em có biết rằng em làm anh cảm thấy hạnh phúc mỗi ngày?",
    "Anh muốn dành cả cuộc đời này để yêu em.",
    "Em làm anh muốn trở thành người tốt hơn.",
    "Anh chưa bao giờ gặp ai đặc biệt như em.",
    "Em làm anh muốn làm mọi điều tốt đẹp.",
    "Anh nghĩ rằng chúng ta được sinh ra để dành cho nhau.",
    "Em là người duy nhất khiến anh cảm thấy như vậy.",
    "Anh chưa bao giờ cảm thấy vậy với ai cả.",
    "Em có thể làm anh cười ngay cả khi không muốn.",
    "Chỉ cần em ở bên cạnh, anh sẽ cảm thấy vui vẻ.",
    "Anh luôn cảm thấy bình yên khi ở bên em.",
    "Mỗi khi nhìn thấy em, trái tim anh lại nhảy lên.",
    "Em có thể làm anh quên hết mọi lo âu.",
    "Anh nghĩ mình sẽ chẳng bao giờ tìm thấy ai đặc biệt như em.",
    "Em khiến anh cảm thấy cuộc sống này thật tuyệt vời.",
    "Mỗi lần em cười, anh cảm thấy hạnh phúc.",
    "Anh muốn đưa em đi khắp nơi trên thế giới.",
    "Em có biết em quyến rũ đến mức nào không?",
    "Anh muốn dành thời gian cùng em mọi lúc.",
    "Em là giấc mơ của anh trở thành hiện thực.",
    "Anh nghĩ chúng ta sẽ có một mối quan hệ tuyệt vời.",
    "Em làm anh cảm thấy yêu đời hơn bao giờ hết.",
    "Anh muốn cùng em chia sẻ mọi khoảnh khắc đẹp trong cuộc đời.",
    "Em là người anh muốn dành cả cuộc đời để yêu thương.",
    "Có phải em là người anh đang tìm kiếm suốt cuộc đời này không?",
    "Mỗi khi em nói, anh lại muốn nghe mãi không thôi.",
    "Anh muốn là người đầu tiên chúc em một ngày tuyệt vời.",
    "Em làm trái tim anh đập nhanh hơn mỗi khi chúng ta gặp nhau.",
    "Anh cảm thấy rất may mắn khi có em trong cuộc đời.",
    "Em là điều tuyệt vời nhất mà anh từng gặp.",
    "Anh sẽ luôn ở đây bên cạnh em, dù có chuyện gì xảy ra.",
    "Em làm cho anh cảm thấy như là một người đặc biệt."
]

advance = [
    "Em có biết rằng mỗi lần anh nhìn thấy em, mọi thứ xung quanh đều mờ nhạt đi không?",
    "Cảm giác khi anh ở bên em, nó khiến anh quên đi mọi nỗi lo, chỉ còn lại niềm vui và hạnh phúc.",
    "Anh không thể tìm được từ nào đủ để miêu tả em, vì em hoàn hảo theo cách riêng của mình.",
    "Em làm cho anh tin rằng tình yêu thật sự không phải chỉ là cảm xúc, mà là sự kết nối sâu sắc giữa hai trái tim.",
    "Em có biết rằng trong từng khoảnh khắc anh ở bên em, anh cảm thấy như mình đang sống trong một giấc mơ ngọt ngào không?",
    "Ánh mắt của em chứa đựng cả vũ trụ, mỗi lần nhìn vào đó, anh như lạc vào một thế giới đầy bí ẩn.",
    "Anh đã từng nghĩ rằng tình yêu là thứ xa vời, nhưng rồi em xuất hiện và mọi thứ thay đổi.",
    "Chỉ cần em cười, cả thế giới này như trở nên tươi đẹp hơn, khiến anh quên đi mọi mệt mỏi của cuộc sống.",
    "Anh không thể diễn tả được cảm giác khi em nắm tay anh, như thể cả vũ trụ này chỉ có chúng ta.",
    "Em có biết rằng trái tim anh bắt đầu đập mạnh hơn mỗi khi em bước vào phòng không?",
    "Cảm giác khi anh được ở bên em, như là hòa mình vào một bản nhạc tuyệt vời mà em là giai điệu chính.",
    "Anh có cảm giác như em là người mà số phận đã sắp đặt để đến bên anh, để làm cuộc đời anh thêm ý nghĩa.",
    "Chỉ cần có em, anh cảm thấy như mọi giấc mơ đều trở thành hiện thực, và tất cả đều trở nên có ý nghĩa.",
    "Em là ngọn lửa làm bừng sáng cả thế giới của anh, khiến anh cảm nhận được niềm đam mê và khát khao sống.",
    "Mỗi lần em nhìn anh, anh không thể không nghĩ rằng em là điều tuyệt vời nhất mà cuộc sống này ban tặng cho anh.",
    "Em có thể làm anh quên đi thời gian, chỉ vì một nụ cười từ em.",
    "Anh sẽ không bao giờ ngừng nghĩ về em, vì em là người duy nhất làm trái tim anh đập loạn nhịp như vậy.",
    "Có phải em là người duy nhất mà anh có thể nhìn mà không bao giờ cảm thấy mệt mỏi không?",
    "Anh muốn đi qua cuộc đời này cùng em, để chúng ta cùng nhau viết nên câu chuyện tình yêu đẹp nhất.",
    "Nếu em là một cuốn sách, thì anh sẽ đọc đi đọc lại mỗi trang, mỗi câu chữ chỉ vì em khiến anh cảm thấy mê đắm.",
    "Em giống như một bức tranh sống động mà anh muốn chiêm ngưỡng suốt cả cuộc đời.",
    "Trái tim anh không bao giờ muốn xa em, vì em là lý do khiến mỗi ngày của anh trở nên đặc biệt.",
    "Anh không cần gì hơn ngoài việc được nhìn thấy em hạnh phúc, vì đó là điều làm anh cảm thấy trọn vẹn.",
    "Tình yêu của anh dành cho em không chỉ là một cảm xúc nhất thời, mà là một lời hứa sẽ tồn tại mãi mãi.",
    "Em làm cho trái tim anh muốn khám phá hết tất cả những điều tuyệt vời trong thế giới này, chỉ để mang lại niềm vui cho em.",
    "Anh cảm thấy như mình là người may mắn nhất trên đời khi được gặp em, người mà làm cho mọi thứ trở nên tốt đẹp.",
    "Anh không thể tưởng tượng cuộc sống này sẽ như thế nào nếu thiếu em, vì em chính là lý do khiến mọi thứ trở nên có ý nghĩa.",
    "Em không chỉ đẹp về ngoại hình, mà cả về tâm hồn, điều đó làm anh yêu em hơn mỗi ngày.",
    "Anh không thể ngừng nghĩ về những khoảnh khắc tuyệt vời mà chúng ta đã có, và mong chờ những khoảnh khắc sắp tới.",
    "Có một điều anh muốn nói với em, đó là anh sẽ luôn ở đây, bên cạnh em, dù cho thế giới này có thay đổi như thế nào đi nữa.",
    "Mỗi ngày trôi qua, anh lại càng nhận ra rằng em là món quà tuyệt vời nhất mà anh từng nhận được từ cuộc đời.",
    "Khi em cười, cả thế giới này dường như trở nên nhẹ nhàng hơn, và mọi khó khăn đều có thể vượt qua.",
    "Anh không muốn chỉ là một phần trong cuộc đời em, mà là người duy nhất em nghĩ đến mỗi khi em cần sự an ủi.",
    "Em giống như một ngôi sao sáng giữa bầu trời đêm, và anh là người may mắn được nhìn thấy vẻ đẹp của em mỗi ngày.",
    "Em không chỉ là một phần của cuộc sống anh, em là tất cả những gì anh muốn có trong cuộc đời này.",
    "Anh yêu cách mà em khiến mọi thứ trở nên nhẹ nhàng và vui vẻ, mỗi khoảnh khắc bên em đều đáng nhớ.",
    "Anh không cần biết tương lai sẽ ra sao, nhưng nếu có em ở bên, thì mọi thứ đều trở nên tuyệt vời.",
    "Em là người khiến anh tin rằng tình yêu thực sự có thể thay đổi cuộc sống, làm cho mọi thứ trở nên có ý nghĩa.",
    "Anh luôn nghĩ rằng một ngày nào đó em sẽ trở thành một phần quan trọng trong cuộc đời anh, và giờ điều đó đã thành hiện thực.",
    "Có một điều đặc biệt về em, đó là em khiến anh cảm thấy hạnh phúc chỉ bằng một cái nhìn hoặc một nụ cười của em.",
    "Nếu em là một vần thơ, thì anh sẽ là người đọc nó hàng ngày, cảm nhận từng chữ, từng câu em mang đến.",
    "Chỉ cần có em, anh cảm thấy mọi thứ trở nên hoàn hảo, và không có gì quan trọng hơn việc được ở bên em.",
    "Em không chỉ là người anh yêu, mà là người bạn đồng hành mà anh muốn chia sẻ mọi khoảnh khắc trong cuộc sống này.",
    "Anh muốn cho em thấy rằng tình yêu không chỉ là cảm xúc mà là một sự cống hiến suốt đời.",
    "Mỗi lần em nhìn anh, anh cảm thấy như trái tim mình không thể đập bình thường nữa, chỉ vì em là tất cả.",
    "Anh yêu cách mà em làm cho mọi thứ trở nên thú vị và đầy màu sắc, ngay cả những khoảnh khắc bình thường nhất.",
    "Em làm anh cảm thấy như mình là người duy nhất quan trọng trên thế giới này, và anh muốn làm cho em cảm thấy như vậy mãi mãi.",
    "Em không chỉ làm cho cuộc đời anh đẹp hơn, mà còn làm cho anh tin vào phép màu của tình yêu.",
    "Anh sẽ không bao giờ dừng yêu em, vì em là người duy nhất khiến trái tim anh cảm thấy trọn vẹn.",
    "Em giống như một bức tranh hoàn hảo, không có gì có thể làm em trở nên hoàn hảo hơn nữa.",
    "Chỉ cần em ở bên, anh cảm thấy như mọi lo lắng đều tan biến, và chỉ còn lại niềm vui trong tim.",
    "Anh muốn là người đầu tiên em nghĩ đến mỗi khi em cần ai đó, và là người duy nhất em tin tưởng.",
    "Em khiến anh cảm thấy rằng tình yêu không phải là sự ngẫu nhiên, mà là điều sắp đặt của số phận.",
    "Anh không thể tưởng tượng cuộc sống này nếu thiếu em, vì em là ánh sáng chiếu rọi trong thế giới tối tăm của anh.",
    "Anh sẽ không bao giờ ngừng yêu em, vì em là người duy nhất làm trái tim anh cảm thấy sống động như vậy.",
    "Em giống như một câu chuyện tình yêu đẹp mà anh muốn kể mãi không dừng.",
    "Mỗi khoảnh khắc bên em đều làm anh cảm thấy như mình đang sống trong một câu chuyện cổ tích.",
    "Em làm cho mọi ngày của anh trở nên đặc biệt, và anh muốn dành cả cuộc đời này để làm cho em cảm thấy như vậy.",
    "Anh nghĩ rằng chúng ta đã gặp nhau vì một lý do, và đó là để tạo ra một tình yêu vĩnh cửu.",
    "Em giống như một viên ngọc quý giá, mà anh sẽ luôn trân trọng và bảo vệ suốt đời.",
    "Anh không biết làm thế nào để thể hiện hết tình cảm của mình với em, nhưng chỉ cần em ở bên, anh cảm thấy đủ đầy.",
    "Em là người khiến anh tin rằng tình yêu không chỉ là cảm xúc, mà là một sự kết nối sâu sắc giữa hai tâm hồn.",
    "Anh yêu cách mà em nhìn thế giới, nó khiến anh nhìn cuộc sống này qua một lăng kính hoàn toàn khác.",
    "Mỗi khi chúng ta ở bên nhau, thời gian dường như ngừng lại, và chỉ có tình yêu giữa chúng ta là tồn tại mãi mãi.",
    "Anh muốn chia sẻ mọi điều trong cuộc sống này với em, vì em là người mà anh muốn bên cạnh mãi mãi.",
    "Em là lý do khiến anh không ngừng tìm kiếm những điều tốt đẹp trong cuộc sống này.",
    "Anh tin rằng cuộc sống này chỉ thực sự trọn vẹn khi có em trong đó, và anh muốn cùng em đi qua mọi thăng trầm.",
    "Chỉ cần nhìn vào mắt em, anh cảm thấy như mình đang tìm thấy một phần của chính mình.",
    "Em không chỉ là một phần trong cuộc đời anh, mà là tất cả những gì anh cần để cảm thấy hạnh phúc.",
    "Anh yêu cách mà em làm cho thế giới này trở nên đáng yêu và đáng sống hơn mỗi ngày.",
    "Anh sẽ làm mọi điều để em cảm thấy mình là người quan trọng nhất trong cuộc đời anh.",
    "Em là lý do anh tin vào tình yêu, và cũng là lý do anh muốn yêu em mãi mãi."
]

vi_flirt = {key: value for key, value in {
    "simple": simple,
    "advance": advance,
    "all": sum([simple, advance], [])
}.items()}
